### ISSUE TITLE
IntroActivity.kt line 105

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#104]
#### in com.pitchedapps.frost.activities.IntroActivity.finish

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/597fd1f1be077a4dcc69097a?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/597fd1f1be077a4dcc69097a?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Fixed in d23b266
