### ISSUE TITLE
Ads everywhere the last few days

### ISSUE THREAD

**Issue by rancidfrog** [AllanWang/Frost-for-Facebook#1069]
A few days ago ads start appearing everywhere in stream.
v.2.0.1

**Comment by AllanWang** [comment]
I've been unable to work on my personal projects during my internship. I'm sure a lot of stuff within facebook has changed, and I will be fixing them in September/October

**Comment by AllanWang** [comment]
Can  you confirm whether this is still an issue? I've rebuilt the app and toggling the ads does make a difference. Perhaps you are seeing ads that I'm not
