### ISSUE TITLE
DataUtil.java line 163

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#109]
#### in org.jsoup.a.b.a

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5984a47bbe077a4dcc9bb01d?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5984a47bbe077a4dcc9bb01d?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Nonfatal timeout exception
