### ISSUE TITLE
Notification List Not Found

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#111]
#### in ca.allanwang.kau.e.b.e

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5984d316be077a4dcc9d87a4?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5984d316be077a4dcc9d87a4?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Notification List not found

**Comment by AllanWang** [comment]
TODO: Add means to fetch html contents with user permissions for debugging
