### ISSUE TITLE
SwipeBackHelper.kt line 20

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#117]
#### in ca.allanwang.kau.swipe.c.c

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5985c7f9be077a4dcca58410?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5985c7f9be077a4dcca58410?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Addressed in KAU v3.2.5
