### ISSUE TITLE
When a post is liked, the like button should turn blue

### ISSUE THREAD

**Issue by dineshmj** [AllanWang/Frost-for-Facebook#1203]
When the user likes a post by clicking the "like" button, it should turn to Blue so that the user can make out that she / he has liked it already, and can press again to "unlike" the post. As of now, even after liking, the button remains as before.

**Comment by AllanWang** [comment]
I see it. Facebook changes their website pretty often so the css attribute associated with a liked post has probably changed. If I have time I will fix it within the next week or two but definitely by the end of december

**Comment by dineshmj** [comment]
Thank you very much for your reply, sir! Great to see Frost evolving!

Thank you, and regards

Dinesh Muciliath Jayadevan

Sent from my Samsung Galaxy Note 8. 
 
  On Wed, Nov 28, 2018 at 3:48 AM, Allan Wang<notifications@github.com> wrote:   
I see it. Facebook changes their website pretty often so the css attribute associated with a liked post has probably changed. If I have time I will fix it within the next week or two but definitely by the end of december
