### ISSUE TITLE
Strings.kt

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#121]
#### in kotlin.h.v.c

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59876b9abe077a4dccb33a0a?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59876b9abe077a4dccb33a0a?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
on page finished null string

**Comment by AllanWang** [comment]
Addressed in dea024999ec7888c54da34f02550e55872036437

**Comment by AllanWang** [comment]
Test dea0249
