### ISSUE TITLE
Feature: Option to lock the top bar so it doesn't hide when scrolling down

### ISSUE THREAD

**Issue by pkillnine** [AllanWang/Frost-for-Facebook#1237]
It would be good to have a setting that prevents the top bar from hiding when scrolling down.

**Comment by AllanWang** [comment]
This is not hard to do but will be very low priority. As of now, the benefits of a hiding top bar is to help with screen real estate. Unless I come up with a clear way to show the designs of each view type, I won't be adding this.

**Comment by AllanWang** [comment]
I'm going to close this as it's pretty typical for apps to allow toolbar scrolling. Other stuff like the fab hide too to provide screen real estate
