### ISSUE TITLE
Opening URL from browser in Frost leads to Desktop version

### ISSUE THREAD

**Issue by edo0** [AllanWang/Frost-for-Facebook#1245]
As per title, when opening a Facebook URL in my browser (latest Chromium-based Brave on Android 6) and am prompted to Frost, Frost tries to load the desktop version and not the equivalent mobile version

**Comment by AllanWang** [comment]
Do you have a link as an example? I'll test it out during the winter break

**Comment by AllanWang** [comment]
Thanks. May be fixed when I change the user agent. Related to https://github.com/AllanWang/Frost-for-Facebook/issues/1229
