### ISSUE TITLE
emoticons are posted in separate message

### ISSUE THREAD

**Issue by hramrach** [AllanWang/Frost-for-Facebook#1253]
When writing a message pressing the emoticon button and selecting an emoticon does not insert an emoticon into the message as it does on FB itself and most software that makes use of emoticons.

Instead it posts a separate message with the selected emoticon and keeps the message box with the text as-is.

**Comment by AllanWang** [comment]
This sounds like a bug specific with facebook. Note that this is a facebook wrapper, so most of the functionality is beyond my control. You can try this in touch.facebook.com on your desktop to see if it works, and if the behaviour is different you can let me know. Note that this won't work on mobile unless you have a special user agent as Facebook doesn't allow viewing messages without their own app

**Comment by hramrach** [comment]
This works as expected when using FB.com directly so I am not sure how facebook is responsible for this one.

**Comment by AllanWang** [comment]
Try it on touch.facebook.com. The feature set is quite different from fb.com
