### ISSUE TITLE
suggestion UI scrolling issue in liked pages

### ISSUE THREAD

**Issue by hramrach** [AllanWang/Frost-for-Facebook#1254]
When you get to the liked pages you get list of pages you liked which is vertical and list of page suggestions which is horizontal.

You can scroll in this suggestion list to the right but when scrolling to the left the whole liked pages UI is closed.

**Comment by AllanWang** [comment]
Is this with the overlay page? There are two options. You can either disable swipe to go back in settings, which will fix all horizontal scroll issues, or you can hold and scroll. Holding and scrolling will disable horizontal swipes (in the overlay and the main page). It may conflict with holding to view images or links, but those typically aren't in horizontal scroll views.

**Comment by hramrach** [comment]
That setting does not work for me. Whichever way I flip it overlays are still closed by scrolling.

**Comment by AllanWang** [comment]
Just so we're clear, you've disabled "overlay full screen swipe to dismiss" correct? And the overlay is still sliding when you swipe right? I just tested it and it seems to be working fine.

Please also post your app version if there are further updates to this question

**Comment by AllanWang** [comment]
That already exists as well (Viewpager swipe)

**Comment by hramrach** [comment]
Yes, there is an option for that. Unfortunately, I did not find any option to disable reload on scrolling down.
