### ISSUE TITLE
Add tab for "Friend Requests"

### ISSUE THREAD

**Issue by sreejithpm92** [AllanWang/Frost-for-Facebook#1261]
Frost is a wonderful alternative to official facebook app/ mobile web version. I really loved the app.

There is no tab for "Friend Requests" with icon showing number of new friend requests. This is available in the mobile web version of facebook. Please add that.

Thanks

**Comment by AllanWang** [comment]
I think I responded to your email already, but for future reference, the tabs can be changed from Settings > Appearance > Main Activity Tabs
