### ISSUE TITLE
ads are still showing in news feed 

### ISSUE THREAD

**Issue by vsinghm3** [AllanWang/Frost-for-Facebook#1262]
here link to screenshot https://paste.pics/4E0I6

**Comment by AllanWang** [comment]
I will take a look at this again in future updates. Note that the main posts I filter are the ones that are independent sponsored posts. If a post is liked by a friend and happens to be sponsored, then it might not be different from other liked posts

**Comment by AllanWang** [comment]
No further ads can be filtered yet
