### ISSUE TITLE
java.lang.NoSuchMethodError in KeyChainService.java:95

### ISSUE THREAD

**Issue by AllanWang** [AllanWang/Frost-for-Facebook#1268]
## Error in Frost for Facebook

**java.lang.NoSuchMethodError** in **KeyChainService.java:95**
No direct method <init>()V in class Landroid/security/IKeyChainService$Stub; or its super classes (declaration of 'android.security.IKeyChainService$Stub' appears in /system/framework/framework.jar!classes2.dex)

[View on Bugsnag](https://app.bugsnag.com/pitched-apps/frost-for-facebook/errors/5c252f25f27ad3001aa0df44?event_id=5c252f25003209def04a0000&i=gh&m=ci)

## Stacktrace

    KeyChainService.java:95 - com.android.keychain.KeyChainService$1.<init>

[View full stacktrace](https://app.bugsnag.com/pitched-apps/frost-for-facebook/errors/5c252f25f27ad3001aa0df44?event_id=5c252f25003209def04a0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Tolriq** [comment]
@AllanWang Sorry to post here but I'm recently facing this exact crash and you are the only one visible with that one :) Hoping that by closing you'd have some information to share? :)

**Comment by AllanWang** [comment]
@Tolriq unfortunately no. None of the logs were particularly useful in determining the cause of the problem, and I couldn't find this problem within my own devices

**Comment by Tolriq** [comment]
Trying to find some matches between libraries versions updates in both apps and it seems both had the issue appearing after updating to kotlin 1.3.11. 
Other possible changes for me would be AndroidX annotation 1.0.1 or Android gradle plugin 3.3.0 RC2 then final.
Do you remember any other changes in libraries in your version 2.1.2?
