### ISSUE TITLE
Webview too wide

### ISSUE THREAD

**Issue by jmaris** [AllanWang/Frost-for-Facebook#1318]
Sites do not adapt to screen size, as if the reported screen size was larger than the actual screen size, as a result I have to scroll horizontally to see the page, which is really tough considering swipe brings up side menus.

**Comment by AllanWang** [comment]
What phone do you have? Does this apply to the newsfeed or other pages you load?

**Comment by jmaris** [comment]
Only to pages I load, and not to the newsfeed, on a moto e4

**Comment by AllanWang** [comment]
Are these pages linked from a facebook post? Does it resize properly on your mobile browser?

**Comment by jmaris** [comment]
It was fine with mobile browser but not with links I clicked from inside the app. However oddly since the last update the issue has dissapeared! Sorry for the trouble ^^
