### ISSUE TITLE
browser not show some links

### ISSUE THREAD

**Issue by chamfay** [AllanWang/Frost-for-Facebook#1319]
Hi,
Frost browser overlay or default browser can't open some links (shows blank page)
here is an example of url:
https://www.tech-wd.com/wd/2019/01/08/%d9%85%d8%a7%d9%8a%d9%83%d8%b1%d9%88%d8%b3%d9%88%d9%81%d8%aa-%d8%aa%d8%b2%d9%88%d8%af-%d9%85%d8%aa%d8%a7%d8%ac%d8%b1-%d9%83%d8%b1%d9%88%d8%ac%d8%b1-%d8%a8%d8%a7%d9%84%d8%aa%d9%82%d9%86%d9%8a%d8%a7/?fbclid=IwAR1GrZSE9ZNjcIB7v4W7qxAAc04wNLzub3VP6uJwpDixzLrbd4s0v-oKrEY

**Comment by AllanWang** [comment]
Can't replicate it on my device. Make sure you are using an update apk (currently version 2.2.1)
