### ISSUE TITLE
TimberLogger.kt line 65

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#132]
#### in ca.allanwang.kau.e.b.a

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/598a7793be077a4dcccf1ac1?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/598a7793be077a4dcccf1ac1?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Duplicate of #111
