### ISSUE TITLE
Support for lite mobile sites?

### ISSUE THREAD

**Issue by DarylSun** [AllanWang/Frost-for-Facebook#1320]
Facebook webpages stop working when on mobile data. Possibly because my ISP redirects then to either free.facebook.com or mbasic.facebook.com.

**Comment by AllanWang** [comment]
Did this work in previous versions?
Unfortunately, I won't be supporting any other formats as it adds extra maintenance, and I also can't access most of them (eg zero and free).

**Comment by DarylSun** [comment]
I'm not sure if these sites work in previous versions, since I only started using Frost last month. Maybe someone else can confirm? Anyway, thank you for the quick response!

**Comment by AllanWang** [comment]
I'm going to close this for now as there's little I can do even if others have this issue.
