### ISSUE TITLE
Theme only working for notification page

### ISSUE THREAD

**Issue by ThibautMouly** [AllanWang/Frost-for-Facebook#1321]
Hello,
The personalised theme doesn't work on the message and news feed pages (or at least it doesn't on my phone), while it does for the notification one.
It remains the standard Facebook theme there.
Is it a problem from the app or from my side?

**Comment by AllanWang** [comment]
Did it work for you in previous updates or are you a new user?
It's supposed to theme everything, but the newsfeed involves theming the webview whereas I create the layout for notifications. Maybe it will fix itself overtime

**Comment by ThibautMouly** [comment]
I am a new user.
Ok, then I will notify you here if it fixes by itself in the future.
Thanks!

**Comment by AllanWang** [comment]
Great. I'll close this for the time being.
