### ISSUE TITLE
Overlay crashes when no internet connection is provided

### ISSUE THREAD

**Issue by AllanWang** [AllanWang/Frost-for-Facebook#1323]

**Comment by AllanWang** [comment]
Try using `NonCancellable` around reload fun

**Comment by Salin1810** [comment]
I used lastest version Frost FB but this errors didn't fixed
![screenshot_20190130-120931](https://user-images.githubusercontent.com/31431375/51959777-937b6300-2488-11e9-9023-8ced9765e754.png)

**Comment by AllanWang** [comment]
Yeah this error is still open. I'm still working on the fix. The crash only applies to one page (menu) and I haven't truly found why yet. A lot of things is based around coroutines and I still need to understand some parts to find a proper solution
