### ISSUE TITLE
JsAssets.kt line 19

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#133]
#### in com.pitchedapps.frost.d.e.a

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/598b1039be077a4dccd517b5?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/598b1039be077a4dccd517b5?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Fixed 524a947
