### ISSUE TITLE
net::ERR_CLEARTEXT_NOT_PERMITTED

### ISSUE THREAD

**Issue by Qutaiba-Khader** [AllanWang/Frost-for-Facebook#1336]
After final release (version 2.2.1) i have this error

Webpage not available
The webpage at http://h.facebook.com/hr/r?redirect_app=....... Etc 

 could not be loaded because:

net::ERR_CLEARTEXT_NOT_PERMITTED

---- 
Clear data , uninstall and reinstall, change user...
All of them not working

Android 9 , oneplus 6t, oos 9

**Comment by AllanWang** [comment]
Yeah it's a new problem in android 9.

I've fixed it in #1331, so it will be in the next release
