### ISSUE TITLE
Reply to comments in Forst

### ISSUE THREAD

**Issue by Firemanpl** [AllanWang/Frost-for-Facebook#1341]
When I click on a reply to a comment I have to manually search for this post and then manually search for the comment.

**Comment by AllanWang** [comment]
What version are you on and where are you clicking from?

**Comment by Firemanpl** [comment]
V 2.2.1 I click on Notification. Sometimes when I click (Someone mentioned about you... Or someone odpowiersiał on the comment...)

**Comment by AllanWang** [comment]
Unfortunately that isn't something I can change, as the url does not seem to indicate any comment position.
