### ISSUE TITLE
Video not playing when audio is unmute

### ISSUE THREAD

**Issue by FaizKhan5** [AllanWang/Frost-for-Facebook#1354]
When I touch on audio unmute video stops and not playing and when i mute audio video playing

**Comment by AllanWang** [comment]
Try replicating the problem on touch.facebook.com on your desktop. This doesn't sound like something I'm controlling

**Comment by AllanWang** [comment]
Problem when autoplay is enabled. 
Setting exists for newer user agents at https://m.facebook.com/settings/videos/

**Comment by AllanWang** [comment]
Temp fixed added through #1386
