### ISSUE TITLE
Notifications not opening after clicking on them.

### ISSUE THREAD

**Issue by Pyro2677** [AllanWang/Frost-for-Facebook#1355]
When clicking on notifications sometimes and more like 75% of the time now the screen flashes like it Is loading the original post but the screen stays black. Eg someone replied to a post I made and when I try to view their comment from the notification screen it doesn't load the page. 
I'm using AMOLED theme and have tried different dark themes and the same thing happens.

**Comment by AllanWang** [comment]
Which version are you using? What if you manually pull down to refresh the blank page? Let me know if it loads as an error, because not all linked from Facebook can be loaded on a separate tab

**Comment by Pyro2677** [comment]
2.2.2 
Pulling down does nothing. 
It flashes briefly the like it is about to load but then it goes blank. I don't get an error if I press back it goes back to the notification page and clicking on another reply/like it works. Going back to the one I want still doesn't. If I close and remove Frost from recents and open again 50% chance it with work.

**Comment by AllanWang** [comment]
If it's specific only to some posts, unless you can identify the type for me to reproduce, it will be pretty hard to fix. Are you saying that even if you press the notification icon in the overlay (to load the notification list) and click the page notification, it doesn't work?

**Comment by Pyro2677** [comment]
Yes exactly.

**Comment by AllanWang** [comment]
If there is a reliable way to reproduce this issue you can let me know. But otherwise if it doesn't work even when clicking from the notification list (after pressing the notification icon), then that may be a bug with Facebook. There are no transitions on my end when you click the list.
