### ISSUE TITLE
Notification Frequency

### ISSUE THREAD

**Issue by kylebriffa7** [AllanWang/Frost-for-Facebook#1358]
Hello,

I would like to suggest a more frequent notification check. At the moment the least setting is 15mins. I keep finding myself missing out on messages which necessitate more frequent updates, say 5mins or ideally less.

Is there a limitation which I am missing which does not allow this frequency to be reduced?

Thank you for your work! :smiley:

**Comment by AllanWang** [comment]
15 min is the highest frequency if you want to use the `JobService`. 
This allows the OS to manage service requests, which should improve battery life.

Anything less would require a persistent background service, which I would not want to do.
