### ISSUE TITLE
RecyclerView.java line 2622

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#137]
#### in android.support.v7.widget.RecyclerView.onDetachedFromWindow

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/598b649dbe077a4dccd8e22d?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/598b649dbe077a4dccd8e22d?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Null reference

**Comment by AllanWang** [comment]
Search related; see https://github.com/AllanWang/KAU/pull/48
