### ISSUE TITLE
RecyclerView.java line 5859

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#138]
#### in android.support.v7.widget.RecyclerView$o.b

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/598b848abe077a4dccda0c1f?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/598b848abe077a4dccda0c1f?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Fixed in KAU
