### ISSUE TITLE
Editing an event iterates the date forward

### ISSUE THREAD

**Issue by rak5381** [AllanWang/Frost-for-Facebook#1385]
In any event I manage, every time I enter the edit mode, the event's ending date moves forward one day.

Not when I enter the date edit box, but the overall edit page. Pull-down refreshing the screen does the same: one day added.

I am using version 2.2.2 from f-droid

**Comment by AllanWang** [comment]
I'll try it out. If it launches an overlay, it may be that the url makes a request to move the date forward. That's a bit weird design wise, but I don't see how else that would happen.

**Comment by AllanWang** [comment]
Looks like it's Facebook's problem. Same thing happens if I try it in my browser. Refreshing also doesn't add a new day each time, which is what I thought was happening.
