### ISSUE TITLE
Posts with text on background always uses black text 

### ISSUE THREAD

**Issue by yaomtc** [AllanWang/Frost-for-Facebook#1388]
Some posts have larger text on one of a selection of Facebook's background images. Some of these are dark or have black, while the text - when viewed with Frost - is also black.

**Comment by AllanWang** [comment]
@yaomtc Try [this build](https://github.com/AllanWang/Frost-for-Facebook-APK-Builder/releases/tag/v2241) and let me know if it fixes it. It's a separate app, so no need to uninstall your current version

**Comment by yaomtc** [comment]
That fixed it, thanks!

**Comment by AllanWang** [comment]
Cool. You can use that build if you want until the next release version comes out
