### ISSUE TITLE
Bug found in frost for facebook when trying to set Privacy settings

### ISSUE THREAD

**Issue by jubreal** [AllanWang/Frost-for-Facebook#1404]
**Describe the bug**
When the privacy settings options are accessed, users be able to check and manage their "Blocking list", manage their "Timeline and Tagging" feature, use "Face Recognition" and manage and control who can see their post and contents all of which are under 'PRIVACY' in the app settings. But when the those listed are clicked to access it, it doesn't load only to display "no internet connection " even though there is an internet connection working perfectly.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Proflile Action Flowing Button' (The 3 horizontal lines by the right <beside notification icon> on the icon row)
2. Scroll down to 'Settings' and click on it
3. Click on any of these or all of them one after the other 'Privacy Settings', 'Face Recognition', 'Timeline and Tagging', and 'Blocking'.

**Details:**
 - App Version: 2.2.4
 - Device: Inifinix Note 3
 - Android Version: 6.0

**Video Recording**
https://youtu.be/WnVzxKIaMDA

**Comment by AllanWang** [comment]
Did you have to set anything from your facebook account to enable this? I don't have a  face recognition page in my account. Also try opening that section in your mobile browser, to see if it's a problem with Frost or Facebook. All the settings open in one page, so it seems unlikely that it's a problem on my end.

**Comment by jubreal** [comment]
The problem is from Frost end, it opened perfectly on the mobile browser, and it worked perfectly on the facebook app but doesn't work on Frost. But I noticed while facebook app was running underground, the pages opened on frost, but when I stopped the facebook app from running, Frost started giving the error message again.

**Comment by AllanWang** [comment]
Whether or not you have the official app running affects how Frost loads?
And this behaviour doesn't affect https://touch.facebook.com your mobile browser?
Even if this is a problem, I currently don't have an idea of the cause. I can leave this open for a while until there's a proper way to replicate the behaviour

**Comment by jubreal** [comment]
> Whether or not you have the official app running affects how Frost loads?
Yes, Frost seems to behave differently when the official app is running
> And this behaviour doesn't affect https://touch.facebook.com your mobile browser?
It actually affect it too, infact the side nav refuse to open at all on the mobile browser 
> Even if this is a problem, I currently don't have an idea of the cause. I can leave this open for a while until there's a proper way to replicate the behaviour
Have you carried the steps written in same test environment?

**Comment by jubreal** [comment]
And this is a picture of the error while trying to access the page on a laptop browser following the steps stated in the main report
![Screenshot (157)](https://user-images.githubusercontent.com/37203158/56488945-fc96d380-64d7-11e9-8acc-f815b1c7daff.png)

**Comment by AllanWang** [comment]
In that case I'm almost certain it's just a Facebook bug. It's very unlikely that the problem is frost specific since once it gets to the overlay, there's nothing special.
Facebook really doesn't invest much effort in maintaining the mobile website, so unfortunately it's probably just a parse error with a generic page. You can maybe check the console for more info.
