### ISSUE TITLE
Change the language of the application

### ISSUE THREAD

**Issue by Reek0** [AllanWang/Frost-for-Facebook#1413]
Hello!
The application appears to me in English in its majority and in Spanish in some parts. But Facebook appears to me in Spanish, that is, it is the interface of the Frost application that is mostly in English.

https://imageshost.eu/images/2019/05/01/IMG-20190501-WA0001.jpg
https://imageshost.eu/images/2019/05/01/IMG-20190501-WA0000.jpg

The device's default language is Spanish and it is a
Samsung Galaxy J2 Prime
Android 6.0.1
Frost v2.2.4

On the other hand as a comparison, in my other device the application is completely in Spanish, both the interface and Facebook and is a
Samsung SM J260M
Android Go 8.1.0
Frost v2.2.4
________________________________
Hola!
La aplicación me aparece en inglés en su mayoria y en español en algunas partes. Pero Facebook me aparece en español, es decir, es la interfaz de la aplicación Frost la que está en su mayoria en inglés.

El idioma por defecto del dispositivo es el español y es un
Samsung J2 Prime
Android 6.0.1
Frost v2.2.4

Por otro lado a modo de comparación, en mi otro dispositivo la aplicación está completamente en español, tanto la interfaz como el Facebook y es un
Samsung SM J260M
Android Go 8.1.0
Frost v2.2.4

**Comment by AllanWang** [comment]
In the app itself, translations exist here:

**Comment by AllanWang** [comment]
In the app itself, translations exist here:

https://crowdin.com/project/frost-for-facebook/es-ES#

and here:

https://crowdin.com/project/kotlin-android-utils/es-ES#

Most of them are complete, but if some are missing, you are free to contribute.

For the main contents itself (newsfeed etc), it takes on your Facebook settings. You may need to specify the language from there.

**Comment by AllanWang** [comment]
Hm I didn't see the images you sent before. It's probably because some parts aren't translated, and crowdin won't pull in incomplete translation files. Feel free to contribute if you wish

**Comment by AllanWang** [comment]
You can try [this test build](https://github.com/AllanWang/Frost-for-Facebook-APK-Builder/releases/tag/v2342) (uninstall old variants if you installed them recently).

**Comment by Reek0** [comment]
> You can try [this test build](https://github.com/AllanWang/Frost-for-Facebook-APK-Builder/releases/tag/v2342) (uninstall old variants if you installed them recently).

good afternoon!
Unfortunately the problem persists, followed the steps of first uninstalling Frost (and even pass the official Android cleaner just in case) and then install the new version, but it is still in English.

**Comment by AllanWang** [comment]
Make sure you've launched the test build in case you have both test builds and official builds installed.
The interface should be all in english now (which means your spanish variant may differ from the one provided), or all be in spanish. Can you check the newsfeed setting text to be sure?

**Comment by Reek0** [comment]
In fact, the application that I have is the one that was sent, uninstall the previous one.

It's totally in English that part

http://imageshost.eu/images/2019/05/02/IMG-20190501-WA0010.jpg

Although I wanted it totally in Spanish, sorry if my request was not understood.

**Comment by AllanWang** [comment]
Okay so it's working. What locale are you? There are multiple locales for spanish, and the one in Frost is for `es-rES`.

You can see that the resolution for Android < 7.0 isn't as you expect:

https://developer.android.com/guide/topics/resources/multilingual-support

As choosing spanish in another location will result in the default language.

You can either change your os language to match `es-rES`, or you can help verify that the translations are valid for your locale and I will copy them over.

If you are able to update to an android version later than 7.0 though, this resolution will also be fixed.

**Comment by Reek0** [comment]
ya encontré la solución. tenia el idioma del dispositivo en "Español (Estados Unidos)", lo cambie a "Español (España)" y el idioma de Frost se cambio a español totalmente.

muchas gracias por la atención y las respuestas!
____________________
I already found the solution. I had the language of the device in "Spanish (United States)", I changed it to "Spanish (Spain)" and the language of Frost was changed to Spanish completely.

thank you very much for the attention and the answers !!
