### ISSUE TITLE
friend request

### ISSUE THREAD

**Issue by duergrim** [AllanWang/Frost-for-Facebook#1419]
**Describe the feature**

Please add a feature that allows me to see current friend requests, and lets me see people who have accepted my friend request.

**Comment by AllanWang** [comment]
Is this not visible through the friends tab from the drawer? Note that you can also change the tabs through settings if you don't like the default 4. If this doesn't resolve it you can add more details

**Comment by duergrim** [comment]
My fault, didn't see it. Sorry.
