### ISSUE TITLE
Back to events without reloading

### ISSUE THREAD

**Issue by mcclaneonfire** [AllanWang/Frost-for-Facebook#1422]
When I scroll down in the events list - for example for today:
I click on an event,
then I go back and the events list reloads and I can't continue at the point in the list, where I left off.
Is it possible to not reload?

Thanx for your great work!

**Comment by AllanWang** [comment]
Looks like a Facebook bug as it also happens with my mobile browser. If you click an event then go back, it will reload the full page. However, subsequent page clicks will retain the list position without a reload. Unfortunately it's unlikely that I'll be able to fix this.
