### ISSUE TITLE
whatsnew is unhelpful

### ISSUE THREAD

**Issue by licaon-kter** [AllanWang/Frost-for-Facebook#1430]
`app/src/main/play/en-US/whatsnew` has a useless text with a non clickable link in F-Droid.

Yes, the changelog metadata entry works ok, but why not actually use that file `whatsnew` as expected and include... _what is new_?

**Comment by AllanWang** [comment]
Does what's new support html? I'll see if I can update my script to add the relevant changelog chunk.

**Comment by AllanWang** [comment]
Do you also know if the file needs to be there before a gradle build? If not I can gitignore it and make it a requirement for the build script

**Comment by licaon-kter** [comment]
IIRC this metadata is picked up on index rebuild/publish, not at build time.

The HTML situation... I don't know exactly, but I do know that it's a mismatch of different capabilities. :(
