### ISSUE TITLE
Groups tab unreadable in AMOLED theme

### ISSUE THREAD

**Issue by djdalfaro** [AllanWang/Frost-for-Facebook#1431]
**Description**
The groups tab is unreadable in AMOLED theme. It appears to work in default or light theme but not in dark, glass or AMOLED.

**Details (please provide at least the app version):**
 - App Version: 2.2.4
 - Device: Pixel 3
 - Android Version: 9
![Screenshot_20190530-072444](https://user-images.githubusercontent.com/34964237/58633047-f51fd280-82ac-11e9-961d-736cb347c392.png)

**Comment by AllanWang** [comment]
This was reported to me a few days ago and was fixed with d38ff35cfe1815e08fb2a807e36bf12f550373bb [(test build)](https://github.com/AllanWang/Frost-for-Facebook-APK-Builder/releases/tag/v2360).

You can use that build for now, or wait for a future release

**Comment by AllanWang** [comment]
Fix was in #1443
