### ISSUE TITLE
Spoof user agent from the beginning (aka. First login)

### ISSUE THREAD

**Issue by kowith337** [AllanWang/Frost-for-Facebook#1435]
**Describe the feature**

It seems like first time login will be use the device's default user agent, I'm expected that the app itself maybe randomise user agent from the beginning and vice versa if you want to make another account logins.

**Comment by AllanWang** [comment]
User agent mainly dictates the device you are logging in from. You can use the same one to log into other accounts. It seems to make sense to keep the original user agent for security reasons, or it will be confusing whether the login is actually yours. If you have a specific use case where user agent actually matters, you can let me know.

**Comment by kowith337** [comment]
Yep, I'm in doubt between two...
- Stay as it's own device user agent is easily to determine that an attempt to login is mean it really (or actually) you.
- Random or use the user agent that mostly use will be possible to prone your in the swarm of uniqueness (at least about device name and manufactures), but yes, it's make your concern that the device name isn't actually your own.
  - For example, forked Chromium browsers like [Bromite](https://bromite.org) and [Marmarduke](https://github.com/macchrome/droidchrome) are spoof user agent, depend on Android's version, e.g.
    - Moto G (Android 5)
    - OnePlus 6 (Android 9)

**Comment by AllanWang** [comment]
I'm not sure if it's really a privacy concern for me to expose your device model when logging in. There are far more sensitive info that one provides to Facebook when using their service.

My reasoning again is for users to be weary of what device each login is associated with.
If users get used to the same device logging in, an unwanted login would be harder to identify.

**Comment by kowith337** [comment]
Wait, are you in trouble with #1504?

**Comment by AllanWang** [comment]
I don't know about trouble. I don't think Frost is directly targeted, despite speculations, but I think Facebook just has some other checks towards post requests now. That PR technically does fix this issue as the user agent is always a desktop one, but I will still be looking towards adding configurations (#1357)
