### ISSUE TITLE
friend timeline

### ISSUE THREAD

**Issue by duergrim** [AllanWang/Frost-for-Facebook#1436]
Looking at a friends timeline, and looking at peoples birthday wishes, from their friends, I can't see if they posted pictures or videoes until I click on the timeline posts. It probably doesn't make sense what I just wrote, so I attacthed 2 pictures showing the bug
![Screenshot_20190606-214323__01__01__01](https://user-images.githubusercontent.com/44030905/59062203-91e20180-88a5-11e9-853f-76871f4b142c.jpg)
![Screenshot_20190606-214326__01__01](https://user-images.githubusercontent.com/44030905/59062210-95758880-88a5-11e9-9a89-67d6c02055cc.jpg)

**Comment by AllanWang** [comment]
If you can, maybe check touch.facebook.com from your browser to see if the same thing happens? I'm quite sure there's nothing I've done that would affect that, so unfortunately it looks like a Facebook UX problem

**Comment by AllanWang** [comment]
Closing unless verification says otherwise. I'm 99% sure this is how the mobile site looks

**Comment by duergrim** [comment]
Sorry for the late answer, yes the exact same problems appears on facebook.touch.com, so it's probably not the app having bugs. Thank you for your hard work, I opened another issue.
