### ISSUE TITLE
Constant crash on v2371

### ISSUE THREAD

**Issue by kowith337** [AllanWang/Frost-for-Facebook#1441]
**Describe the bug**
App constant crash

**To Reproduce**
1. Install Test build v2371
2. Make a first login, however, if you already logged in, you can skip
3. Once you've logged in for first time, you will got introduction setup, if not your first time, try simply launch app
   - And app will crash on this stage

**Details (please provide at least the app version):**
 - App Version: Test build v2371
 - Device: Motorola One Vision
 - Android Version: 9

**Logcat** (Notepad++ filtered search with package name)
- https://gist.github.com/kowith337/db4caf6301a2cf50035162336faafe15

**Comment by AllanWang** [comment]
As noted in the repo, builds from the `dev` branch are generally stable, as they should be tested. Even then, there is no guarantee that test builds work, as they are generated with every change. This branch is wip.

**Comment by kowith337** [comment]
I understand that it's still a testing, just noted here.

And I've forgot to tell that if I had downgrade to v2370, I didn't faced that crash.
