### ISSUE TITLE
Second line from link title text is cut off as font size is configured bigger

### ISSUE THREAD

**Issue by djpeinado** [AllanWang/Frost-for-Facebook#1448]
**Description**
As I configure font size bigger than 120% then second line from the link title text is progressively cut off, because text box remains same height.

**Details (please provide at least the app version):**
 - App Version: v2.2.4
 - Device: Xiaomi Redmi Note 5 Pro
 - Android Version: 9.0 PKQ1.180904.001 MIUI 10.3.1.0

![Screenshot_2019-06-17-19-16-18-997_com pitchedapps frost](https://user-images.githubusercontent.com/1162202/59624147-4bf32c00-9136-11e9-916a-98a0d428b7b1.png)

**Comment by AllanWang** [comment]
It becomes a bit difficult to fix changes like that since it's mess up layouts for other fonts. I'm not sure if there's a different way I can deal with font size changes or if this is just poor accessibility support on Facebook's end

**Comment by djpeinado** [comment]
I tried other apps with same result. I suppose it is a Facebook poor accessibility support. As a general rule it is a pain in the ass to set a font size bigger inside an application. Even google apps suffer this, because widget's layouts usually have fixed height.
If there is something you can do, it would be nice, otherwise I will continue reading with half sized letters ;-)

**Comment by AllanWang** [comment]
That makes sense. If Facebook supplied a good and open sdk, I would have used that, but since this is a web wrapper, I think this is the best I can do. If you want to play around, I think modifying height constants to min height or something might work. However, styling it may be pretty annoying, especially if there's no good css selector
