### ISSUE TITLE
Remove another stories tray inject

### ISSUE THREAD

**Issue by kowith337** [AllanWang/Frost-for-Facebook#1452]
**Describe the feature**
It seems like Facebook want users to watch other people's stories, by re-injecting stories panel.

Yeah, it seems like the one panel on the top isn't enough to make user engagement that feature!

![image](https://user-images.githubusercontent.com/16535467/59965164-a1637a80-9534-11e9-81e1-5e5d6ca41f7c.png)

**F12 Inspector**
![image](https://user-images.githubusercontent.com/16535467/59965238-7e859600-9535-11e9-80ca-923dc0ef369f.png)

**Comment by AllanWang** [comment]
I will take a look for the next release. If there's any other snippets, feel free to let me know. I will link a test build here once it's done, and you can see if it works. Website content may differ by locale

**Comment by AllanWang** [comment]
See https://github.com/AllanWang/Frost-for-Facebook-APK-Builder/releases/tag/v2391

Filtering may be a bit aggressive so you can let me know if other posts are missing. Otherwise I can filter just the tray easily, but you'd still have the "See fullscreen photos..." part there

**Comment by kowith337** [comment]
Confirm worked with latest build right now (2406)

**Comment by AllanWang** [comment]
Just tested some other things and it looks like it ends up hiding all non story related posts. I'm going to have to revert the aggressive styler
