### ISSUE TITLE
The last update is not available on FDroid, Why ?

### ISSUE THREAD

**Issue by mikhoul** [AllanWang/Frost-for-Facebook#1454]
The last update is not available on FDroid, Why ?

Regards :octocat:

**Comment by AllanWang** [comment]
You can see all the requests I've made to update Frost [here](https://gitlab.com/fdroid/fdroiddata/merge_requests?scope=all&utf8=%E2%9C%93&state=all&author_username=AllanWang)

After I submit it, it's no longer in my control as to when it gets merged, built, and released. I've sent another ping now, but if it no action occurs it's a bit out of my control.
