### ISSUE TITLE
F-droid stuck on 2.24

### ISSUE THREAD

**Issue by DanielValahul** [AllanWang/Frost-for-Facebook#1455]
Hello, 
As the title says, F-droid still has the 2.24 version. Is there a way to update Frost to 2.30 without uninstalling the apk from F-droid?

**Comment by AllanWang** [comment]
https://github.com/AllanWang/Frost-for-Facebook/issues/1454

Newest build has been approved, but probably still hasn't been approved yet. It basically isn't in my control when F-Droid updates, but you will get the update when it does.

I am personally working on a github client now that may help produce auto updates through github exclusively, where I have full control
