### ISSUE TITLE
Messenger Redirect still persists

### ISSUE THREAD

**Issue by 3drinks** [AllanWang/Frost-for-Facebook#1469]
**Describe the bug**
Update feature suggests messenger redirect was dealt with but it's not completely gone.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open messeages
2. See messenger redirect sometimes

Additionally, can't view images in messages. 

**Details (please provide at least the app version):**
 - App Version: 2.3.0
 - Device: s8+
 - Android Version: pie

**Comment by AllanWang** [comment]
Are you using the F-Droid version? All the js stuff doesn't work in that build so either try the github one or wait for 2.3.1. If the issue persists on a different build, you can let me know
