### ISSUE TITLE
Crash if "Get Frost Pro" is selected without Play Store installed

### ISSUE THREAD

**Issue by yaomtc** [AllanWang/Frost-for-Facebook#147]
Using LineageOS without Google apps.

**Comment by AllanWang** [comment]
It seems like you are using 1.4.1 please consider updating to a newer variant as the billing has been changed. Look at the Travis logs to see which builds are the stable ones

**Comment by yaomtc** [comment]
I'm using 4.1.1-test. What version should I get? The only more recent versions I can see are a beta 1.4.2 and a beta 1.5, which are... 410 and 411 respectively? But when I install #411 it ends up still saying 1.4.1.1-test in the About section. I guess I don't understand this versioning system.

**Comment by AllanWang** [comment]
@yaomtc Oops you're right. I've gone through quite a few changes within the last week to finalize my structure. I'll update the docs on how to get the latest non play store release when it's ready.

I'll take another look at the log as the bug may be related to the new library and not my old implementation. Is your current build still usable without clicking that?

Sorry for the inconvenience.

**Comment by yaomtc** [comment]
Yeah, I don't see any other problems. It's all good. Had a feeling it wouldn't work, since like 99% of apps use Google Play for any transactions.

**Comment by AllanWang** [comment]
Yeah sorry about that. It's harder to keep track of purchases ourselves as information isn't retained across fresh downloads or new devices. GPlay is the easiest for me.

Luckily most of the core features are free.

**Comment by yaomtc** [comment]
Yeah, that makes sense. Some app listings on F-Droid include links to
donate through PayPal or BitCoin, maybe when you get on there I could
donate that way.

**Comment by AllanWang** [comment]
@yaomtc are those apps capable of maintaining your pro status after you switch phones or after you uninstall the app? There still needs to be a way to tie it to an account, and that will take a bit more looking into

**Comment by yaomtc** [comment]
Oh I just meant for donation, not for pro features. Not sure of a FOSS friendly alternative method, but there is the Amazon app store for people who just want to avoid Google, at least.
