### ISSUE TITLE
Missing Facebook Dating

### ISSUE THREAD

**Issue by KyleSanderson** [AllanWang/Frost-for-Facebook#1472]
**Describe the feature**

FB Dating shipped a while ago. I've installed the Official FB app to use it but absolutely hate the battery drain on it.

**Comment by AllanWang** [comment]
Do you see it on touch.facebook.com? Not all features are a part of the web version. If you do see if, you can send me the base url, but note that some urls redirect to the newsfeed when opened in a new tab

**Comment by KyleSanderson** [comment]
Ah damn. Looks like it's app-only so far. Mind if we keep this open for when they expand it out?

**Comment by AllanWang** [comment]
I'd rather have this closed and reopened/reported if the feature comes out.
Facebook doesn't tend to update their mobile web page much, so it isn't something that will definitely happen
