### ISSUE TITLE
Update 2.3.0 breaks dark themes

### ISSUE THREAD

**Issue by fluffynuts** [AllanWang/Frost-for-Facebook#1473]
Just saw the update on F-Droid today and got it. After loading the app, Facebook page backgrounds are white. I tried toggling the theme to default and back to dark. I tried closing and reopening the app. Settings pages are fine - it's the site itself which isn't correct.

Downgrading to 2.2.4 gets dark themes back.

**Comment by AllanWang** [comment]
Duplicate of https://github.com/AllanWang/Frost-for-Facebook/issues/1463

TL;DR wait for 2.3.1 on F-Droid or stay on 2.2.4

**Comment by fluffynuts** [comment]
Apologies. I did scan the open issue list, but didn't spot another similar issue.

**Comment by AllanWang** [comment]
It's fine. I've had about 20+ emails anyways
