### ISSUE TITLE
More intervals for Notification sync

### ISSUE THREAD

**Issue by SOI7** [AllanWang/Frost-for-Facebook#1475]
Right now the minimum interval for notification checks is 15 mins, could you implement also 10 and 5 minutes? I know they're more battery consuming, but that's up to the user

**Comment by AllanWang** [comment]
No, because the service I'm using requires the minimum interval be 15 minutes. Anything shorter requires either a hack or a long term background process, which will then be more limited as Android updates. Official apps do not use polling, so they are able to produce instant notifications.

**Comment by AllanWang** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=421921
