### ISSUE TITLE
Download video 

### ISSUE THREAD

**Issue by darktweek** [AllanWang/Frost-for-Facebook#1479]
A way to download video can be a good feature. 

Thanks for the app.

**Comment by AllanWang** [comment]
You can do so with PIP. Disable autoplay, click the video, and it'll pop up with download options. Make sure you aren't using F-Droid 2.3.0

**Comment by darktweek** [comment]
I have the 2.3.1 and not work.

**Comment by AllanWang** [comment]
Can you elaborate? Does the download button not do anything?

**Comment by darktweek** [comment]
Update, it's works but not with all vidéos.

**Comment by darktweek** [comment]
Somes vidéos don't have the fullscreen button []. This kind of videos can't be download. 
Other have the [] button, can play in pip and download.
