### ISSUE TITLE
CookiesDb.kt line 71

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#148]
#### in com.pitchedapps.frost.dbflow.c$a.a

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost.test/issues/598e0621be077a4dccf4072c?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost.test/issues/598e0621be077a4dccf4072c?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
See #149
