### ISSUE TITLE
Dark mode.

### ISSUE THREAD

**Issue by userkilled** [AllanWang/Frost-for-Facebook#1480]
**Description**
Dark mode in group '···'

**Details (please provide at least the app version):**
 - App Version: 3.2.1
![Screenshot_20190708-123344](https://user-images.githubusercontent.com/39238592/60800203-7c4e4900-a17d-11e9-8108-ff44121ccc28.png)

 - Android Version: 7.0

**Comment by AllanWang** [comment]
Is this version 2.3.1? There is no 3.2.1

**Comment by userkilled** [comment]
I was wrong.😃

**Comment by AllanWang** [comment]
Might be fixed in #1490. If not in the future updates, provide the html source
