### ISSUE TITLE
Some areas of my pages are not themed

### ISSUE THREAD

**Issue by SOI7** [AllanWang/Frost-for-Facebook#1481]
As you can see from the screenshots below, the Status updater and the Community cards of a page I manage are not themed in Dark and Transparent themes. The version I'm running is 2.3.1. Doesn't seem to affect pages I don't manage 

![Screenshot_2019-07-09-01-21-10-067_com pitchedapps frost](https://user-images.githubusercontent.com/50930970/60848864-a0933f80-a1e8-11e9-9adf-c41f152576cb.png)
![Screenshot_2019-07-09-01-21-39-534_com pitchedapps frost](https://user-images.githubusercontent.com/50930970/60848865-a12bd600-a1e8-11e9-9175-01a00427b63c.png)

**Comment by AllanWang** [comment]
Thanks. I'll see if I can replicate it on a page I manage. If not, I may need you to send me the html source
