### ISSUE TITLE
Comments sometimes not visible

### ISSUE THREAD

**Issue by P4VL0** [AllanWang/Frost-for-Facebook#1482]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Just scrolling facebook
2. random issue - after entering to commands section, it's not visible (see screenshot)

**Details (please provide at least the app version):**
 - App Version: V2.3.1
 - Device:  OnePlus 6T
 - Android Version: Pie, OxygenOS 9.0.15/14

![Screenshot_20190709-165511](https://user-images.githubusercontent.com/52710522/60899663-1cce6700-a26b-11e9-9dbd-ae259b1516dc.jpg)

**Comment by AllanWang** [comment]
Can you produce the issue on `touch.facebook.com`? The only possibility I think is that I'm pausing web timers when you exit main activities, but otherwise it might be facebook's problem

**Comment by P4VL0** [comment]
What do you mean? What should I do? Where is the mistake and how to fix it?

**Comment by AllanWang** [comment]
If you go on `touch.facebook.com` on your mobile browser and check a few pages, do you also experiences missing comments as frequently in Frost? If yes, then that is a Facebook bug that I won't be able to fix

**Comment by OscarBarrett** [comment]
Just noticed this on a post and can confirm in my case at least they aren't visible on touch.facebook.com either, so it looks like it's Facebook's issue.
