### ISSUE TITLE
How to disable/turn off this floating button?

### ISSUE THREAD

**Issue by P4VL0** [AllanWang/Frost-for-Facebook#1484]
Is there any chance to disable this? I think it is a bit laggy 😂 And with scrolling to down, it often must "finish animation" and then I can scroll with no problems.  Some mod? How to do that?

![Screenshot_20190711-193343__01](https://user-images.githubusercontent.com/52710522/61072668-0c0d2500-a414-11e9-8154-f27be464ead2.jpg)

**Comment by AllanWang** [comment]
You can't. I will consider adding the option to remove it since it isn't always stable and often does nothing for users
