### ISSUE TITLE
Auto-Refresh?

### ISSUE THREAD

**Issue by GiantWaffle** [AllanWang/Frost-for-Facebook#1488]
Hi,

Frost v2.3.1

LG V20 (H910) Nougat 7.0

I'm not sure if this is a Frost issue or not.  I just don't recall seeing it happen before switching to Frost.  Although I could just be getting old and my mind is going. <lol>

Question: Every so often, the feed refreshes all on its own and I'm back at the top again, usually right when I'm about to tap on something to check it out, or in the middle of reading something. Annoying, as it constantly happening.

Is that Facebook doing that? Or is that some sort of timer programmed into Frost that auto-refreshes it, because if it's Frost, while of course it should refresh when first opened, or when tapping the "Feed" tab, I would love to have an option to disable it from happening "automatically" like that.

Thanks!

**Comment by AllanWang** [comment]
It is done by Frost, but I believe there was a reason behind it. The feed either does refresh on its own too after x minutes, or some loading components stop working. I will make a build to disable it in the future (maybe soon, maybe in weeks), and you can see

**Comment by AllanWang** [comment]
Try this and let me know what happens https://github.com/AllanWang/Frost-for-Facebook-APK-Builder/releases/tag/v2466

**Comment by GiantWaffle** [comment]
Allan,

I did try it and thank you for providing it so quickly! :-)

Here are my comments:

1) Just FYI, it installs as a separate icon called "Frost Test".  So I uninstalled both so I wouldn't use the wrong one by accident, cleaned up and reinstalled only the Test Apk you linked above for testing.

2) Again just FYI, it still shows as v2.3.1 which I assumed meant you just didn't change what it displays in the code and it actually is v2.4.6.6  Not important to me.  Just an FYI so you're aware, that's all. :-)

3) I did not see an option to disable the auto-refresh, so I am assuming that you just removed the code that makes it do that, because I viewed my Feed and made it all the way to the end without it auto-refreshing, so it appears to be working, since I have not previously been able to do that. :-)

Thank You Very Much!

Dave

**Comment by AllanWang** [comment]
First 2 are expected for test builds. The point is to allow you to keep release builds while testing.

If the feed still works fine, then maybe I'll add the option to disable auto refresh. Let me know if there are other loading issues that come with it

**Comment by GiantWaffle** [comment]
Dear Allan,

There are two more items (#'s 4 & 5 below) that I have noticed:

1 & 2) Okay, thank you for explaining those to me.  Both make perfect sense.  I just didn't know if you were aware, but it seems you were actually way ahead of me. <lol>

3) It would definitely be awesome to have the option to "Disable Auto-Refresh"!  Yes, please, please add that!

4) It seems that there is text that I can no longer copy.  The text within a news article and such works fine for me.  But when I try to copy the text that people have typed in at the top (above the link when they were first posting it and which now appears at the top of their post), as well as text they type in as the entire post that has no article link (maybe they type out a joke and post it, etc.), when long-tapping it to try to highlight the portion I wish to copy (or all of it), it either won't do anything (won't highlight anything), or *sometimes* a context menu pops up, from which I can choose "Copy Text".  But then as soon as I tap that option, it immediately copies all of that text.  There is no ability to highlight only a portion of the text.

5) I am using the Default Theme that Frost sets up when it's first installed.  Maybe it's the Standard Facebook Theme???  When highlighting text in an article that can be copied, both the highlight over the text and the little tabs that appear after you long-tap on text, that you then drag to select the exact text that you want to copy, are like see-thru, or white, or something.  I.e., you cannot see the highlight over the text, nor the little tabs, so you end up guessing at exactly where they are, based on what you believe you highlighted.  If making it/them black would be a problem for people using a Dark Theme, then please make them blue, or to be even more visible, red (but still seeing the text, of course).  Maybe light or dark highlight/tabs can be automatically chosen depending on which theme you choose, to make them visible no matter what?

Thank You Again, Allan!  Your support has been awesome!  I wish all Developers were like you (to be fair, some are)!  I will check my records to see if I Donated yet.  If not I will.  And if I did, I will do it again! <lol>

Thanks!

Dave

**Comment by AllanWang** [comment]
Please make new issues for unrelated topics.

Default theme = no css change at all. Everything is what you'd see from a browser.

I do not accept donations for this project. I use this app myself, so I'm happy with putting effort to maintain this. It's also nice to make this public so others can benefit too.
