### ISSUE TITLE
CookiesDb.kt line 71

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#149]
#### in com.pitchedapps.frost.dbflow.CookiesDbKt$fetchUsername$1.accept

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost.test/issues/598e0671be077a4dccf40a88?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost.test/issues/598e0671be077a4dccf40a88?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Called network checker on the main thread
