### ISSUE TITLE
Can't See Highlight or Little Tabs

### ISSUE THREAD

**Issue by GiantWaffle** [AllanWang/Frost-for-Facebook#1492]
Frost Release Test v2.4.6.6

LG V20 (H910A)
Android Nougat 7.0

I am using the Default Theme that Frost sets up when it's first installed. Maybe it's the Standard Facebook Theme??? When highlighting text in an article that can be copied, both the highlight over the text and the little tabs that appear after you long-tap on text, that you then drag to select the exact text that you want to copy, are like see-thru, or white, or something. I.e., you cannot see the highlight over the text, nor the little tabs, so you end up guessing at exactly where they are, based on what you believe you highlighted.

If making it/them black would be a problem for people using a Dark Theme, then maybe blue, or to be even more visible, red (but still seeing the text, of course)?  Maybe light or dark highlight/tabs can be automatically chosen depending on which theme you choose, to make them visible no matter what?  Just my guesses at what might work. :-)

Thank You!

**Comment by AllanWang** [comment]
Screenshot? Seems visible for me. This may also be OS specific rather than app specific, but the app theme is set according to the respective Frost theme
