### ISSUE TITLE
New Post/Like opens Other/That Post

### ISSUE THREAD

**Issue by GiantWaffle** [AllanWang/Frost-for-Facebook#1493]
Frost Release Test v2.4.6.6

LG V20 (H910A)
Android Nougat 7.0

When you create a new post, whether it's just some text you type, or uploading a picture or video, when it's finished, it does post, but it also immediately opens the post that was at the top of the feed, directly below where you tap to start creating a new post.

It also sometimes does this when you long-tap on the "Like" button to bring up the choices of "Like", "Love", "Funny", etc..  But it'll go into *that* post instead of the one below it.

Thank You!

**Comment by AllanWang** [comment]
I'm almost certain this is a Facebook web bug, since I don't modify the action of post buttons.

Can you see if you can replicate this error from your mobile browser? (touch.facebook.com)

**Comment by GiantWaffle** [comment]
Allan,

Sorry for the delay.  I tried it 3 times using the mobile web site, but the problem did not occur, so I don't know what to say.  I believe you on what you said, get it only happens in the app, so I'm stumped. :-)

Thanks,

Dave
