### ISSUE TITLE
Filter Facebook Link IDs

### ISSUE THREAD

**Issue by fabmazz** [AllanWang/Frost-for-Facebook#1495]
When opening a link to a webpage, it would be really great to be able to "clean" the URL from all the tracking parameters of Facebook (for example, the link ID, which is a very long string) which are put in the address (for example, "fbclid=......").
This would enhance one's privacy, as the websites tracking is removed.
Could this be implemented in the app? By, say, also putting an option in the menu for this?

**Comment by AllanWang** [comment]
Where are you seeing the fbclid? It's supposed to already be filtered out when you share it or leave Frost

**Comment by kowith337** [comment]
Probably any external URLs that posted on Facebook, even...
- `m.me` (Shorten URLs of MESSenger, appear often in pages chat button)

As my reproduce process, I have installed [NetScope](https://f-droid.org/packages/com.oF2pks.netscope) for expose URL before open in other apps, here's the result.
![image](https://user-images.githubusercontent.com/16535467/62413762-d804d880-b63c-11e9-87f2-2a9b2bc21d1c.png)

**Comment by AllanWang** [comment]
In this case, where did you click?

**Comment by kowith337** [comment]
At name and/or description of external link body.
