### ISSUE TITLE
Add option to set homepage tab

### ISSUE THREAD

**Issue by PaperMountainStudio** [AllanWang/Frost-for-Facebook#1498]
I would like to set my homepage (the page that opens when app starts) to messages instead of the default - news feed. I think it would be a nice improvement.
Thanks.

**Comment by AllanWang** [comment]
You can change the main tabs through settings. The one on the very left will be the one that opens by default, so you can reorder them.

**Comment by PaperMountainStudio** [comment]
Oh. OK, sorry.
