### ISSUE TITLE
Shorten extremely long share URLs

### ISSUE THREAD

**Issue by hejops** [AllanWang/Frost-for-Facebook#1506]
Currently, URLs generated for sharing are extremely long. Usually only the first few "elements" of the URL are necessary.

For example,

https://m.facebook.com/theghettogeppetto/photos/a.697397840424194/1370155349815103/?type=3&source=48&_ft_=qid.6722114752186769482:mf_story_key.7247529533689534602:top_level_post_id.398236880803627:page_id.227739844519999:src.22:photo_id.1370155349815103:story_location.5:attached_story_attachment_style.photo:view_time.1565107623:page_insights.{"227739844519999":{"page_id":227739844519999,"actor_id":227739844519999,"dm":{"isShare":1,"originalPostOwnerID":1370155393148432},"psn":"EntInternalObjectAggregatedStory","post_context":{"object_fbtype":266,"story_name":"EntInternalObjectAggregatedStory","story_fbid":[398236880803627],"publish_time":null},"role":1,"sl":5,"targets":[{"actor_id":227739844519999,"page_id":227739844519999,"post_id":398236880803627,"role":1,"share_id":1370155393148432}]},"686593728171272":{"page_id":686593728171272,"actor_id":227739844519999,"dm":{"isShare":0,"originalPostOwnerID":0},"psn":"EntInternalObjectAggregatedStory","role":1,"sl":5,"sub_story":{"page_id":686593728171272,"actor_id":1309433642437664,"attached_story":{"page_id":686593728171272,"actor_id":686593728171272,"dm":{"isShare":0,"originalPostOwnerID":0},"psn":"EntStatusCreationStory","post_context":{"object_fbtype":266,"publish_time":1564959833,"story_name":"EntStatusCreationStory","story_fbid":[1370155393148432]},"role":1,"sl":5},"dm":{"isShare":0,"originalPostOwnerID":0},"psn":"EntStatusCreationStory","role":1,"sl":5},"targets":[{"actor_id":227739844519999,"page_id":686593728171272,"post_id":1370155393148432,"role":1,"share_id":0}]},"1309433642437664":{"page_id":1309433642437664,"actor_id":227739844519999,"dm":{"isShare":0,"originalPostOwnerID":0},"psn":"EntInternalObjectAggregatedStory","role":1,"sl":5,"sub_story":{"page_id":1309433642437664,"actor_id":1309433642437664,"dm":{"isShare":1,"originalPostOwnerID":1370155393148432},"psn":"EntStatusCreationStory","post_context":{"object_fbtype":266,"publish_time":1564960107,"story_name":"EntStatusCreationStory","story_fbid":[2342969405750744]},"role":1,"sl":5},"targets":[{"actor_id":227739844519999,"page_id":1309433642437664,"post_id":2342969405750744,"role":1,"share_id":1370155393148432}]}}&__tn__=EHH-R

could instead be

https://m.facebook.com/theghettogeppetto/photos/a.697397840424194/1370155349815103

I think this is a pretty common issue for third party FB apps, but fwiw [SlimSocial](https://github.com/rignaneseleo/SlimSocial-for-Facebook) manages to handle it pretty well.

Not a major issue by any means (I myself got hit by the "phishing" alert recently), but it's worth some attention, I hope.

**Comment by AllanWang** [comment]
URLs have been shortened a bit more for the upcoming build, but I can take a look at these params. I tend to prefer being conservative in case these arguments one day become necessary.

As for phishing, see #1504. Please file separate issues for independent topics in the future.

**Comment by AllanWang** [comment]
I'll remove the bulk of that query in the next update. SlimSocial is a lot more aggressive in how it removes queries, and doesn't actually check which one it removes. This will potentially break other sites, so I won't be following that pattern
