### ISSUE TITLE
Auto-reply to FB Messages

### ISSUE THREAD

**Issue by adamzea** [AllanWang/Frost-for-Facebook#1507]
I love that Frost is able to show and reply to Facebook messages without installing the Facebook messenger app!  I've been trying to phase-out using FB messages completely by telling everyone who uses them with me to use my preferred more-private email method of communications if they want a faster response.
I would love an auto-reply option to be able to do that instantly so that I can ignore FB messenger completely.

**Comment by AllanWang** [comment]
I think this is a bit too niche for frost, and it will also be highly unstable. If you are going to depend on this to essentially avoid using messenger, you wouldn't know when it breaks
