### ISSUE TITLE
Phishing claims in v2.3.2

### ISSUE THREAD

**Issue by AllanWang** [AllanWang/Frost-for-Facebook#1522]
Test Builds

* [v2551](https://github.com/AllanWang/Frost-for-Facebook-APK-Builder/releases/tag/v2551); see #1532
* [v2559](https://github.com/AllanWang/Frost-for-Facebook-APK-Builder/releases/tag/v2559); see #1542 

---

Follows #1504, which introduces potential fixes.

If v2.3.2 doesn't work, please enable web only mode (under settings > experimental) first and see how that goes. Remember, you must log out and remove your device from Facebook before updating, as the log in agent matters.

**Comment by MallemIsmail** [comment]
I got locked out again in this version.

**Comment by AllanWang** [comment]
@MallemIsmail did you try web only? When was your last post activity prior to the lock? Did you recently update from 2.3.1 or was it a while back, and did you log in through 2.3.2? More information is needed (for future posts too)

**Comment by MallemIsmail** [comment]
@AllanWang i didn't try the web only. yep i did recently update from 2.3.1, nope i didn't log into 2.3.2.

**Comment by nwrkbiz** [comment]
2.3.2 fixed the problem for me.

**Comment by GerRudi** [comment]
Got locked out using version 2.3.2. 
Haven't used the app before and also didn't know about the web only mode. 

Edit: didn't do anything special with the app. I had notifications enabled. Came from "Material for FB" and I didn't experience that problem there.

**Comment by timoleary** [comment]
Can confirm same happened to me. Upgraded from last public release on f-droid to 2.3.2. Worked fine for a while and received the phishing attempt message today. I've enabled web only mode and will continue to test.

**Comment by AllanWang** [comment]
How long is a while? Phishing attempts can take a few days to propagate, so can you be sure that it wasn't because of the old release? Did you also log out after the update?

**Comment by AllanWang** [comment]
> Got locked out using version 2.3.2.
> Haven't used the app before and also didn't know about the web only mode.
> 
> Edit: didn't do anything special with the app. I had notifications enabled. Came from "Material for FB" and I didn't experience that problem there.

This is a bit more concerning for me. I will probably remove web mode in the future and split it up to request service and parsing. Most apps do parse and so perhaps it is just request that is the issue.

There also haven't been any claims of failures with web only mode, so that's the silver lining

**Comment by mainmachine** [comment]
I also just got logged out again on 2.3.2 - was working well for at least a week where previously got logged out every other day... The real sting is having to go through the whole dance of authorizing, only to have to change my password and all the logistics that entails.

Haven't tried "web only" mode, but will do so next. I will report back after a week if successful or sooner if I encounter this issue still.

**Comment by SteveGdvs** [comment]
I was logged out too just 10 minutes ago.

I was having the same problem in the older version but when 2.3.2 came out I completely uninstalled Frost and reinstalled 2.3.2 from F-droid.

I only use Frost for the notifications and to open Facebook links that people sent me.
I never post or like from the app.
I wasn't using web only mode mode but I will try now.

The logout happened seconds after a friend of mine sent me a post to a FB page on Messenger and I clicked on it. 
The post opened on Frost and when I pressed back to respond Messenger said "Session Expired" and logged me out.

When i tried to login it was the same page about phishing.

**Comment by AllanWang** [comment]
@SteveGdvs To confirm, when you say messenger do you mean the official messenger app or the messages tab under Frost?

**Comment by SteveGdvs** [comment]
@AllanWang Yes the official messenger app.

**Comment by creativetrendsapps** [comment]
@AllanWang , how sure are you that this relates to user agent and it switching per accessing messages?  Curious if it's not something else. Maybe account switching? Something to do with how you're handling cookies maybe? For instance, I use the same exact user agent in Simple for everything, ("Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36") including messages.. it's a windows desktop user agent which seems to be fine for everyone. I just added account switching so I'm hoping that will be fine also (dealing with cookies and all). Let me know if you need help with anything, I'm willing to help try to solve this if needed.

**Comment by nwrkbiz** [comment]
Happened to me again after sending a friend request.

**Comment by AllanWang** [comment]
@creativetrendsapps User agents seem like it's at least a factor. I don't test much with account switching but I don't see how the server would be able to distinguish that, beyond having two devices for different accounts with one user agent.

**Comment by AllanWang** [comment]
@nwrkbiz do you click notifications? I'm pretty sure that is the other factor, and I'm going to make some time to disable some actions tomorrow

**Comment by LightWayUp** [comment]
I experienced frequent lock outs with v2.3.1 too. After updating to v2.3.2, I first logged in from a computer to clear all login sessions, then opened Frost and enabled web only mode right away.

With web only mode everything *seems* to be fine no matter what I do ( although there's no real reliable way to verify ), so after about a week I turned it off to have parsing and native notifications feature again.

All was fine until today, when I ~~get the courage and~~ *very intentionally* tried to reproduce the problem... Visit the Friends section and view a few profiles, and then visit the Messages ( Messenger ) section to view messages. Within hours, I got locked out again - on v2.3.2 without web only mode. Seems like native notifications is only one of the factors ( if it is ) that triggers the phishing warning.

**Comment by AllanWang** [comment]
From what other third party apps provide, I do believe it's the service I use to mark posts as read, which is pretty hacky. Parsing shouldn't be a problem, so I'll just add a toggle for that aspect. It will be annoying now that notification viewing isn't synced, but until I find a better way it beats getting locked out.

Did you end up clicking notifications with web only disabled? I have not found general viewing to be the cause of any bans

**Comment by nwrkbiz** [comment]
@allanwang
I am pretty sure, that i did not click the notifications. I usually swipe them away and then open the app normally.

But I have disabled notifications for now. Will do some testing again and report back.

I am pretty sure the last ban was due to the friend request I sent. I did nothing else than lurking.

I should point out that I have fingerprint protection enabled.

**Comment by AllanWang** [comment]
What I mean is if you use the notification page at all. Even for the main activity, with web only disabled it's a native UI, so it requires a service to mark items as read. If it really was just the friend request action then there isn't much I can do. I don't customize that part. Bans aren't immediate so it may appear that something else is the reason. I got my ban from adding users to a group, but I don't think that's the problem

**Comment by K4rBie** [comment]
2.3.2, got locked out for no apparent reason. I only read and post on Messenger. Although, unfortunately, I cannot tell for sure that I haven't clicked anything else by mistake.

**Comment by AllanWang** [comment]
@K4rBie did you click a notification at all? Be it from the notification panel, or from the main activity with web only disabled

**Comment by AllanWang** [comment]
For testing, there is now [test v2551](https://github.com/AllanWang/Frost-for-Facebook-APK-Builder/releases/tag/v2551). Just install it and use as is, as the defaults should disable the features in question. See #1532 for more details

**Comment by K4rBie** [comment]
@AllanWang No haven't enabled web only But I clicked a notification whenever it showed up and I use Frost for a few months, maybe more.
I will test it tomorrow, I probably won't be able to recover the account (Facebook requires my ID card, f** off; and I don't blame Frost, I've already heard about this issue, have read this bug report, and I took my chances).
FB says it's temporary: do they mean it is reversible, or will they drop it after some time? I will most likely start a new account either way

and.. I haven't read the bugreport from start to bottom, I will do that, and then I will be more helpfull. I just rushed here to post, sorry

**Comment by adolfintel** [comment]
I got locked out for the first time in weeks today. They're asking me to send a picture of my ID. That's not gonna happen.

**Comment by AllanWang** [comment]
When I have time I'll look into removing all the request based actions. Other third party apps have similar features, but given that I worked on them with a mobile agent, it may have been harder than necessary. Desktop content is usually less js based which is nicer for parsing

**Comment by thatsatoffee** [comment]
Does anyone know whether Facebook will unlock accounts that were locked because of this issue after some time? I'm not comfortable with sending them a picture of my ID.

**Comment by K4rBie** [comment]
@thatsatoffee Mine got unlocked after 24 hours

**Comment by AllanWang** [comment]
With the next release (v2.4.0), I believe the phishing issue should be fully addressed. I'll allow comments on this issue for 2.3.2 related problems, but if it still happens, I'll open another one
