### ISSUE TITLE
Refresh Contiues At Most Inopportune Times

### ISSUE THREAD

**Issue by puppykickr** [AllanWang/Frost-for-Facebook#1528]
- [ ] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**

The refresh 'feature' is such a nuisance as it is active while editing a text post.

**To Reproduce**
Steps to reproduce the behaviour:
1. Copy some text to the clipboard
2. Go to '...'
Frost app
3. Click on '....'
'what's on your mind'
4. Longpress, and select 'Paste'.
5. Attempt to scroll through text
6. Irritating refresh 'feature' activates unwantedly, completely deleting post.

**Details (please provide at least the app version):**
 - App Version:  2.3.2
 - Device:   ZTE558VL
 - Android Version:   7.1.1

**Comment by AllanWang** [comment]
There are scripts to disable the refresh option when a textfield is focused. Either pasting does not trigger a focus, or you've clicked elsewhere to remove the focus. I may add something to specifically disable refresh for the whats new page, or if I can detect scrolling in a text view

**Comment by alekksander** [comment]
to trick and bypass this script select to share post as message and as far as it works fine when entering text as comment for the shared link (btw the text is never sent, but is it an issue with frost? i'd think it's up to them) this script doesn't trigger when entering recipients name.
