### ISSUE TITLE
Desktop View Is Coming Up When Sharing From Other Apps

### ISSUE THREAD

**Issue by puppykickr** [AllanWang/Frost-for-Facebook#1529]
- [ ] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**

When sharing photos, memes, sites, etc. from other apps, the page is displayed in desktop view.

**To Reproduce**
Steps to reproduce the behaviour:
desired content
share
3. Click on Frost icon in share selection page
4. Frost opens, to display in a large screen format.

This causes the user to need to scroll to the bottom rightto find the 'Post To Facebook' button.

Previous versions also had this issue, although some versions did display in the mobile portrait mode.

This should be decided by the user setting on the device, as to mobile or landscape display.

**Details (please provide at least the app version):**
 - App Version:  2.3.2
 - Device:   ZTE558VL
 - Android Version:   7.1.1

**Comment by AllanWang** [comment]
After #1505, the user agent is forced as desktop. That might change after #1357, but that's far down the road
