### ISSUE TITLE
Add history

### ISSUE THREAD

**Issue by smnthermes** [AllanWang/Frost-for-Facebook#1538]
A history feature, like the one of a web browser

**Comment by AllanWang** [comment]
This adds quite a lot of overhead, so it's a bit unlikely for me to add this. If you want to view your activity log, facebook already provides that. Same with saved posts. If you want your full history, most of it will be spent in bookmarked urls (like feed, messages, events), and it doesn't really make sense to keep track of those

**Comment by smnthermes** [comment]
@AllanWang activity log doesn't show viewed posts. And also, I don't always remember to save posts.

**Comment by AllanWang** [comment]
The implementation and performance overhead is still there. Even if I do log all posts for you to see, you'll have a lot to search through to view a post. In that case, the easiest way to keep track is to interact with it so it's in your activity log or to save it. If you just want a search function, you can already do so in Facebook. Me keeping a list won't help much more
