### ISSUE TITLE
Support for "Facebook Dating" feature

### ISSUE THREAD

**Issue by 3drinks** [AllanWang/Frost-for-Facebook#1540]
Facebook recently rolled out their dating service. This seems linked with their native app as I don't have it on my PC or mobile site. Are there any plans for that implementation via Frost? Or is that exclusive to their service?

**Comment by AllanWang** [comment]
If you can find the related mobile link (touch.facebook.com), you can post it here. But otherwise I don't think they support it here

**Comment by 3drinks** [comment]
It doesn't appear to be supported. Only in their native app...

**Comment by AllanWang** [comment]
Then it unfortunately cannot be supported. Once they add it to their mobile sites I will consider
