### ISSUE TITLE
navigation bar icons remain white despite background color

### ISSUE THREAD

**Issue by alekksander** [AllanWang/Frost-for-Facebook#1543]
If theme is set as white navigation bar icons remain white too. desired behavior is to have black icons if background is set as bright one. frost 2.3.2, android 8.1

**Comment by AllanWang** [comment]
To confirm, are you using a custom theme or light mode? Nav icons may also be set by the system (depending on your OS), so I might not be able to change that. It's a problem among many devices

**Comment by alekksander** [comment]
if i apply white theme to other foss like qksms nav. bar is changing icons to black without any additional work. with frost i am using custom theme and as i said before it displays white on white.

**Comment by alekksander** [comment]
here is example of how it currently looks in Frost, and how it's supposed to be in my opinion (pic from qksms as an example)
F:
![Screenshot_20190920-095237](https://user-images.githubusercontent.com/3148302/65309772-0dce3400-db8d-11e9-8d70-4071a6b180f0.png)

Q:
![Screenshot_20190920-095428](https://user-images.githubusercontent.com/3148302/65309901-5ab20a80-db8d-11e9-8250-08e427111a32.png)

**Comment by AllanWang** [comment]
For that case specifically, note that the accent color should be visible against the foreground color, background color, and the icon color. I'll have to check the navigation bar on my own time

**Comment by alekksander** [comment]
yes, absolutely, but android nav bar and top system icons remain white no matter what. Thank You.

**Comment by AllanWang** [comment]
This is in the works, but keep in mind that light icons are a feature as of Android O only. Given that other apps have this, you will have it too, but in general, customizing the theme does not check that everything is visible. The icon and header colors should still be different

**Comment by alekksander** [comment]
one more issue. both aurora store and qksms (foss apps i use as white–themed) blend the top bar with its own headbars. this is minor, but it doesn't happen with frost. frost will adapt color, but still have top bar slightly greyed down against app header.

**Comment by AllanWang** [comment]
Please make new issues for separate problems. Gradients were a thing back in lollipop, and are no longer a standard. I currently don't intend on adding it.
