### ISSUE TITLE
please standardize swipe direction for video and pictures

### ISSUE THREAD

**Issue by alekksander** [AllanWang/Frost-for-Facebook#1544]
to get rid of pip video it's currently to swipe left or right, but to get rid of picture (on long press (btw thank You for that feature, even though it seems it's not fetching highest quality possible)) it's to swipe up or down. could we have unified gesture for that? it is confusing as is.

**Comment by AllanWang** [comment]
PIP currently has the old youtube style video, and I wasn't sure if I was going to add an option to swipe back up for full screen. Image view on the other hand may support albums eventually, where horizontal scrolling will be necessary. I can potentially add a swipe down to dismiss in PIP, but having swipe up too probably won't make sense given the current motion to go from collapsed to expanded
