### ISSUE TITLE
add message „seen” remover for facebook

### ISSUE THREAD

**Issue by alekksander** [AllanWang/Frost-for-Facebook#1545]
Would it be possible to integrate simple code like:

`||facebook.com/ajax/mercury/change_read_status.php$xmlhttprequest`

to remove „seen” from messeges? i know it's been impossible or not figured out in the past yet, but perhaps something changed in this matter. thank You

**Comment by AllanWang** [comment]
After phishing concerns, I've essentially removed all custom post requests (#1542). Even if this is possible, web features are likely to change, and this isn't one that you want to break unexpectedly.
