### ISSUE TITLE
[Check in] phishing suspicions

### ISSUE THREAD

**Issue by 3drinks** [AllanWang/Frost-for-Facebook#1548]
I don't have a bug report, just a check in for confirmation purposes.

I recently got the ultimate FB lock requiring photo ID submission, thanks to Frost. After clearing that up I uninstalled Frost completely, and then reinstalled Frost with web only enabled.

This has stopped the issue, though I also don't get push notifications anymore, as hypothesized. I wish there was a way to get notifications with this app without triggering the alert.

Anyway, I hope this confirmation helps you.

**Comment by AllanWang** [comment]
Web only disables notifications. Update to 2.4.0 and it'll be added back. No other changes necessary.
