### ISSUE TITLE
Switching to an account, removes that account

### ISSUE THREAD

**Issue by PanderMusubi** [AllanWang/Frost-for-Facebook#1549]
- [x] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
Switching to another accounts results in that account being removed from the app. This is for any way of switching (directly or via accounts).

**To Reproduce**
Steps to reproduce the behaviour:
1. Add two accounts 
2. Switch to the other account 
3. That account is removed.
4. Switch again to remaining acoount, that one gets removed too and you are left with initial login screen.

**Details (please provide at least the app version):**
 - App Version: 2.3.2.2030200
 - Device: OnePlus 5T
 - Android Version: LineageOS 16, Android 9

**Comment by AllanWang** [comment]
Cannot replicate. Please update to 2.4.0 and try again. Facebook login does seem to fail from time to time for no reason

**Comment by PanderMusubi** [comment]
Same problem with 2.4.0, unfortunately. Can reproduce it each time, not occasionally. Any other ways to report this? Do you need a log file?

**Comment by AllanWang** [comment]
Log could help. You could also try reinstalling the app. Sometimes there
are random login issues

**Comment by PanderMusubi** [comment]
Any particular way to create a log? Does the app have a log uploading feature (request)? ;-) If not, what is the preferred way for capturing and sending a log for this?

**Comment by AllanWang** [comment]
Frost uses standard logging, so any way of viewing logs will do (third party app, adb, etc). You can filter logs to show Frost only before sending, and watch out for sensitive information from other apps.

**Comment by PanderMusubi** [comment]
Miraculously, it is working now. Did not do a reinstall or anything.

**Comment by PanderMusubi** [comment]
Still happens sometimes, but not every time as before.
