### ISSUE TITLE
Convert desktop url to mobile

### ISSUE THREAD

**Issue by gradinaruvasile** [AllanWang/Frost-for-Facebook#1556]
It would be nice to convert desktop Facebook URLs to mobile ones when opening Frost from links from other apps.
Currently desktop URLs are opened as is so the pages are large and need panning.

**Comment by AllanWang** [comment]
Any specific example?

**Comment by gradinaruvasile** [comment]
Random example (from Reddit Slide app):

https://www.facebook.com/events/2437476539807977/

**Comment by AllanWang** [comment]
Okay. Frost needs to use a desktop user agent so all url conversions will have to be manual. I'd have to check and see if urls will be converted if we simply convert facebook to m.facebook, but I don't think it's that easy

**Comment by AllanWang** [comment]
As a quick update, it appears that converting from www.facebook to m.facebook works in most cases. For non facebook urls, we can bring back the mobile agent and have it switch, since they don't have a problem.
