### ISSUE TITLE
No Emoji like FB

### ISSUE THREAD

**Issue by sputnick-dev** [AllanWang/Frost-for-Facebook#1570]
The bug occur in my mobile browser too

**The bug**
The emojis are not the same as the FB ones, like the simple smileys

**To Reproduce**
Steps to reproduce the behaviour:
Just try to type a text in a message with an emoji by touching the emoji icon, emojis are not the same like facebook :

![](https://i.imgur.com/ZXXgeUG.png)

**Details (please provide at least the app version):**
 - App Version: 2.4.0
 - Device: SM-A520F
 - Android Version: LineageOS 16

**Comment by AllanWang** [comment]
The emojis themselves are out of my control. These are provided by facebook's mobile message page

**Comment by sputnick-dev** [comment]
FB can break UX because we don't use the FB app, but maybe Frost can fix this kind of issues to be more relevant than just a web page. My 2 cents

**Comment by AllanWang** [comment]
There is no api for emojis so it isn't possible. I'm also no longer considering hacky workarounds for post requests, given recent phishing accusations (#1504, #1522)
