### ISSUE TITLE
Can't see comments from notifications or by touching comments link

### ISSUE THREAD

**Issue by sputnick-dev** [AllanWang/Frost-for-Facebook#1571]
The bug occur in my mobile browser too

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to notifications (Earth)
2. Touch on a notification saying someones commented something
3. Now you are not in the comments but in the list of the people liked your post

Another way:
1. Go to your post
2. try to unfold comments by clicking the comments link : ![](https://i.imgur.com/w5CyF7Y.png)
3. Now you are not in the comments but in the list of the people liked your post

(tested in horizontal or vertical device position)

**Details (please provide at least the app version):**
 - App Version: 2.4.0
 - Device: SM-A520F
 - Android Version: LineageOS 16

**Comment by AllanWang** [comment]
Cannot personally replicate this, but the like description is quite long and they have small touch boxes. Perhaps you can try clicking a bit lower.

As a general note, if the same problem happens on your browser, then chances are it is a web issue vs an issue in Frost.

**Comment by sputnick-dev** [comment]
FB can break UX because we don't use the FB app, but maybe Frost can fix this kind of issues to be more relevant than just a web page. My 2 cents

**Comment by AllanWang** [comment]
In this case, I'm pretty sure it's just smaller hit boxes, and french taking up its own row (poor design on Facebook's part perhaps). If you click lower you will probably open comments.
