### ISSUE TITLE
[FR] Add Workplace by Facebook

### ISSUE THREAD

**Issue by fazlerabbi37** [AllanWang/Frost-for-Facebook#1574]
[Workplace by Facebook](https://www.facebook.com/workplace) is a social network for individual organization. As many organization including my usages it. I would love to use it with Frost.

**Comment by AllanWang** [comment]
It seems like workspace is essentially a completely new platform (like messenger). It would be a lot of effort to theme and maintain it, and I also can't verify any non free feature, so this won't be feasible.
