### ISSUE TITLE
(Question) Possibility Of A Separate Messenger App?

### ISSUE THREAD

**Issue by puppykickr** [AllanWang/Frost-for-Facebook#1575]
Due to the difficulties involved with trying to use Frost on my mobile, I find that is is often (always) quicker and easier to just use a browser.

I have discovered that the only things I really use Frost for are to post things to Facebook from other apps (still slow and difficult) or for the built in Messenger service.

As it takes an inordinate amount of time for Frost to load up and start, it takes awhile before I can get to any messages.

Is it feasable to have a Messenger wrapper without the Facebook attachment?

Would this speed up/simplify either of the functions?

**Comment by AllanWang** [comment]
The load time isn't really affected by messenger. Each tab is already loaded lazily.

I also don't have the time to support any additional apps. I personally use the actual messenger client so it's already extra work to maintain what Frost has currently.
