### ISSUE TITLE
Support fb:// intents

### ISSUE THREAD

**Issue by fabmazz** [AllanWang/Frost-for-Facebook#1586]
While searching for profiles, when I click on one it uses a new address scheme: fb://profile/?id=...
This isn't recognized by the browser/app, therefore it is impossible to see the profile.

**Comment by ArjenR** [comment]
Experiencing the same, but notably when searching. The profiles in the presented search results have the URL`fb://profile/?id=<removednummericalid>&profile_type=person`
Which results in the error:
`net::ERR_UNKNOWN_URL_SCHEME`

**Comment by michel-slm** [comment]
![Screenshot_20191114-225141](https://user-images.githubusercontent.com/85603/68922878-afa77280-0731-11ea-9609-3f06a4920a35.png)

Screenshot of this happening. Interestingly opening a page works just fine, it's just profiles that break

**Comment by AllanWang** [comment]
Thanks for the heads up. I haven't had time to work on Frost recently, but once I do I'll take a look. Facebook may have changed a bunch of url handling, which will all need to be fixed.

**Comment by AllanWang** [comment]
Seems like events are changed too

**Comment by shatteringlass** [comment]
I had the same error with photos too.
Link:

`fb://photo/?id=10152125647484919&set=spms.10152125647484919.906023292747296.245351955601058.570342463003680.1869916382140.10202864602802852&showDismissalControlsImmediately=1`

**Comment by AllanWang** [comment]
Can I get some specific paths that lead to the intents? Either it isn't happening at my locale or it's been addressed by Facebook?

I tried clicking my profile, searching for users, and clicking events

**Comment by chrishickman81** [comment]
Photos/profiles/events work fine for me at present.

**Comment by AllanWang** [comment]
Is this still a bug then? Or just a temporary facebook experiment?

**Comment by AllanWang** [comment]
Got two reports that it is fixed. This was likely changes on Facebook's side, so I'm closing this for now
