### ISSUE TITLE
Facebook Dating?

### ISSUE THREAD

**Issue by GibberMeJenks** [AllanWang/Frost-for-Facebook#1589]
**Describe the feature**

Does Frost support the new Facebook Dating feature? I was not able to find it within the app and if possible to implement this would be great without having to use the official app!

Apologies in advance if this isn't the proper way to propose a feature.

**Comment by AllanWang** [comment]
It seems like a completely separate space (like facebook for business), and I won't be able to take on extra additions. Sorry
