### ISSUE TITLE
Unable to use app, asks for mobile number

### ISSUE THREAD

**Issue by rancidfrog** [AllanWang/Frost-for-Facebook#1596]
Recently app has been unusable with message to enter phone number.
So, I finally updated to latest version, but still unable to do anything without entering phone number:
![](https://i.imgur.com/mXXJqd0.png) 

Logout, and cannot login without number.

Did fb make changes to force phone numbers now?
that will render app useless, in my case at least.

**Comment by AllanWang** [comment]
That's a change on Facebook's end. I think it's been like that for a while now
