### ISSUE TITLE
Getting rid of FB trackers

### ISSUE THREAD

**Issue by b-r-o-t** [AllanWang/Frost-for-Facebook#1598]
When copying / opening a URL from Frost, the usual Facebook trackers are copied along (because they are part of the URL. It's everything after and including the question mark, which can be quite long nowadays).

Since Frost seems to care much about privacy, I would like to have the tracking part stripped off URLs.

Doing this manually, by copying the URL to clipboard, paste it to the address bar of a browser, then deleting the tracker portion is a real pain and consumes a load of time.

Hope you see it the same way.

**Comment by AllanWang** [comment]
Which queries specifically? I don't believe that all query params are
trackers in every situation, and there are cases where missing a query will
fall to load. If there are some reoccurring ones, I can blacklist them

**Comment by b-r-o-t** [comment]
You can easily spot these trackers, because they are either extraordinary long, of they start with ?fbclid= or ?h=

The vital portion of the URL is always located before the questionmark and is not harmed, when removing everything else after and including the "?".

Examples:

- https://exampleurl.domain/?h=AT3qW-oUqEPwq7thPFnv15uLsghCbrYZcdk0QQrBzUXY1CpyhiLcuOrdBBL7YXXEN9Vl9J8LFiI83psmtEZFipjCXSLQ_Lwix7W0HhuKBT0sJ55__rz1pZ5wZYTiQUgCTF12U04A7_hOsSA9ZKBG0k0fePBRe2J2bT_CFQ_Noh5Ms-QuHmh3YcBLnSX_oo73fGnBwPgir4aH1rQ1apxi3Btv1tUtk78G9aedpvxsXqimC8m4lQNZOjr3kKAIOyPr6BBrg771FZ_r1KN90ASeMMKKlY0MNaj96HtiXwab7h6K4eHYMQxEF82ldFPQHKxKa9rQJY7ZBjWqYxNqx8C_cfOapY4hgc0EPpI4VsN6a7_ghlitn-1eTaVZUt6WmBICe0jo6Yizq615OtuHNxjKYLyj5Jg6r7QUgfXZZPPR0_u4IHM_erPRqRDoJp0x1XIozYMJKTvPXADUrHgaWY_zaaSpwJZDWqCMu2XThvoA6a1HXpK1165qbv88nD8H0iG_K8gI1STVjhWHgTiH4Kj9qKZLa5ZXPwZNWF9glalYyQI7A1hsv4nTNJXBWXn65O9Vai5AdwdqERUM2bGOQuieRv_lDMsZSX_9pMO7srCZwEqoB0dSrxduOkw_alxGn1v4o1Lm
- https://exampleurl.domain?fbclid=IwAR0V0Z7LTkqRdTSV45LyC5nHDmEy9nYWWSBbQ3bp9Eq4R9YOZDuXcG-DpAE

BR,
B.

**Comment by AllanWang** [comment]
I'll have to look at that, since fbclid should already be removed. FYI, entries after ? mark queries, and it isn't true to say that l queries are trackers. Some are indeed required for certain websites to load

**Comment by AllanWang** [comment]
Blacklisted `h` in 03787c95cbdd71c6a3e3c0e4dc2ec13adaa79620. Urls are already formatted from copying and sharing links, so I'm not sure if this report is for an outdated version.
