### ISSUE TITLE
Fatal Exception: No virtual method setCornerRadius

### ISSUE THREAD

**Issue by syphyr** [AllanWang/Frost-for-Facebook#1599]
- [ x] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
Commit 15494d3b42315fa6fa7ae5daeb5ddf1f964b3932 causes the following fatal exception when starting the application on my T813 tablet with cm-14.1 (nougat).

12-23 20:37:10.617  7273  7273 D AndroidRuntime: Shutting down VM
12-23 20:37:10.619  7273  7273 E AndroidRuntime: FATAL EXCEPTION: main
12-23 20:37:10.619  7273  7273 E AndroidRuntime: Process: com.pitchedapps.frost, PID: 7273
12-23 20:37:10.619  7273  7273 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method setCornerRadius(F)V in class Lf/c/a/b/a0/k; or its super classes (declaration of 'f.c.a.b.a0.k' appears in /data/app/com.pitchedapps.frost-1/base.apk)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at com.mikepenz.materialdrawer.s.b.d(AbstractDrawerItem.kt:4)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at com.mikepenz.materialdrawer.s.c.a(BaseDescribeableDrawerItem.kt:10)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at com.mikepenz.materialdrawer.s.a.a(AbstractBadgeableDrawerItem.kt:5)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at com.mikepenz.materialdrawer.s.a.a(AbstractBadgeableDrawerItem.kt:1)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at com.mikepenz.fastadapter.x.g.a(OnBindViewHolderListenerImpl.kt:3)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at com.mikepenz.fastadapter.b.a(FastAdapter.kt:23)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$g.a(RecyclerView.java:15)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$v.a(RecyclerView.java:8)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$v.a(RecyclerView.java:73)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$v.b(RecyclerView.java:1)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$v.d(RecyclerView.java:11)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager$c.a(LinearLayoutManager.java:4)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.a(LinearLayoutManager.java:160)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.a(LinearLayoutManager.java:147)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.e(LinearLayoutManager.java:64)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:8)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:9)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:18)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:729)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:621)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
12-23 20:37:10.619  7273  7273 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**To Reproduce**
Steps to reproduce the behaviour:

**Details (please provide at least the app version):**
 - App Version: latest sources
 - Device: T813
 - Android Version: Nougat (cm-14.1)

**Comment by syphyr** [comment]
Reverting back to core-ktx 1.1.0 fixes the problem on Nougat.

**Comment by AllanWang** [comment]
This is a known issue. The material library changed, and it is a dependency on many other libraries. I've reverted some of the changes, but haven't had time to look at the rest; will get to it after Christmas. Thanks for looking into this!

**Comment by syphyr** [comment]
No problem. I added a pull request for a partial revert.  The rest works fine.

**Comment by AllanWang** [comment]
Closing as it is currently working in the dev branch. After future changes, all dependencies will end up at the latest version
