### ISSUE TITLE
Autoplay Settings: Page Not Found

### ISSUE THREAD

**Issue by syphyr** [AllanWang/Frost-for-Facebook#1612]
- [ X] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
"Settings-->Behaviour-->Autoplay Settings" shows "Page Not Found".

**To Reproduce**
Steps to reproduce the behaviour:
1.See above

**Details (please provide at least the app version):**
 - App Version: v2.4.2
 - Device: T813
 - Android Version: Nougat

**Comment by AllanWang** [comment]
Likely because the desktop agent does not support autoplay. If you've used another wrapper that has it, please let me know. I'd like to revert and support both mobile and desktop agents, but I'm not sure if it causes phishing problems. (See #1504, #1522)
