### ISSUE TITLE
remove exif on photo share/send

### ISSUE THREAD

**Issue by alekksander** [AllanWang/Frost-for-Facebook#1613]
would it be possible to automatically remove exif from pictures before sending them to fb servers (posting and sending in conversation)? there is external app for that (like scrambledexif), but would be great to have that in built in frost. facebook strips any exif for us anyway, so why to feed it with information by default?

**Comment by mmm4m5m** [comment]
There is similar application:
Scrambled Exif (Remove the metadata from your pictures before sharing them) - https://f-droid.org/app/com.jarsilio.android.scrambledeggsif

**Comment by AllanWang** [comment]
This seems out of scope for the project, and not directly related to Facebook. I imagine that apps like the ones mentioned, which are dedicated to the specific feature, will do a better job than I can. There's probably also other ways (and maybe other existing apps) that can already strip data on image creation, vs on image usage.
