### ISSUE TITLE
Can't Share

### ISSUE THREAD

**Issue by GiantWaffle** [AllanWang/Frost-for-Facebook#1614]
- [x] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
This issue actually started with v2.4.1 but I figured I'd just go back to v2.4.0 and wait for v2.4.2 which I did, but the same thing is now happening with v2.4.2 as well (so I'm back at v2.4.0 now, but will be happy to load v2.4.2 again to test).

Everything works fine, except for when I try to Share an article to Frost.  I have always used "SmartNews" and have never had a problem doing this until v2.4.1  The problem still exists even when trying to Share a page from my Web Browser to Frost though.

What happens is that the Frost screen, where you tell it to "Post" it (after share) pops up, but it doesn't show anything except a solid white background, with the blue Frost border, that says, "Frost Web", in the top blue border.

The thin little bar that would go across (right where the top of the white meets the the bottom of the top blue border) as it loads, looks like it's about 10% of the way done and it just stops there.  I let it sit there for a while, but it didn't do anything.

I did try performing a clean install.

I like the other changes in the app and would love to get v2.4.2 working! :-)

**To Reproduce**
Steps to reproduce the behaviour:

The steps are simple:
1) Open article (or whatever) in app or browser.
2) Choose "Share".
3) Chose "Frost".

**Details (please provide at least the app version):**
 - App Ver: Frost for Facebook v2.4.1 & v2.4.2
 - Device: LG V20 (H910A)
 - Android Version: Android Nougat 7.0

Thank You!

**Comment by AllanWang** [comment]
It's weird to me that the problem happened from 2.4.0 to 2.4.1, so I will have to find the diff and check it out in the future.

**Comment by GiantWaffle** [comment]
I would appreciate that.  I'd love to be able to update!

**Comment by Clickau** [comment]
Can confirm this. On 2.4.0 sharing works normally, but on 2.4.1 and 2.4.2, the sharing page stays like in the attached image.
![Screenshot_20200111-010658_Frost](https://user-images.githubusercontent.com/40263542/72192547-dd95f400-340e-11ea-9595-a7981a71960e.png)

**Comment by GiantWaffle** [comment]
Hi,

Just tried v2.4.3 and the problem still exists.

I'm not trying to be rude, but is this problem being worked on?  Will it be fixed by v2.4.4?

Frost changed, becoming a lot nicer with v2.4.1, eliminating UI issues that existed up to v2.4.0, but I can't update and am stuck using v2.4.0 because after that version I can't Share anything through Frost.

Thanks

**Comment by AllanWang** [comment]
I understand the frustration. In short, I used to spend hours on Frost a day, and now I spend a few hours per entire release. This build was a quick fix to get the search issue addressed as it was the most prominent bug (with an easy and known solution), and behind the scenes, I'm trying to get F-Droid auto updates back so they get closer to the github release cycle. I haven't really had time to look at the other issues yet.

Given the infrequent updates, I'm perfectly find with pings on lacking bugs per release, and if some get more pings, it helps me assess what is more important for the next releases.

I can't make any promises, but I will make an effort to try and fix this bug for the next build, which I hope will come next next week

**Comment by tcables** [comment]
Thanks for all your hard work!

Im running 2.4.3, and I see this issue

**Comment by AllanWang** [comment]
Fixed. Details are in the PR linked above. You can try a test build at

https://github.com/AllanWang/Frost-for-Facebook-APK-Builder/releases/tag/v2738

**Comment by AllanWang** [comment]
@GiantWaffle does this also mean you've been using old builds now with post related actions? Have you not been locked out? I do want to try adding back mobile + desktop user agent support, since it improves a lot of features, but that was one of the testing points for the phishing problems.

In the updated builds, the desktop sharing page will be used, which isn't as nice

**Comment by GiantWaffle** [comment]
> @GiantWaffle does this also mean you've been using old builds now with post related actions? Have you not been locked out? I do want to try adding back mobile + desktop user agent support, since it improves a lot of features, but that was one of the testing points for the phishing problems.
> 
> In the updated builds, the desktop sharing page will be used, which isn't as nice

I have been using v2.4.0 but want to go newer because I like its layout better.  It looks "Mobile" vs 2.4.0 which looks "Desktop".

Sorry it took so long to respond.  I will try the new "fixed" version and thank you! :-)
