### ISSUE TITLE
Can't switch profile (4 or more)

### ISSUE THREAD

**Issue by mmm4m5m** [AllanWang/Frost-for-Facebook#1615]
**Describe the bug**
In the right popup panel, on top, I see 3 profile pictures. When you have 4 or more profiles, then there is drop-doen menu. Also in the same menu is 'manage profiles'. 
This is not working with latest version. When I tap the drop-down button, nothing happens, nothing popup, no changes in the menu, I still see ONLY profile specific menu items like 'most recent', 'top stories', etc.

**Details (please provide at least the app version):**
Frost 2.4.2
Android 7.0
10'' tablet

**Comment by AllanWang** [comment]
To clarify, when clicking anywhere in the header, the dropdown arrow does not animate around? The drawer was completely rewritten, but items like logout, add account, and manage account are hardcoded and should remain there.

**Comment by mmm4m5m** [comment]
The drop-down arrow image does change - from "pointing right" to "pointing down". That is all. All my animations are OFF and was OFF since long time (months ago).
I "force-stoped" Frost and restarted. All I see is only 3 profile images on top and nothing else related to profiles.

**Comment by AllanWang** [comment]
I just tried with animation off, and it appears to work every other time.
Is that the same with you? I will look into a good in the near future

**Comment by mmm4m5m** [comment]
For me it never works. I tried with animations ON (different speed) - no change.
Side panel is always the same. Only the drop-down image change, that is all
(Point down or pointing up. Above I said "pointing right", but it is mistake)
I can give screenshot if needed.

**Comment by AllanWang** [comment]
I think I know what you are talking about. I might have to test with 4 or more accounts later (only tested with 2 accounts). If you want you can remove some accounts to test, but otherwise it's more convenient for me to try duplicating my accounts to get more

**Comment by mmm4m5m** [comment]
I think, I can not remove/add accounts. All these functions are in the hidden (not working) menu.

**Comment by AllanWang** [comment]
Did not test yet with 4+ accounts, but even with 1, it doesn't work exactly half the time for me, due to the height staying at the expected value on collapse

**Comment by AllanWang** [comment]
You can try testing with https://github.com/AllanWang/Frost-for-Facebook-APK-Builder/releases/tag/v2686, but otherwise just wait for the next update

**Comment by mmm4m5m** [comment]
Tested with Android 9 (5.5" phone), animations off:
Frost from FDroid (2.4.2) - accounts menu is shows every second time (as you said above).
Frost-test (v2686) - it works, thanks.

Later I will test with Android 7 and give feedback.

**Comment by mmm4m5m** [comment]
Tested with Android 7 (10" tablet), animations off:
Frost from FDroid (2.4.2) - accounts menu is never shows.
Frost-test (v2686) - it works, thanks!

**Comment by mmm4m5m** [comment]
I suspect another bug(s) with multiple accounts...

Here the basic idea(s) and a valid case:
1. from notifications open Frost Web, profile 2
2. open Frost, profile 1
3. switch back to Frost Web, profile 2 and click "Messages" button (top/right corner)
It will load messages/notifications from profile 1

Another use case but not confirmed:
1. from notifications open Frost Web, profile 1 - post with video
2. click to start the video, press "back" to see "floating video"
3. from notifications open Frost Web, profile 2 

I will appreciate any comments and directions from you. 
Like when and how accounts are switched? 
Shall I expect every window to remember "his" account? 
OR I shall expect that "last activity/action will override and define the current active profile for ALL windows"

Sorry for this off topic. If you like, I can move it to new issue.
