### ISSUE TITLE
Overlay Mode Off Causes Bad Formatting of Page

### ISSUE THREAD

**Issue by landry314** [AllanWang/Frost-for-Facebook#1617]
In the newest version of Frost v2.4.2, when I turn Enable Overlays off in Behavior then personal pages and group pages load incorrectly with horrible large images and cheap low res links.

**Comment by AllanWang** [comment]
Cannot replicate. Can you give me some steps to get there? I tried disabling overlays and clicking a group and a person's profile. Does this problem not happen when overlays are enabled? In general having overlays may cause more problems for dependent links, but the url loaded is the same for both

**Comment by landry314** [comment]
ok, so i have the problem most of the time now, independent of overlays. the problem is the pages after a search for a person's profile are loading in mbasic mode... or a search for a group too.

**Comment by landry314** [comment]
i don't know why playing with the overlay setting doesn't help anymore.

**Comment by AllanWang** [comment]
Duplicate of #1620

**Comment by landry314** [comment]
can we please have this update? every day i check...

**Comment by AllanWang** [comment]
I'm going to try to push an update today, but F-Droid will still take a couple of days before release. Github releases are the fastest since I build them myself, and there's also test builds which generate automatically with each commit, though only the dev branch outputs are relatively stable

**Comment by AllanWang** [comment]
If you're also checking here every day, consider watching for github releases or joining the slack channel. You will be pinged when there's a new release
