### ISSUE TITLE
2.4.2 - search result page - pictures too big

### ISSUE THREAD

**Issue by Genis-Sage** [AllanWang/Frost-for-Facebook#1620]
**Description**

-open search
- type in some letters
- click enter

the pictures on the result page are too big (wider than my screen)

the behaviour started with Frost 2.4.2
setting back Frost to Default settings (deleting date) did not help
downgrading to 2.4.1 solves the problem, so the cause is not a server-side change from FB

perhaps it's the root cause is similar to #1617 

**Details (please provide at least the app version):**
 - App Version: 2.4.2
 - Device: Nokia 7 Plus
 - Android Version: 9

**Comment by AllanWang** [comment]
Problem seems to be unrelated. I believe this is because I changed the search url to fix parsing, but forgot to change it back for loading the page
