### ISSUE TITLE
cant download images 

### ISSUE THREAD

**Issue by regulator-g** [AllanWang/Frost-for-Facebook#1629]
**Describe the bug**
I cannot download images in both news feed posts and messages

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to news feed 
2. Click on 'full size
3. Press download 

**Details (please provide at least the app version):**
 - App Version:242
 - Device: pixel 3 
 - Android Version: 10 
Frost via fdroid store
Frost has access to storage
Can successfully upload photos

![Screenshot_20200204-130437_1](https://user-images.githubusercontent.com/40394866/73713232-07adae00-4750-11ea-9505-f0864a999b6e.png)
![Screenshot_20200204-130446_1](https://user-images.githubusercontent.com/40394866/73713243-1005e900-4750-11ea-9edb-28eb846941ed.png)

**Comment by AllanWang** [comment]
This bug is too generic to debug. I'd need the actual log. There is a problem with a certain jpg format (#1440) which may be the problem

**Comment by regulator-g** [comment]
I tried turning on verbose logging but it doesnt crash so no log is sent?



OS Version: 4.9.185-g9f181f6db9d7-ab6027027 (6031801)
OS SDK: 29
Device (Manufacturer): blueline (Google)
Model (Product): Pixel 3 (blueline)
Package Installer: com.google.android.packageinstaller
Tablet: false
Screen Dimensions: 1080 x 2028

App: com.pitchedapps.frost
App Version Name: 2.4.2
App Version Code: 2040200

Url: (removed) 
Type: java.io.IOException
Message: No such file or directory
Prev version: -1
Random Frost ID: 1578783830365-207048671-FO
Locale: English (Australia)

**Comment by AllanWang** [comment]
It's the the message logged. Seems like a folder problem so I'll have to take a look. I'm guessing all images fail to download?

**Comment by regulator-g** [comment]
All images fail,  thanks for looking into it

**Comment by burakku-sabasu** [comment]
I am also experiencing this issue on the Pixel 4 XL, same errors.  All images fail to download.  I can long-press and view image, but the download fails when I press the download button.  

Details (please provide at least the app version):
    App Version: 2.4.2
    Device: Pixel 4 XL
    Android Version: 10
    Frost via F-Droid store
    Frost has access to Storage, denied access to Location
    Can successfully upload photos

**Comment by AllanWang** [comment]
I will see if I can get a hold of a pixel 4 xl to test

**Comment by mabster314** [comment]
Same error on original Pixel.

OS Version: 3.18.137-g72a7a64494e (5972272)
OS SDK: 29
Device (Manufacturer): sailfish (Google)
Model (Product): Pixel (sailfish)
Package Installer: com.google.android.packageinstaller
Tablet: false
Screen Dimensions: 1080 x 1794

App: com.pitchedapps.frost
App Version Name: 2.4.3
App Version Code: 2040300

Url: (removed)
Type: java.io.IOException
Message: No such file or directory
Prev version: -1
Random Frost ID: 1581820119305-932252159-FO
Locale: English (United States)

**Comment by Teryss** [comment]
[frost.txt](https://github.com/AllanWang/Frost-for-Facebook/files/4244413/frost.txt)
I expierience the same issue with app. It only bugs with images, I can download videos without any problem.

I'm attaching a logcat file, don't know if it helps, but willing to provide the information needed. So if it's not enough or you'd want some kind of sorting in logcat or needed some other info, please tell me and I'm gonna do my best!

Btw I really appreciate your work and maybe it isn't a place for that, but is there a way for one-time donation? I saw only on github donation in a subscrpition way.

CrDroid 6.3 Android 10
Predator 5.3C kernel
App version: 2.4.3
Redmi note 7

**Comment by burakku-sabasu** [comment]
I can confirm I can download videos, but not pictures.  

2.4.3
Pixel 4 XL
Android 10

**Comment by burakku-sabasu** [comment]
Can confirm I can download videos, but not pictures.  

2.4.3
Pixel 4 XL
Android 10

**Comment by AllanWang** [comment]
I believe the two use different folders, so it is helpful to know that one works and the other doesn't. I know that this issue is still unverified, but I haven't had a change to personally replicate the problem (and last I checked it works on OnePlus). I will try to get to it this weekend.

> Btw I really appreciate your work and maybe it isn't a place for that, but is there a way for one-time donation? I saw only on github donation in a subscrpition way.

If you wish to donate, you can send stuff to [my paypal](https://paypal.me/allanw97), but I'd like to stress that donations are purely for the sake of donations, and that I'm not looking to meet any minimum to continue working on this project.

**Comment by AllanWang** [comment]
For those here, please try out https://github.com/AllanWang/Frost-for-Facebook-APK-Builder/releases/tag/v2748
