### ISSUE TITLE
Only black text

### ISSUE THREAD

**Issue by Jowat97** [AllanWang/Frost-for-Facebook#1638]
Hello there,

since the last update, the text will stay always black. If you use a black theme, with a black background, the text will also stay black, so you can't see it at all. Even if you use a custom design and choose the text color yourself, it will always stay black, no matter which color you choose..

 - App Version: 2.4.3

**Comment by Godecki** [comment]
Can confirm. However, I tried installing 2.4.2 and 2.4.1 instead because of this issue and it persists in both of this versions, too

**Comment by ofrinevo** [comment]
Adding to this.
I wasn't on 2.4.3 and the bug appeared to me this morning.
Updated to 2.4.3 in hopes to fix it but it didn't.
Probably Facebook changed something on their end?

**Comment by ErebosGR** [comment]
I was using the 2.4.3 github apk from Feb 5 and the theme was working fine until today, so definitely Facebook broke it on their end as soon as the F-droid build was released yesterday. Intentional maybe?

**Comment by fitittome** [comment]
> Adding to this.
> I wasn't on 2.4.3 and the bug appeared to me this morning.
> Updated to 2.4.3 in hopes to fix it but it didn't.
> Probably Facebook changed something on their end?

Agreed, same for me.  I was on 2.4.2 previously.  The only usable themes now are Default or Light.

**Comment by AllanWang** [comment]
Facebook changed, and I can replicate the problem. This should be addressed by the weekend, and I will probably have a quick fix test build out slightly sooner

**Comment by OscarBarrett** [comment]
It looks like Facebook has reverted whatever change they made? Text is visible again for me now.

**Comment by Godecki** [comment]
@OscarBarrett Yeah, it's fixed, at least for now

**Comment by AllanWang** [comment]
Confirmed it currently is reverted. Closing this for now. Feel free to make a new issue if a theming problem occurs (I'm less likely to see comments on closed issues)
