### ISSUE TITLE
Most Recent Feed Broke

### ISSUE THREAD

**Issue by 3drinks** [AllanWang/Frost-for-Facebook#1653]
I've just encountered an issue on the most recent feed. "Top stories" feed still appears to be working as intended (which is to say worthless chronologically but I digress). I'm uploading a screen cap of the issue I'm seeing.

![Screenshot_20200224-230336_Frost](https://user-images.githubusercontent.com/43733276/75222811-de35e000-5759-11ea-9502-8607260ca6d0.jpg)

**Details (please provide at least the app version):**
 - App Version: 2.4.3
 - Device: s8+ sm-955U
 - Android Version: 9.0

**Comment by AllanWang** [comment]
That happens a lot. You can try disabling "aggressive recents", which tries to filter out posts that shouldn't be in recents. If you try on mobile you'll probably notice the same results; Facebook does not always show a reorder of the same posts in top stories
