### ISSUE TITLE
You closed my report earlier but. Re: recent feed

### ISSUE THREAD

**Issue by 3drinks** [AllanWang/Frost-for-Facebook#1654]
When I came back to do what you suggested, turning off aggressive recents, forcing a cold restart, the problem persisted. Again the feed appears as intended under top stories.

**Comment by Genis-Sage** [comment]
hey @3drinks 
you only read the first have of AllanWang's answer 

> If you try on mobile you'll probably notice the same results; Facebook does not always show a reorder of the same posts in top stories

you should go to m.facebook.com to the menu --> recent stories (or how it is called)
you will see, this page is also empty, i just tried it out

so the behaviour is an issue of the mobile fb site, not of frost

**Comment by AllanWang** [comment]
^ Correct. I'll keep this open for now, but if you try in a browser you'll likely see the same problem. If it were caused by Frost, I currently have no ideas on how to address it. For the most part, I don't believe Frost can modify what data is loaded. If a page is completely broken, then that's a different problem

**Comment by 3drinks** [comment]
> ^ Correct. I'll keep this open for now, but if you try in a browser you'll likely see the same problem. If it were caused by Frost, I currently have no ideas on how to address it. For the most part, I don't believe Frost can modify what data is loaded. If a page is completely broken, then that's a different problem

I have seen it on the mobile site and desktop site. So what is my recourse? Is it to just use the top comments feed, because that is not what I'm looking for and would just show me stuff that is hours or days old.

**Comment by AllanWang** [comment]
By seen it, do you mean the problem also occurs? There isn't much I can do. One factor may be the desktop user agent, but that must remain as is for now until I test mobile again. I don't have other ideas, since aggressive recents is the only thing that filters out content

**Comment by 3drinks** [comment]
Yes, thats exactly what I mean. The problem has seemed to go away since joining a high activity user group, however, which suggests to me the problem was related to my low following count (by that, I mean I keep a small friends list and a very low number of interests.

**Comment by AllanWang** [comment]
In that case the problem is on Facebook's end. I can't resolve it. Sorry

This bug is a follow up from #1653
