### ISSUE TITLE
Messaging: Text box does not expand when typing a message

### ISSUE THREAD

**Issue by GibberMeJenks** [AllanWang/Frost-for-Facebook#1655]
Hello! I am not sure if this is a bug or a improvement request, so left it open for you to assign as such! However, based on my experience it is a bit difficult to use the app in terms of messaging because of it.

When in messaging, the message box does not expand big enough to show you what you are typing. This makes it very difficult to read over the message as you need to scroll up to re-read the message, and if you're not careful, scrolling may 'refresh' the page where you are at, making you lose your message process.

Attached is a sample screenshot.
![Message_Box_Not_Expanding](https://user-images.githubusercontent.com/53843087/75615248-396b2800-5af6-11ea-867f-218011a7df84.jpg)

Would it be possible when messaging, to make this box a bit bigger to see more of what you are typing?

**Comment by AllanWang** [comment]
I can add this since it's pretty annoying to deal with. On desktop, you're typically able to drag the lower right corner to expand the text area. The indicator is still there on mobile, but it's really small and I personally couldn't drag it. I will try to add on option to allow all text areas to expand as you type

**Comment by GibberMeJenks** [comment]
That's great! Thank you so much, looking forward to when it's added in!

**Comment by GibberMeJenks** [comment]
Hi @AllanWang! This is a continual reference to #1655.

First off, thank you for the update to 2.4.5! I was very exciting to see the expanding text box function added in. However, when sending a message today I noticed the text box did not expand (this is when responding or initiating a message to someone from an existing conversation string):

![Text box not expanding](https://user-images.githubusercontent.com/53843087/83939177-a0504b00-a78f-11ea-9e5b-7282189c6b76.PNG)

Is this a bug? The size of a text bug when composing a new message to someone you never messaged before however, looks great:

![new message larger text box](https://user-images.githubusercontent.com/53843087/83939187-b78f3880-a78f-11ea-84e4-d9e573240745.PNG)

Not sure if it would be possible to make the text box the same size as the one when composing a new message if the expanding doesn't work.

Thanks again for the hard work, and stay safe during this time! Let me know if you need more info!

**Comment by AllanWang** [comment]
Linked PR and closing this for now. Will follow up with the new bugs in the other issue

**Comment by AllanWang** [comment]
Reopening for now as the fix is causing problems for some (#1704)
