### ISSUE TITLE
German Translation Cut Off / Missing

### ISSUE THREAD

**Issue by Glitchy-Tozier** [AllanWang/Frost-for-Facebook#1659]
**Describe the bug**
As seen in the pictures, the German translation often takes up too much space, which in some places either results in texts being on top of other ones or them being cut off mid-sentence.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the fifth screen in the very first start-up dialogue *or* go to the notifications tab.
2. See error

**Details (please provide at least the app version):**
 - App Version: v2.4.3
 - Device: Samsung Galaxy S9
 - Android Version: 10

**Screenshots**

![frost_s1](https://user-images.githubusercontent.com/59611881/75623758-3e3ae500-5ba5-11ea-8b22-855dcd0a5449.jpeg)
![frost_s2](https://user-images.githubusercontent.com/59611881/75623759-3f6c1200-5ba5-11ea-8fa3-adb15543a95c.jpeg)

**Comment by AllanWang** [comment]
For this screenshot, I believe the translation on the top next to the settings gear is from Facebook. There isn't much I can do about that. If there's a problem with anything in the screenshot, that can potentially be addressed

**Comment by Glitchy-Tozier** [comment]
You wrote "screenshot" two times. Is the second "screenshot" talking about the second picture I uploaded or still targeting the first?

In the second picture, the sentence is just cut off.
It (the last sentence) is "Long-press on pictures to [cut off]".

Possible solutions could be to make the text slightly smaller or to enlage the textbox so that 4 lines fit into that space.
