### ISSUE TITLE
Show reacts to messages

### ISSUE THREAD

**Issue by GibberMeJenks** [AllanWang/Frost-for-Facebook#1662]
Would it be possible to show the message reacts based on messages you send to others?

For example, the image below has a heart icon based on my friend's reaction, but it is missing in the app:

![Message_React_Missing](https://user-images.githubusercontent.com/53843087/76375661-9b503c80-6303-11ea-86f3-c49dfd10b1f1.PNG)

No rush or anything, I use messaging a lot and this would be a nice feature. Sometimes I think my friends see my message and don't reply but they do with reacts haha. 

Thanks so much!

**Comment by AllanWang** [comment]
This and a few other issues revolve around supporting messenger. Currently only the mobile fb messages page is supported. I don't really mind if I can get around some of the desktop limitations, but it definitely won't be a great experience. No push notification, interactions based around mouse and keyboard, and what I assume is a more frequently updated site will lead to a lot of bugs.

I'm still considering it, though I'm mainly waiting to find a way to get push notifications before supporting anything that more or less requires it

**Comment by GibberMeJenks** [comment]
No worries! A large reason I use this app is because it is significantly more user friendly, customizable, and also privacy friendly (Facebook itself isn't really privacy friendly, but at the very least I can restrict even more access to my phone in this case). If adding on the above feature conflicts with that, I can live without it haha!

Thanks for your continued hard work with this app and the quick response too!

**Comment by AllanWang** [comment]
Closing as duplicate for #1667. If I add messenger support then it will have reactions
