### ISSUE TITLE
Can't download images/videos, download manager bugs when no stock gallery

### ISSUE THREAD

**Issue by Teryss** [AllanWang/Frost-for-Facebook#1664]
As the title, I'm unable to save images and videos. I've encountered this bug in 2.4.3, but the thread was closed as in changelogs the issue was fixed, but for me it still doesn't work :(

I tried making a logcat, and here it is what i found and it repeats itself:

[ 03-13 20:35:36.538 13330:13552 D/DownloadManager ]
[65] Starting

[ 03-13 20:35:36.557 13330:13552 D/NetworkSecurityConfig ]
No Network Security Config specified, using platform default

[ 03-13 20:35:36.558 13330:13552 D/NetworkSecurityConfig ]
No Network Security Config specified, using platform default

[ 03-13 20:35:36.562  2751:13553 E/ResolverController ]
No valid NAT64 prefix (103, <unspecified>/0)

[ 03-13 20:35:36.670  3838: 3838 D/InterruptionStateProvider ]
No heads up: unimportant notification: 0|com.android.providers.downloads|0|1:com.pitchedapps.frost|10104

[ 03-13 20:35:36.827   735:  735 I/perf@2.0-servic ]
type=1400 audit(0.0:3337): avc: denied { write } for name="sched_freq_aggregate_threshold" dev="proc" ino=31665 scontext=u:r:init:s0 tcontext=u:object_r:proc:s0 tclass=file permissive=1

[ 03-13 20:35:36.827   735:  735 I/perf@2.0-servic ]
type=1400 audit(0.0:3338): avc: denied { write } for name="cpu_min_freq" dev="sysfs" ino=25044 scontext=u:r:init:s0 tcontext=u:object_r:sysfs_msm_perf:s0 tclass=file permissive=1

[ 03-13 20:35:36.827   735:  735 I/perf@2.0-servic ]
type=1400 audit(0.0:3339): avc: denied { open } for path="/sys/module/msm_performance/parameters/cpu_min_freq" dev="sysfs" ino=25044 scontext=u:r:init:s0 tcontext=u:object_r:sysfs_msm_perf:s0 tclass=file permissive=1

[ 03-13 20:35:37.209 13330:13558 D/DownloadManager ]
[66] Starting

[ 03-13 20:35:37.225 13330:13558 D/NetworkSecurityConfig ]
No Network Security Config specified, using platform default

[ 03-13 20:35:37.226 13330:13558 D/NetworkSecurityConfig ]
No Network Security Config specified, using platform default

[ 03-13 20:35:37.301  3838: 3838 D/InterruptionStateProvider ]
No heads up: unimportant notification: 0|com.android.providers.downloads|0|1:com.pitchedapps.frost|10104

[ 03-13 20:35:37.354  3838: 3838 I/chatty   ]
uid=10172(com.android.systemui) identical 2 lines

[ 03-13 20:35:37.357  3838: 3838 D/InterruptionStateProvider ]
No heads up: unimportant notification: 0|com.android.providers.downloads|0|1:com.pitchedapps.frost|10104

[ 03-13 20:35:37.569 13330:13552 W/DownloadManager ]
[65] Stop requested with status HTTP_DATA_ERROR: Failed to connect to video.fwaw8-1.fna.fbcdn.net/212.2.112.148:443

[ 03-13 20:35:37.573 13330:13552 D/DownloadManager ]
[65] Finished with status WAITING_TO_RETRY

[ 03-13 20:35:37.618 13330:13330 D/DownloadManager ]
onStopJob id=65, reason=0

[ 03-13 20:35:37.637   749:  749 I/surfaceflinger ]
type=1400 audit(0.0:3340): avc: denied { use } for path="anon_inode:sync_fence" dev="anon_inodefs" ino=12051 scontext=u:r:init:s0 tcontext=u:r:untrusted_app:s0:c194,c256,c512,c768 tclass=fd permissive=1

[ 03-13 20:35:37.724  3838: 3838 D/InterruptionStateProvider ]
No heads up: unimportant notification: 0|com.android.providers.downloads|0|1:com.pitchedapps.frost|10104

[ 03-13 20:35:37.728  3838: 3838 D/InterruptionStateProvider ]
No heads up: unimportant notification: 0|com.android.providers.downloads|0|1:com.pitchedapps.frost|10104

[ 03-13 20:35:37.741 13330:13562 D/DownloadManager ]
[67] Starting

[ 03-13 20:35:37.744  3838: 3838 D/InterruptionStateProvider ]
No heads up: unimportant notification: 0|com.android.providers.downloads|0|1:com.pitchedapps.frost|10104

[ 03-13 20:35:37.745  3838: 3838 D/InterruptionStateProvider ]
No heads up: unimportant notification: 0|com.android.providers.downloads|0|1:com.pitchedapps.frost|10104

[ 03-13 20:35:37.756 13330:13562 D/NetworkSecurityConfig ]
No Network Security Config specified, using platform default

[ 03-13 20:35:37.757 13330:13562 D/NetworkSecurityConfig ]
No Network Security Config specified, using platform default

[ 03-13 20:35:37.840  3838: 3838 D/InterruptionStateProvider ]
No heads up: unimportant notification: 0|com.android.providers.downloads|0|1:com.pitchedapps.frost|10104

[ 03-13 20:35:37.889  3838: 3838 I/chatty   ]
uid=10172(com.android.systemui) identical 2 lines

[ 03-13 20:35:37.890  3838: 3838 D/InterruptionStateProvider ]
No heads up: unimportant notification: 0|com.android.providers.downloads|0|1:com.pitchedapps.frost|10104

And at the end of logcat

[ 03-13 20:35:51.768  2741: 2835 W/MediaAnalyticsItem ]
Failed to record: [1:drm.vendor.Google.WidevineCDM:32:-1:com.pitchedapps.frost:0:-1:1:0:0:] [forcenew=0]

Also, when I had stock gallery uninstalled, the images in download manager wouldn't show up and the screen was black with buttons in right top corner

Android 10 / crDroid 6.3
Redmi note 7
App version 2.4.4

**Comment by AllanWang** [comment]
The log doesn't show too much beyond that the download manager fails to connect. There are also no error messages; only warnings. If you can, capture the error log, and send it to me privately if it's sensitive. I am simply passing a url to the download manager though, and this used to always be the case for videos, so it being broken may mean something else for you.

**Comment by Teryss** [comment]
[error.txt](https://github.com/AllanWang/Frost-for-Facebook/files/4332712/error.txt)
Idk if it matters, but I'm using Blokada with DNS enabled and afwall+ Killing both apps doesn't fix the issue, but maybe it's worth mentioning

**Comment by AllanWang** [comment]
There's still no useful information. For future reference, you'd probably also want to clear your log prior to sending a report as it'll make it shorter. 

If your image activity loads the image and there's also the download button, then I would say the bug falls outside of Frost. The image has downloaded successfully, and the url is passed to a system service. I currently do not have plans to make my own download manager

**Comment by Teryss** [comment]
Ok, thanks for looking into that! Maybe installing fresh new rom will help :/
Have a nice day!
