### ISSUE TITLE
AudioMix wakelock

### ISSUE THREAD

**Issue by Godecki** [AllanWang/Frost-for-Facebook#1665]
I am ocassionaly encountering a wakelock caused by Frost and it's AudioMix. Today, for example I haven't played any videos/music on Frost and this wakelock occured 32 times within around 4h of phone usage, with total of 1,5h worth if wakelock.

**Comment by AllanWang** [comment]
This seems to be a common wakelock. I don't have any details or actions Frost can take, but any audio played either comes from the webview, exoplayer (for PIP videos), or maybe the notification ringtones. Otherwise, I do not handle audio directly myself
