### ISSUE TITLE
Location shared without consent

### ISSUE THREAD

**Issue by ghost** [AllanWang/Frost-for-Facebook#1666]
Hello,

I clicked on "Local" and saw that Facebook suggests me places in the city where I am.

Problem:
- Since I arrived in this city, I only used Facebook on Frost
- I didn't give Frost permission for getting my location
- I didn't share anything on Facebook in this regard (only using for messages)

Do you know how come Facebook can still have this information?
Is there a way to hide it?

Thanks

PS: I'm on Android 10

**Comment by AllanWang** [comment]
There's many ways Facebook could have gotten your location. Sites can get your general location through your IP address, which applies to more than just Facebook. If you've uploaded any Photos with metadata, or mentioned anything in your messages, Facebook could have extracted your general location there too. As of now, I don't see any further action Frost can take
