### ISSUE TITLE
Support messenger.com

### ISSUE THREAD

**Issue by BearBuster** [AllanWang/Frost-for-Facebook#1667]
Hi,
I think, that new tab, with adopted to mobile view, messenger site, will bring many featurrs, like:
Calls, file transfer, emoji, gifs...

Same is done on FaceSlim. But calls don't work for me there, and is not really mobile friendly.

Also, on PC, calls work only through Chrome browser.
Thank you!

**Comment by Vintic** [comment]
Can be helpful: https://github.com/sindresorhus/caprine
Cross-platform Messenger desktop app.

**Comment by t0ma5** [comment]
this would be gold! specially now that https://touch.facebook.com/messages doesn't work anymore.. 
More info here https://github.com/AllanWang/Frost-for-Facebook/issues/1732

**Comment by t0ma5** [comment]
> Same is done on FaceSlim. But calls don't work for me there, and is not really mobile friendly.

do you mean this faceslim? last release 2018?
https://github.com/indywidualny/FaceSlim/releases
