### ISSUE TITLE
Search for a hashtag results in error

### ISSUE THREAD

**Issue by durka** [AllanWang/Frost-for-Facebook#1668]
- [x] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
Searching for a hashtag doesn't return any results, instead a blank "Error Facebook" page pops up.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to news feed
1. Click on search bar
1. Enter a search term starting with '#', such as '#foo'
1. Hit enter
1. See error

**Details (please provide at least the app version):**
 - App Version: 2.4.4
 - Device: Moto G6
 - Android Version: 9

**Comment by AllanWang** [comment]
Good catch. Query should be encoded, `#` -> `%23`
