### ISSUE TITLE
Cannot login to Facebook on Desktop when logged in to Frost

### ISSUE THREAD

**Issue by GibberMeJenks** [AllanWang/Frost-for-Facebook#1671]
Hello!

I got the following error just today when logging in to my Facebook on my desktop:

"Sorry, something went wrong.
We're working on getting this fixed as soon as we can."

I then get a notification on Frost from Facebook that there was an unauthorized login. Even after saying it's from me and saving my browser, I can no longer login from my desktop.

Currently using the latest version.

Thank you!

**Comment by AllanWang** [comment]
Can you still not log in? It's hard to say what's going on, or if this problem is definitely associated with Frost.

**Comment by GibberMeJenks** [comment]
Hi, sorry for the delay! Just an update, I think I fixed the issue.

I had two factor authentication on, and turned it off using Frost then turned it back on again and then reset the authentication code by scanning the QR code again through my phone.

I think the issue was caused when you don't verify that the login was from you through an unrecognized browser, so as a security measure the account got locked on my desktop but not through phone on Frost.

To prevent this I'm guessing you should confirm it was you logging in through desktop every once in a while.
