### ISSUE TITLE
account locked again

### ISSUE THREAD

**Issue by gothmog123** [AllanWang/Frost-for-Facebook#1675]
is this problem coming back?

account locked due to suspicious activity.

latest frost from F-droid

**Comment by AllanWang** [comment]
As of now you seem to be the only request. I am closing this for now as there are several factors to account locks, but if I get more requests I will reopen and link it here

**Comment by evanbishop** [comment]
I'm having this issue too. Facebook locked my account twice in a week. I'm quite certain I wasn't phished. I haven't even used Facebook outside of Frost.

**Comment by AllanWang** [comment]
Moved to new issue above. If others have the same issue I'll get a better idea, though I'm not aware of any further changes I can do to fix this. I've already been considering getting Frost back to using mobile agents as it limits a bunch of features.

Please move conversations to the new issue as it is harder to follow up on closed ones
