### ISSUE TITLE
copy URL

### ISSUE THREAD

**Issue by msjasinski** [AllanWang/Frost-for-Facebook#1676]
I need an option to copy current webpage (in order to share or save it). It is present only in groups sometimes.
It is the most lacking feature imho.
Thanks for the useful app!

**Comment by AllanWang** [comment]
Are overlays showing? Each overlay has options to copy link, share, and open in browser

**Comment by msjasinski** [comment]
> Are overlays showing? Each overlay has options to copy link, share, and open in browser

I enabled overlays in Settings/Behaviour. Now it works. Thanks.
