### ISSUE TITLE
font scaling slider breaks after reset

### ISSUE THREAD

**Issue by osowiecki** [AllanWang/Frost-for-Facebook#1678]
Reset your font to default by long pressing the percentage. Now your slider is stuck at that value until you leave the appearance menu.

**Comment by AllanWang** [comment]
What version are you on? I cannot reproduce the issue. Video would be nice if you are noticing some kind of disabled state

**Comment by osowiecki** [comment]
ver 2.4.4

https://www.youtube.com/watch?v=syeE8JD8reU

**Comment by AllanWang** [comment]
I still cannot replicate the issue, but feel free to try 2.4.5 or the new update when it comes out to see if it resolves it.
