### ISSUE TITLE
Keyboard hiding after new message

### ISSUE THREAD

**Issue by alekksander** [AllanWang/Frost-for-Facebook#1683]
When chatting, keyboard is hiding each time new message is shown in chat – regardless sent/received. This happens during composing as well. Additionally all existing text in composing box is disappearing.

•v2779 (frost-test)
•android 8.1

**Comment by AllanWang** [comment]
Did you close this because it no longer occurs or?

**Comment by alekksander** [comment]
webview 83.0.4103.83 was trouble causer. On 83.0.4103.96 it's all good.

**Comment by alekksander** [comment]
occurs only on 83.0.4103.83. webview update fixes it
