### ISSUE TITLE
Option to disable Swipe Left (go back)

### ISSUE THREAD

**Issue by orangemango** [AllanWang/Frost-for-Facebook#1713]
**Describe the feature**

Hello! Thank you for offering us this awesome alternative to the horrible Facebook app.

I would like to be able to disable the Swipe Left feature because too often I get back to previous page by mistake. Worst scenario for me is being on a Webview (external link) looking at pictures in a caroussel and swiping left to see the previous picture > I leave the webview.

**Comment by AllanWang** [comment]
You should be able to mitigate this by going to settings behavior and only allowing swipes to happen from the edge. Let me know if that works
