### ISSUE TITLE
Most Recent feed view shows Welcome to Facebook

### ISSUE THREAD

**Issue by gbakeman** [AllanWang/Frost-for-Facebook#1715]
- [x] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
Within the last few days, the Most Recent feed is just showing a default introduction telling us to add new friends, even though I already have done. I don't know if this is a temporary Facebook hiccup or a longer-term change that may need to be addressed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open app
2. If default view is set to most recent, then the introduction is displayed rather than my feed.

**Details (please provide at least the app version):**
 - App Version: 2.4.5
 - Device: OnePlus 6T
 - Android Version: 9

![Screenshot_20200920-193152](https://user-images.githubusercontent.com/842942/93729114-f5b23b80-fb77-11ea-9520-6be0f3c5fd96.jpg)

**Comment by creativetrendsapps** [comment]
When you verified the issue doesn't occur in your mobile browser, what steps did you take to verify it? What is the link to the most recent feed in your browsers address bar? What browser were are you using?

**Comment by gbakeman** [comment]
> When you verified the issue doesn't occur in your mobile browser, what steps did you take to verify it? What is the link to the most recent feed in your browsers address bar? What browser were are you using?

I visited the aforementioned URL in Firefox for Android (68.11.0) and also /home.php, both appeared to be working fine.

**Comment by creativetrendsapps** [comment]
Did you verify that was the most recent feed though? By default you are sent to the top stories feed, not most recent. Try again and go to the more menu and tap most recent. Does that work in your browser? If it does. Can you post the specific link to the most recent feed.

**Comment by creativetrendsapps** [comment]
> > When you verified the issue doesn't occur in your mobile browser, what steps did you take to verify it? What is the link to the most recent feed in your browsers address bar? What browser were are you using?
> 
> I visited the aforementioned URL in Firefox for Android (68.11.0) and also /home.php, both appeared to be working fine.

Does this specific link to the most recent feed work? https://touch.facebook.com/home.php?sk=h_chr ......... 

It's important to note that:
https://touch.facebook.com **&** https://touch.facebook.com/home.php are the default **top stories** feed.

**Comment by gbakeman** [comment]
Sorry, I missed the Most Recent link when I checked - the real Most Recent feed (sk=h_chr) does in fact show the same behaviour as Frost right now.

**Comment by creativetrendsapps** [comment]
> Sorry, I missed the Most Recent link when I checked - the real Most Recent feed (sk=h_chr) does in fact show the same behaviour as Frost right now.

Hopefully Facebook fixes it soon.

**Comment by AllanWang** [comment]
Thanks for replying! This is a known issue on Facebook's end. With aggressive recents disabled, Frost does not alter the feed, given how buggy it already is.
