### ISSUE TITLE
Content get refreshes after dark mode is toggled.

### ISSUE THREAD

**Issue by abhishekabhi789** [AllanWang/Frost-for-Facebook#1721]
This issue happens all the time, when system dark theme is changed, the page gets refreshed.
It doesn't matter if the app is in foreground or background.
Google chrome has an experimental feature to prevent this [night-mode-tab-reparenting](chrome://flags/#enable-android-night-mode-tab-reparenting) 

Also it'll be very helpful if the app can cache last opened pages and last few opened URLs, so that it can be again opened like in facebook android app, without loading time.
And auto feed refresh is only with user action or after app restart.

**To Reproduce**
1. Open frost
2. Toggle dark mode
3.  Or toggle again after minimising frost in background

**Details**
 - App Version: 2.4.6
 - Device: Redmi Note 4 (RROS 8.6.1)
 - Android Version: 10

**Comment by AllanWang** [comment]
If you don't swipe away a page and reopen the app, it'll retain the state like the normal app. If you kill the official app, I'm pretty sure it reverts to the newsfeed either way. 

For theme toggles, I could consider avoiding it restart. Ideally I'd add support for a separate theme when dark mode is enabled.

**Comment by abhishekabhi789** [comment]
Thanks. I think the loading time is due to loading cached html codes. Not a problem.

Another thing is when scrolled down few times on newsfeed, tapping back button will close the app instead of going back to top of the page. The newsfeed icon works by going top of the page. But back button simply closes the app. In official app, back button scrolls to page top.

**Comment by AllanWang** [comment]
Back press aligns with most browser behaviours. They won't scroll up for you on back press. It won't be feasible to bring a browser load speed up to native app speed due to the nature of what is loaded. It is also pretty futile to cache data from social media since it's always changing. Even facebook refreshes their own feeds sometimes after some delay

**Comment by AllanWang** [comment]
Probably fixed in cc17381e78caabbd8920741c4d1b41a79f319173. Refresh on Frost settings change is done intentionally
