### ISSUE TITLE
Deleting Conversation (s) in Messenger.

### ISSUE THREAD

**Issue by DigiG0d** [AllanWang/Frost-for-Facebook#1722]
**Describe the feature**

Thanks for creating the best Facebook alternative app. It's all I use. I know everyone is working hard to integrate new features into the app and you're all doing incredible. The only complaint I have is not being able to delete old conversations in messenger manually. Usually long-pressing the conversation gives you the option to do so. But that's my only itch. Thanks for all of your hard work and contributions.

**Comment by AllanWang** [comment]
This can only be resolved by supporting messenger, so closing this and following up at https://github.com/AllanWang/Frost-for-Facebook/issues/1667. Messenger support is non-trivial and I'm not sure if I can actually share login content between the two. It might have to be a different app

**Comment by DigiG0d** [comment]
Okay. Thank you.
