### ISSUE TITLE
Frost Dark mode changes to White randomly

### ISSUE THREAD

**Issue by DudeVirus** [AllanWang/Frost-for-Facebook#1724]
- [ ] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/) - Not applicable

**Describe the bug**
Manually refreshing the page ie:- swiping down to refresh OR sharing a post. It causes the dark mode to change to white. In frost settings I have Amoled mode selected. The app will stay white until I close the app and relaunch. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Share any post.
2. Refresh the feed. 

**Details (please provide at least the app version):**
 - App Version: 2.4.6
 - Device: OP7 Pro
 - Android Version: 10

**Comment by AllanWang** [comment]
Known issue within the past few days. Don't think it is because of the update but I will have to look around

**Comment by DudeVirus** [comment]
> Known issue within the past few days. Don't think it is because of the update but I will have to look around

I can confirm that this was not happening on 2.4.4. I had not updated the app since a while and didn't install 2.4.5 so can't comment if the same issue was on that or not.

**Comment by ofrinevo** [comment]
Can confirm it is also present in 2.4.5.

**Comment by Issam28** [comment]
Happening in 2.4.6

**Comment by AllanWang** [comment]
As a quick update, it looks like this change is either android or device dependent. It doesn't affect some of my older devices. Changes are being applied in the pr above, which basically involves injecting all the scripts more frequently
