### ISSUE TITLE
[Solved] App size "user data" increases

### ISSUE THREAD

**Issue by Albnu14** [AllanWang/Frost-for-Facebook#1733]
- [ ] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
The size of the app particularly "user data" increases with every photo viewed, it went from 730M to 780M as I viewed (not downloaded) about 10 images

**To Reproduce**
Steps to reproduce the behaviour:
1. Check the app size from settings
2. Open the app and view a page full of images, and let them load (no need to download)
3. Close the app and check the size again
4. Size increased quite a bit

**Details (please provide at least the app version):**
 - App Version: 2.4.7 (downloaded from f-droid)
 - Device: J7 2015
 - Android Version: Los 17 (android 10)

If this is necessary for offline browsing or a better experience please provide the user with the choice to stop the app from saving the browsed data.

Update : so the problem continued to heppen every time after deleting the data and opening and then closing and opening, till the last update of the app, in which it seems solved now the size of 'user data' doesn't go above 2MB, Thanks.

**Comment by creativetrendsapps** [comment]
Why would you expect the app not to save anything?

**Comment by Albnu14** [comment]
@creativetrendsapps
Not "anything", probably there are things that need to be saved (login details for one), but at least not the images and videos which take space even when I don't download them
This behaviour is understandable for offline browsing but I think the user should have the choice to enable or disable this.

**Comment by creativetrendsapps** [comment]
> @creativetrendsapps
> Not "anything", probably there are things that need to be saved (login details for one), but at least not the images and videos which take space even when I don't download them
> This behaviour is understandable for offline browsing but I think the user should have the choice to enable or disable this.

How do you think cache works? You're also basically using a browser when using Frost, any browser will automatically save data/write to cache. If available, move the app to the SD card.

**Comment by Albnu14** [comment]
@creativetrendsapps 
If it was cache I would simply delete it from the settings, what frost is saving is increasing the "user data" and I can't delete it unless I delete the app data,
It would be a good alternative to provide a way to delete these saved data inside the app if you think it's not possible to stop the app from saving data.
The same complain is applicable to the official app, but deleting the cache of it usually does the trick.

**Comment by creativetrendsapps** [comment]
> @creativetrendsapps 
> If it was cache I would simply delete it from the settings, what frost is saving is increasing the "user data" and I can't delete it unless I delete the app data,
> It would be a good alternative to provide a way to delete these saved data inside the app if you think it's not possible to stop the app from saving data.
> The same complain is applicable to the official app, but deleting the cache of it usually does the trick.

Every app saves "user data" though. The dev probably could add an option but it probably will clear data each time.

**Comment by Genis-Sage** [comment]
I can not reproduce this at all

For me, the user data is around 3 MB and the cache is about 35 mb
And when looking at pictures in Frost, the cache size changes... The user data stays the same

@Albnu14
how big is the cache for you?
What happens, if you delete the cache?
Do you see a similar behaviour for other apps, like your browser?

**Comment by Albnu14** [comment]
@Genis-Sage 
I would like to apologise for the trouble
After your comment, I tried frost again, I deleted the data, logged in, and as you said the user data didn't go beyond 5MB,
I don't know why, but I browsed quite a bit and only the cache size increased, which is normal, (the user data increased by a few KBs but nothing to worry about,)

The only thing that changed, since made this issue is that I deleted almost all the messages using messenger, I don't think it has to do with it, but I can't think of another reason, 

I will close this issue, and reopen it if this happens again.

**Comment by creativetrendsapps** [comment]
> @Genis-Sage 
> I would like to apologise for the trouble
> After your comment, I tried frost again, I deleted the data, logged in, and as you said the user data didn't go beyond 5MB,
> I don't know why, but I browsed quite a bit and only the cache size increased, which is normal, (the user data increased by a few KBs but nothing to worry about,)
> 
> The only thing that changed, since made this issue is that I deleted almost all the messages using messenger, I don't think it has to do with it, but I can't think of another reason, 
> 
> I will close this issue, and reopen it if this happens again.

No need to apologise to me. Maybe it was just old data sticking around like when Frost used native views for things.
