### ISSUE TITLE
Messenger tab not working when links are opened in Default App

### ISSUE THREAD

**Issue by amine250** [AllanWang/Frost-for-Facebook#1748]
- [x] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
When the option to open links in the default application (externally) is set, the messenger tab opens in the browser too.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Preferences
2. Click on Behaviour
3. Turn on Open Links in Default App
4. Go to the Messenger tab

**Details (please provide at least the app version):**
 - App Version: 3.0.0
 - Device: IN2023
 - Android Version: Android 11

**Comment by Perdellian** [comment]
Happens with me too.
I did some playing around, however, and found a (somewhat annoying to do every session) workaround:

**Launching Frost with _Settings_ > _Behavior_ > _Open Links in Default App_ DISABLED:**
1. Go to the Messenger tab and let it load
2. Reenable _Settings_ > _Behavior_ > _Open Links in Default App_
3. Return to Messenger tab

**Launching Frost with _Settings_ > _Behavior_ > _Open Links in Default App_ ENABLED:**
1. Disable _Settings_ > _Behavior_ > _Open Links in Default App_
2. Go to the annoyingly blank Messenger tab
3. Tap the tab's icon again to reload it (pull-down reload gesture just makes the throbber spin endlessly)
4. Reenable _Settings_ > _Behavior_ > _Open Links in Default App_
5. Return to Messenger tab

**Notes:**
After doing the above, subsequent taps on the Messenger tab icon (i.e. refreshing/reloading the tab) will try opening the link in the default app again
- No default app set
  - just cancel out of the prompt
  - Frost's Messenger tab still works
- Official Messenger app set as default
  - message shows up saying "This username doesn't exist. Try another link."
    - update: tried it again a little later, (perhaps after a relaunch?) and now it launches the official Messenger app. I'm removing that default.
  - Frost's messenger tab still works.


**Details:**
- App Version: 3.0.0 (github apk)
- Device: Pixel 2
- Android Version: 10 (LineageOS 17.1)

**Comment by KopiasCsaba** [comment]
+1 confirming of this

**Comment by montvid** [comment]
I have the same problem too. Messenger is trying to open my browser instead of working in app.

**Comment by AllanWang** [comment]
Extension of https://github.com/AllanWang/Frost-for-Facebook/issues/1732#issuecomment-767652877. Will look into this

**Comment by AllanWang** [comment]
So to gain clarity on this, do messenger links just not work at all when opened with the official messenger app? Seems like weird behaviour, but if it truly doesn't work, then I won't forward them ever.

If it's a matter of keeping messenger links in Frost while also using the official app, what is the use case there? Is it for the sake of different accounts? To me the ideal expectation would be to continue forwarding to messenger, and to have messenger properly parse links.

---

The main use case I'd resolve is for users without the messenger app who are getting forwarded to browsers instead. With this in mind, the update won't have any settings, and will simply keep messenger links inside Frost

**Comment by AllanWang** [comment]
Test build at https://github.com/AllanWang/Frost-for-Facebook-APK-Builder/releases/tag/v3020

Comment here if there are additional issues/file new bugs if there are new ones

**Comment by amine250** [comment]
> So to gain clarity on this, do messenger links just not work at all when opened with the official messenger app? Seems like weird behaviour, but if it truly doesn't work, then I won't forward them ever.
> 
> If it's a matter of keeping messenger links in Frost while also using the official app, what is the use case there? Is it for the sake of different accounts? To me the ideal expectation would be to continue forwarding to messenger, and to have messenger properly parse links.
> 
> ---
> 
> The main use case I'd resolve is for users without the messenger app who are getting forwarded to browsers instead. With this in mind, the update won't have any settings, and will simply keep messenger links inside Frost

The issue is not with messenger links, but with the messenger tab itself. Once the tab is clicked, the default browser (brave in my case) opens the link messenger.com.

**Comment by amine250** [comment]
> Test build at https://github.com/AllanWang/Frost-for-Facebook-APK-Builder/releases/tag/v3020
> 
> Comment here if there are additional issues/file new bugs if there are new ones

I'll test this and give feedback asap
