### ISSUE TITLE
Shinigami Eyes support

### ISSUE THREAD

**Issue by Perdellian** [AllanWang/Frost-for-Facebook#1752]
https://shinigami-eyes.github.io/
"A Chrome/Firefox addon that highlights transphobic/anti-LGBT and trans-friendly subreddits/users/facebook pages/groups with different colors."

I'd like to see support for this added to Frost if possible.
While I understand that Frost doesn't implement the WebExtension system used by Chrome and Firefox, I wonder if the extensions' site-code munging could be somehow integrated into Frost's.

The FAQ suggests that the extension does indeed work with Facebook's mobile site:
> **Can I use it on my phone?**
> Yes, if you use Firefox for Android (on mobile, Chrome doesn't support extensions). Note however that you won't be able to right-click (and therefore set new labels). 

Shinigami Eyes appears to be [MIT-licensed](https://github.com/shinigami-eyes/shinigami-eyes/blob/master/LICENSE), which would allow code to be legally included with Frost's GPLv3 codebase. I don't know enough about either Kotlin or Javascript to know how how well such inclusion would work on a technical level, unfortunately.

**Comment by AllanWang** [comment]
This would be a significant undertaking, and is currently too niche of a feature. Frost is more or less in maintenance mode now, so new feature support is very limited.

I believe I've received this request before, and those who want it are free to fork Frost and try to add it themselves.
