### ISSUE TITLE
Getting logged out when switching accounts

### ISSUE THREAD

**Issue by caviidae** [AllanWang/Frost-for-Facebook#1753]
- [X] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

When trying to switch to my second account, it logs that account out, then shows the "select facebook account" screen with my first account only. Clicking on that account logs it out as well.

**To Reproduce**
Steps to reproduce the behaviour:
1. Be logged in to two accounts
2. Open the sidebar
3. Click on the icon for another account
4. It logs that account out
5. Shows one account left
6. Click on the remaining account's icon
7. That one gets logged out too

Same thing happens from the 'Manage Account' screen.

**Details (please provide at least the app version):**
 - App Version: 3.0.0
 - Device: OnePlus 7 Pro
 - Android Version: 10

**Comment by AllanWang** [comment]
Is this new to 3.0.0? Are you using the messenger tab? I've noticed it too during testing, and it seems like the app momentarily visits the log out page during switching, which prompts the login page

**Comment by caviidae** [comment]
Yeah it started after I updated. I do use the messenger tab but this happens before I even use it.

Clicking any of the avatars in the sidebar or going to 'manage account' and doing it there logs out the account clicked on. 
![1](https://user-images.githubusercontent.com/19197453/106745631-4ef7a480-6619-11eb-9b00-87401883c9ec.jpg)
![2](https://user-images.githubusercontent.com/19197453/106745634-5028d180-6619-11eb-91c0-cd45a6761047.jpg)
 
So yeah kind of impossible to use multiple accounts right now without logging in again each time.

Pretty sure the actual avatars used to show but now they don't?

**Comment by AllanWang** [comment]
Reiterating from the other issue, but feel free to revert to pre 3.0.0 if you need multiple accounts more than messenger. That release hasn't been fully tuned for multi accounts yet, and I need to figure out what to do going forward with two login requirements per account.

Avatars were broken for a while, but they were "fixed" for me some time ago. I had planned on fixing it, but it worked on desktop the whole time, so I'm not sure what Facebook is doing with that endpoint.

**Comment by deanaba** [comment]
I've been seeing this for the better part of the year. (Before 3.0). I have two accounts, (family only, and all professional contacts). I add an acoount successfully, when I add second account, i am brought to a login screen, add the second account, what seems 
 succussfull. I go to switch accounts, and am brought to login screen. It's essentially logging me out of both accounts. I just verified it's in test build… version 3.0.0-19-bf55dbf-test, android 11.

**Comment by AllanWang** [comment]
That's interesting. I'll have to revisit, since it's been a long time since I've used that feature. There's probably something wrong with identifying when the app logs out that has changed. If it's server side logic, it would also break Frost regardless of app version, which is one of the difficulties when trying to fix bugs

**Comment by gesu92** [comment]
Here with the same problem, when switch to second account, getting logged out 😪😪.
I have a personal account and a profesional account, I love this app and need this feature ✌️✌️
Thanks a lot!

**Comment by MustafaMemisogM** [comment]
same issues

**Comment by AllanWang** [comment]
Test out https://github.com/AllanWang/Frost-for-Facebook-APK-Builder/releases/tag/v2991

If this works I'll release a new build relatively soon. Keeping the issue opened so I see replies but bug should be fixed

**Comment by caviidae** [comment]
@AllanWang switching accounts is fixed in that version, thanks! The account profile pictures still don't show but that's not a huge issue.

**Comment by AllanWang** [comment]
Sg. Still not sure what happened to the account profile photo since I think it works when testing on desktop. It was on and off for me at a time but I'll take a look in the future as a low priority bug (#1804)

**Comment by AllanWang** [comment]
v3.1.0 is released https://github.com/AllanWang/Frost-for-Facebook/releases/tag/v3.1.0

Should be on F-Droid automatically in a few days
