### ISSUE TITLE
Comentary/Notifications is white on custom themes

### ISSUE THREAD

**Issue by alefouau** [AllanWang/Frost-for-Facebook#1760]
**Description**

When using a custom theme, the comment balloons and the unread notification background are the default Facebook color
![Screenshot_20210227-003901](https://user-images.githubusercontent.com/56359523/109374561-143e0080-7895-11eb-88eb-5d0d7905a7cb.png)
![Screenshot_20210227-003858](https://user-images.githubusercontent.com/56359523/109374567-1a33e180-7895-11eb-8ef9-2569baf727a6.png)
My suggestion is adding an option to modify the color of coments/notifications background
My other suggestion is related to color of the header in main page, in the settings page its ok, but in main page the header is more darker, it would be good if was like settings page
![Screenshot_20210227-003913_1](https://user-images.githubusercontent.com/56359523/109374752-5287ef80-7896-11eb-8502-22de7fc5d991.png)
![Screenshot_20210227-003901_1](https://user-images.githubusercontent.com/56359523/109374753-574ca380-7896-11eb-94cc-18ccd8fb0df2.png)
Sorry for my english

**Details (please provide at least the app version):**
 - App Version: 3.0.0
 - Device: SM-G532M (Samsung Galaxy J2 Prime/Granprime Plus) 
 - Android Version: 6.0

**Comment by AllanWang** [comment]
Can't be replicated on my end. Facebook often has different CSS around the world, so someone would have to provide the css classes to address it. Second part is a UI bug, but it's low priority to address

**Comment by AllanWang** [comment]
Closing as still can't replicate
