### ISSUE TITLE
Black fonts in Dark Theme

### ISSUE THREAD

**Issue by Bon18** [AllanWang/Frost-for-Facebook#1763]
**Description**
In some pages/places, the fonts are black while choosing a Dark theme. When accessing the Menu (pressing Menu tab on the Nav bar) the fonts are white (Image 1) in Dark theme (as expected). These fonts are black in Light/Default theme. But, when I tap on "See more Groups" option, the next page opens with all Facebook Groups listed. In this page, all the group names are Black, which does not change its colour like the Menu page or other pages do (Image 2). The fonts are Black in Default/Light theme, but should be changed to White in a dark theme. This happens for both Dark theme or a Custom dark theme. 
I am attaching a screenshot of my current dark theme too, to let you know what colours I have chosen (image 3). 

**To see the issue:**
 - Go to Menu by tapping the Menu button on Nav bar. 
 - A dark theme should have been applied. 
 - From the Menu, Tap on "See more Groups" 
 - See the problem. 
 
**Screenshots:**
 - Image 1: 
! [Screenshot_20210309-105657_Frost](https://user-images.githubusercontent.com/80167060/110424078-37a05100-80c8-11eb-8bd7-5688345c0854.jpg)
 - Image 2: 
! [Screenshot_20210309-105029_Frost](https://user-images.githubusercontent.com/80167060/110424253-8221cd80-80c8-11eb-9596-13a1eef02a67.jpg)
 - Image 3:
! [Screenshot_20210309-105048_Frost](https://user-images.githubusercontent.com/80167060/110424336-a5e51380-80c8-11eb-8640-c62c0d5807ca.jpg)

**Details (please provide at least the app version):**
  - App Version: 3.0.0
  - Device: Samsung Galaxy J7 Pro (2017), and Samsung Galaxy A7 2018. 
  - Android Version: Android 9 Pie (J7) and Android 10 (A7).

**Comment by adarsh1001** [comment]
Can be reproduced in the AMOLED theme when one tries to create a new post in their profile:

![SmartSelect_20210314-011823_Frost.jpg](https://user-images.githubusercontent.com/8820038/111042443-708f4b80-8463-11eb-96e4-b0959962798a.jpg)
