### ISSUE TITLE
No message notification

### ISSUE THREAD

**Issue by dln949** [AllanWang/Frost-for-Facebook#1767]
Frost 3.0.0 on Android 11, running the latest version of grapheneOS.  

When I receive FB messages, no notifications appear in the top panel for the android device.  

But, if I look in the messages tab in Frost, it shows the new messages as unread.  

I believe I have everything turned on so that the notifications should appear, but they do not.  

Just for testing I randomly tried another app, Swipe, and that app does show notifications in the top android panel when Facebook messages arrive.  

The only way I can make a Frost notification appear in the top android panel is to manually obtain notifications within Frost - but then all I get is a notification that says there are no notifications.  

Same problem with the facebook touch web site.  

Why is Frost not producing notification?  

How do I fix that?  

Thanks.

**Comment by AllanWang** [comment]
Are you using the messenger tab? Notifications aren't supported there for now

**Comment by landry314** [comment]
i stopped getting new message notifications too.

**Comment by AllanWang** [comment]
Closed because of no response, but other issue is #1844 

Messenger notifications aren't supported if you're using that tab
