### ISSUE TITLE
Cannot Reply

### ISSUE THREAD

**Issue by DigiG0d** [AllanWang/Frost-for-Facebook#1768]
- [x] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any conversation in a group. 
2. Click on any post
3. Scroll down to any comment 
4. See only like or more. No option to reply.

**Details (please provide at least the app version):**
 - App Version: 3.0.0
 - Device: Samsung A21
 - Android Version: Latest

**Comment by AllanWang** [comment]
Unrelated to Frost. Even if it's in your browser and not Frost, the most it can be is due to user agents and facebook hiding certain things per agent.
