### ISSUE TITLE
When replying to messages, nothing shows up

### ISSUE THREAD

**Issue by moeb74** [AllanWang/Frost-for-Facebook#1772]
**Describe the bug**
When I reply to a message, my reply doesn't show up. I have to back out and then click on the icon at the top to go back into messenger to see my recent reply. 

Also I cannot post pictures in replies it posts. I get a yellow triangle with an exclamation in the middle.

These are both something new that recently popped up...

**Details (please provide at least the app version):**
 - App Version: 3.0.0
 - Device: s20fe
 - Android Version: 11

**Comment by moeb74** [comment]
Added another bug. Cannot post images either

**Comment by AllanWang** [comment]
Have you verified that this works for you in general? Pick a browser, go to messenger.com in desktop mode, and see how it works. Doesn't seem actionable, though images may require a permission prompt or some other integration on my end

**Comment by moeb74** [comment]
So I had to uninstall it and reinstall the older version. Everything is ok now. Not sure what happened.

**Comment by AllanWang** [comment]
Older version? I think only one version has messenger; so are you going back to the original messages webpage? That one has always been fine as long as it isn't blocked in your region. Messenger is flaky, and I likely don't have the time to look into it too deeply
