### ISSUE TITLE
Option to hide News Feed tab

### ISSUE THREAD

**Issue by RaghavRao** [AllanWang/Frost-for-Facebook#1773]
I would like to disable the news feed entirely on the app or make messages the default tab. Is this an easy feature to add?

**Comment by AllanWang** [comment]
Cross referencing https://www.reddit.com/r/FrostForFacebook/comments/msxs08/disable_newsfeed/

It already exists, and you can look at that thread on how to do it.

UI is not intuitive and was a result of me not wanting to implement custom draggable items (https://github.com/AllanWang/Frost-for-Facebook/issues/1749); may update in the future if I have time
