### ISSUE TITLE
Long press on photos crashes application

### ISSUE THREAD

**Issue by syphyr** [AllanWang/Frost-for-Facebook#1774]
- [x ] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

Long press on photos causes Frost to crash with fatal exception.

04-22 12:58:44.098  4402  4402 E AndroidRuntime: FATAL EXCEPTION: main
04-22 12:58:44.098  4402  4402 E AndroidRuntime: Process: com.pitchedapps.frost, PID: 4402
04-22 12:58:44.098  4402  4402 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.pitchedapps.frost/com.pitchedapps.frost.activities.ImageActivity}: g.v: lateinit property prefs has not been initialized
04-22 12:58:44.098  4402  4402 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2586)
04-22 12:58:44.098  4402  4402 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
04-22 12:58:44.098  4402  4402 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
04-22 12:58:44.098  4402  4402 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
04-22 12:58:44.098  4402  4402 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-22 12:58:44.098  4402  4402 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
04-22 12:58:44.098  4402  4402 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
04-22 12:58:44.098  4402  4402 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-22 12:58:44.098  4402  4402 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
04-22 12:58:44.098  4402  4402 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
04-22 12:58:44.098  4402  4402 E AndroidRuntime: Caused by: g.v: lateinit property prefs has not been initialized
04-22 12:58:44.098  4402  4402 E AndroidRuntime: 	at com.pitchedapps.frost.activities.ImageActivity.<init>()
04-22 12:58:44.098  4402  4402 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
04-22 12:58:44.098  4402  4402 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
04-22 12:58:44.098  4402  4402 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2576)
04-22 12:58:44.098  4402  4402 E AndroidRuntime: 	... 9 more

**Details (please provide at least the app version):**
 - App Version: Latest source on dev branch (bf55dbf9b46cd8826987ee6e556307e24f3d46cc)
 - Device: T813
 - Android Version: Nougat (lineage-14.1)

**Comment by syphyr** [comment]
I would also like to mention that uploading photos is not possible with latest source on dev branch.

**Comment by AllanWang** [comment]
Thanks. The changes in #1770 don't add anything to the end user, and is mainly an internal maintenance thing. You can revert back to an older build for now, but testing on dev branches is helpful.

More exceptions will occur in the app, but testing and adding more features will be easier for me in the future.

**Comment by AllanWang** [comment]
I'll keep this opened since it's likely an actual bug. But I'll resolve it in the future

**Comment by syphyr** [comment]
The issue here seems to be that the previously working code did not use lateinit when initializing prefs.

**Comment by AllanWang** [comment]
Yeah a few things broke when migrating to hilt. I'd like to keep it if possible and I'll look into the uninitialized lateinits

**Comment by syphyr** [comment]
The error message is slightly different now with the latest sources in dev.

```
09-13 22:49:52.233 22249 22249 E AndroidRuntime: FATAL EXCEPTION: main
09-13 22:49:52.233 22249 22249 E AndroidRuntime: Process: com.pitchedapps.frost, PID: 22249
09-13 22:49:52.233 22249 22249 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.pitchedapps.frost/com.pitchedapps.frost.activities.ImageActivity}: v8.v: lateinit property prefs has not been initialized
09-13 22:49:52.233 22249 22249 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2586)
09-13 22:49:52.233 22249 22249 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
09-13 22:49:52.233 22249 22249 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
09-13 22:49:52.233 22249 22249 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
09-13 22:49:52.233 22249 22249 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-13 22:49:52.233 22249 22249 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-13 22:49:52.233 22249 22249 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
09-13 22:49:52.233 22249 22249 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-13 22:49:52.233 22249 22249 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
09-13 22:49:52.233 22249 22249 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
09-13 22:49:52.233 22249 22249 E AndroidRuntime: Caused by: v8.v: lateinit property prefs has not been initialized
09-13 22:49:52.233 22249 22249 E AndroidRuntime: 	at com.pitchedapps.frost.activities.ImageActivity.<init>()
09-13 22:49:52.233 22249 22249 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
09-13 22:49:52.233 22249 22249 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
09-13 22:49:52.233 22249 22249 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2576)
09-13 22:49:52.233 22249 22249 E AndroidRuntime: 	... 9 more
```

**Comment by AllanWang** [comment]
Thanks. Not sure why that changed but that's the expected error message. I'll get to this before submitting the next release
