### ISSUE TITLE
The app hangs everytime I try to play a video

### ISSUE THREAD

**Issue by amine250** [AllanWang/Frost-for-Facebook#1776]
- [x ] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
The app hangs everytime I try to play a video, or a video story. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Play a video or a video story. 
2. Watch the app not responding until it crashes. 

**Details (please provide at least the app version):**
 - App Version: 3.0.0
 - Device: IN2023
 - Android Version: 11

**Comment by Appoox** [comment]
Exactly the same issue.

Same Ways to reproduce.

App Version: 3.0.0
Device: IN2021 (Oneplus)
Android Version: 11

**Comment by AllanWang** [comment]
I'd either need a log or I'd have to be able to reproduce it myself to address this.

**Comment by Appoox** [comment]
I don't know why, but the problem just stopped occurring today for me. I would be happy to post a log if you can tell me where to find it.

**Comment by AllanWang** [comment]
You can look up how to get logs online as there are several ways. Easiest way is to connect via adb to view logcats, and there are other ways if you're rooted. Frost used to have a bug report tool that would do it for you but I removed it since it counts as app tracking on F-Droid

**Comment by AllanWang** [comment]
Can't fix crashes without logs unless it's very reproducible. Videos were tested on 3.1.1
