### ISSUE TITLE
Easily add an event to android calendar?

### ISSUE THREAD

**Issue by vijay-prema** [AllanWang/Frost-for-Facebook#1777]
**Describe the feature**
Not sure how possible this is, but I would like to be able to easily add a private event I am viewing in Frost, into my Android phones calendar app.   Maybe a way to do it is download link of a calendar file (like .ics) which imports the event into the whichever calendar app the smartphone is using.

I know this is possible in the Facebook desktop webrowser version where you can "Export event" and either download an ics or email a link to yourself to add to your calendar.  Something like this in Frost for mobile would be nice.

**Comment by AllanWang** [comment]
It's a good idea, but it's probably too much to parse and maintain. Frost might be able to get the title while it's constant, but without locations, dates, etc, it's not a very useful event. I feel like Facebook used to or might still have actual integrations where you can export your full facebook calendar and sync with android calendar
