### ISSUE TITLE
direct not working

### ISSUE THREAD

**Issue by jlslinux** [AllanWang/Frost-for-Facebook#1785]
- [ ] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
Direct, live video not working

**Details (please provide at least the app version):**
 - App Version: 3.0.0
 - Device: Samsung j3 2016
 - Android Version: 7.1.2 (lineage is 14.1)

**Comment by AllanWang** [comment]
Probably not supported and I don't intend on requesting camera permissions anyways
