### ISSUE TITLE
Multiple Account doesn't work 

### ISSUE THREAD

**Issue by MustafaMemisogM** [AllanWang/Frost-for-Facebook#1792]
Hi, the feature multiple accounts doesn't work. If switch the account both account is sign out. 

 - App Version:Version 3.0.0
 - Android Version:10 QKQ1.190910.002

**Comment by MostWanted-Hub** [comment]
Same problem on JoyUI  / miUi , I can't stay logged in

**Comment by AllanWang** [comment]
Duplicate of #1753
