### ISSUE TITLE
File chooser not found

### ISSUE THREAD

**Issue by syphyr** [AllanWang/Frost-for-Facebook#1806]
- [x ] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

Unable to select photos to upload.

When attempting to upload photos, frost gives message "File chooser not found".

**Details (please provide at least the app version):**
 - App Version: 3.1.0
 - Device: T813
 - Android Version: cm-14.1

**Comment by syphyr** [comment]
I am unable to find any relevant errors in logcat for this issue, but it appears that "Hilt Injection" from this 39db7f4c3d7b8f3d68ef1a8881b69624b721f6c6 commit is the cause.

**Comment by KyleBroflowski** [comment]
I too have noticed this bug, though needed storage permissions were already given, the same error appears

**Comment by gurski** [comment]
I'm seeing both this and "Cannot resolve browser" in 3.1.0 across a Pixel 4, a Pixel 5, and a couple Fire HD 8 tablets.

**Comment by AllanWang** [comment]
To everyone affected, please see #1819
