### ISSUE TITLE
Can't play any videos on latest version

### ISSUE THREAD

**Issue by MichalisSak** [AllanWang/Frost-for-Facebook#1808]
- I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
Can't play any videos

**To Reproduce**
Steps to reproduce the behaviour:
1. Find a video on your timeline
2. Click on play button
3. Nothing happens

**Details (please provide at least the app version):**
 - App Version: 3.1.0
 - Device: Xiaomi Mi 9T Pro
 - Android Version: 11

**Comment by GibberMeJenks** [comment]
I am experiencing this issue as well

**Comment by glocalglocal** [comment]
Same here. It's fixed when I disable PIP in the Frost settings.

**Comment by Stanley00** [comment]
I'm also having the same issue, with the same phone.

**Comment by autogris** [comment]
Same issue here. I had to disable PIP to get videos again.

**Comment by AllanWang** [comment]
To everyone affected, please see #1819

**Comment by toas-koas** [comment]
In Version 3.1.0 it's only working when I open the post itself, or when I disable PIP.
In Version 3.1.0-9-355d8ae-test it's working perfect.
