### ISSUE TITLE
Feature: option to only check/sync when app is open

### ISSUE THREAD

**Issue by regulator-g** [AllanWang/Frost-for-Facebook#1809]
**Describe the feature**
Hey, 
I try to use Facebook as little as possible and before someone messages me I'd like it to say inactive for 5+ days

I assume under notification frequency that is where the app checks for messages etc, can you please add an option to only check when the feed is manually refreshed?

thanks!

**Comment by AllanWang** [comment]
If you only need notifications when the app is opened, do you really need notifications? Why not use the notifications tab at that point?

While frequencies beyond what is given is a valid request, I'm not super interested in adding longer intervals. If possible, I would make the notifications near immediate at all time, and polling intervals is really to reduce data consumption than anything else. If this is highly requested I can merge it, though it's also just as easy for you to change the mapped constants and maintain your own build if you'd like. The github action ci will even build the app for you.

**Comment by regulator-g** [comment]
Hey @AllanWang Thanks for the reply,

Just putting notifications to the side, what I would like is an option where the app will not make any contact to Facebook unless opened and manually refreshed

I was assuming this could be achieved by changing the notification frequency..

I think it would be a popular feature as most Frost users want to use Facebook with as little tracking/data mining as possible

**Comment by AllanWang** [comment]
You can disable notifications (general and messages), which is the only thing Frost runs as a service while the app isn't in the foreground. Closing as I believe that's enough
