### ISSUE TITLE
Open links in default app not working

### ISSUE THREAD

**Issue by GibberMeJenks** [AllanWang/Frost-for-Facebook#1812]
**Describe the bug**
All links open in Frost web overlay despite setting in to open in default app within the behavior settings

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'settings', 'behaviour', and select _open links in default app_
2. Click on any link
3. Link will open in Frost web overlay and not default app

**Details (please provide at least the app version):**
 - App Version: v3.1.0
 - Device: Pixel 5a
 - Android Version: 11

**Comment by samo1** [comment]
I have the same problem, just to add that when I select 'Open in browser', I got a toast message Cannot resolve browser.

**Comment by AllanWang** [comment]
Did it work before? Did you happen to uninstall your chromium webview, update your android OS, or anything?

Might be a permission thing with new android updates so I'll see

**Comment by GibberMeJenks** [comment]
> 
> 
> Did it work before? Did you happen to uninstall your chromium webview, update your android OS, or anything?
> 
> Might be a permission thing with new android updates so I'll see

Thanks for your reply. It did work fine in the previous release. Nothing was changed or modified with chromium webview, the android OS, or anything else.

I reverted back to 3.0.0 to test with the same settings and it is working fine in the previous release. As @samo1 also mentioned, I also get a toast message mentioning 'cannot resolve browser'.

**Comment by AllanWang** [comment]
To everyone affected, please see #1819

**Comment by AllanWang** [comment]
Actually haven't verified yet so I'll keep opened. Test build isn't linked in the bug tracker yet and apparently it causes bugs (#1821)

**Comment by gburjan** [comment]
This feature is also broken on my device since the upgrade to 3.1.0. (Samsung Galaxy A50, Android 11) "Open Links in Default" is checked in the settings, but every link is opened in "Frost web" instead of my preferred browser. This setting worked fine before the upgrade.
