### ISSUE TITLE
Unable to slide between stories.

### ISSUE THREAD

**Issue by farhun1** [AllanWang/Frost-for-Facebook#1814]
- [x] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
When you want see the stories from your friend and want to slide/swipe accross them to see the overview it doesn't allow to slide/swipe across them. The windows changes to message.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the app
2. slide/swipe accross the stories
3. It will go in the message option rather than to the next story.

**Details (please provide at least the app version):**
 - App Version: 3.1.0
 - Device: Redmi Note 7
 - Android Version: Android 11

**Comment by AllanWang** [comment]
Untested as I don't have stories in my dev account, but you can try with https://github.com/AllanWang/Frost-for-Facebook-APK-Builder/releases/tag/v3008

**Comment by AllanWang** [comment]
To everyone affected, please see #1819
