### ISSUE TITLE
v3.1.0 Bug Tracker (Beta Test)

### ISSUE THREAD

**Issue by AllanWang** [AllanWang/Frost-for-Facebook#1819]
This is a tracker for the main bugs in 3.1.0. Once they are verified, I'll create a new release: 

#1806, #1808, #1812, #1814

Test build (subject to change): https://github.com/AllanWang/Frost-for-Facebook-APK-Builder/releases/tag/v3011

Test releases do not affect F-Droid installations; they are a separate app. If the bug is fixed for you, feel free to comment. If not, create a new bug.

**Comment by MichalisSak** [comment]
#1808 Videos and PiP are both fixed with this test build.

**Comment by syphyr** [comment]
"File Chooser Not Found" error is now fixed. Thanks.

**Comment by Stanley00** [comment]
I can confirm #1808 fixed with this test release

**Comment by DudeVirus** [comment]
Yes the video issue for fixed in the test.
