### ISSUE TITLE
Market place is not loading

### ISSUE THREAD

**Issue by resudroid** [AllanWang/Frost-for-Facebook#1820]
- [x] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
Market place is not loading, its a blank page
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'frost'
2. Click on 'Marketplace'
3. Scroll down to 'cannot'
4. See error, does not load

**Details (please provide at least the app version):**
 - App Version: 3.1.0-9-355d8ae-test
 - Device:  Samsung s10+
 - Android Version: android 11, oneui 3.1
 - screenshot below.
![Screenshot_20210926-091233_Frost Test](https://user-images.githubusercontent.com/89598257/134811741-762c3931-8e43-4a1d-888a-e4225b194f31.jpg)

**Comment by syphyr** [comment]
I just tested frost-v3.1.0-8-geb9fc5c6 and marketplace is working.  The version you mention (3.1.0-9-355d8ae-test) seems to be different.

**Comment by AllanWang** [comment]
it's probably location specific and not build specific. Blank loads happen from time to time but they can't be replicated easily; easy way to verify is to go back to a working build and seeing if it's reproducible.

**Comment by AllanWang** [comment]
On this note, I'm also curious if you opened up the link in your browser and tested. If it's that reproducible, then filing a log would be good.
