### ISSUE TITLE
all pages are blank white

### ISSUE THREAD

**Issue by resudroid** [AllanWang/Frost-for-Facebook#1821]
- [x] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
all pages dont load now, as seen in screen shot notifications is blank as well.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'frost'
2. Click on 'any page'
3. Scroll down to 'n/a'

**Details (please provide at least the app version):**
 - App Version: 3.1.0-355d8ae-test
 - Device:  s10+
 - Android Version: Android 11 oneui 3.1
![Screenshot_20210926-130124_Frost Test](https://user-images.githubusercontent.com/89598257/134819073-fa43180a-2f06-4100-9f10-f39ba04b4864.jpg)

**Comment by syphyr** [comment]
Try frost-v3.1.0-8-geb9fc5c6

**Comment by AllanWang** [comment]
This happens when you restart/refresh the tabs too? I usually don't take bug reports from test builds unless I've linked them, but that one should still be working. Frost/Facebook can be slow at times which is why I'm looking into #1807

**Comment by AllanWang** [comment]
Not reproducible
