### ISSUE TITLE
Cannot resolve browser - everytime I want to open a link

### ISSUE THREAD

**Issue by PhiilFen** [AllanWang/Frost-for-Facebook#1829]
- [x] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
Every time I open a link in the integrated browser and then click on the three dots "open in other browser", the error "cannot resolve browser" appears.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open any link
2. Click on the three dots 
3. Scroll down to 'Open in browser '

**Details (please provide at least the app version):**
 - App Version: 3.1.0
 - Device: Google Pixel 5
 - Android Version: 11

**Logs/Screenshots:**

**Comment by sliminat0r** [comment]
Can confirm

**Comment by AllanWang** [comment]
Duplicate of #1812
