### ISSUE TITLE
Video stories won't open

### ISSUE THREAD

**Issue by carlosnewmusic** [AllanWang/Frost-for-Facebook#1833]
- [x] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
Stories that contain video cannot be opened even if you give the play

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to feed
2. Click on story
3. View a story that contains video
4. Hit the play
4. Not seen, the video does not open

**Details (please provide at least the app version):**
 - App Version: 3.1.0
 - Device: Sony Xperia XA2
 - Android Version: 9

**Comment by AllanWang** [comment]
Duplicate of #1808
