### ISSUE TITLE
Can't log into Facebook using Frost

### ISSUE THREAD

**Issue by hehates** [AllanWang/Frost-for-Facebook#1837]
- [ ] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
Encountering "logging into Facebook from embedded browser is disabled" when trying to login using Frost

**To Reproduce**
Steps to reproduce the behaviour

4. See [error](url)

**Details (please provide at least the app version):**
 - App Version: 3.0.0 and 3.1.1
 - Device: BB Key 2
 - Android Version: 8.1

**Logs/Screenshots:**

![Screenshot_20211011-071542](https://user-images.githubusercontent.com/73746791/136807269-46616612-312e-4ac2-a838-e9d8719cda9d.png)
:

**Comment by AllanWang** [comment]
If you're using 2fa, you might have to accept the new device through your desktop. You can look up other issues around sign in here, but it's not a reproducible/fixable issue

**Comment by jokay** [comment]
Disabled 2FA and reenabled it after login did work :+1:
