### ISSUE TITLE
Disable news feed completely

### ISSUE THREAD

**Issue by xAdamQ** [AllanWang/Frost-for-Facebook#1838]
The main reason I installed this app was to avoid engagement with the timeline, but it was surprising that I couldn't find a way to disable news feed. See how many installs for news feed killer extensions on web browsers, it is essential.
Thanks.

**Comment by AllanWang** [comment]
you can remove it from your tabs through settings > appearance > main activity tabs.

drag and drop to the top 4 entries for what you'll see in the main activity
