### ISSUE TITLE
unwanted refresh when bluetooth input device connects

### ISSUE THREAD

**Issue by mark-orion** [AllanWang/Frost-for-Facebook#1839]
- [ x] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
The moment my bluetooth keyboard connects as an input device, a refresh is triggered. This is highly annoying. I often use the touch keyboard for standard simple replies / posts, but then come across something that requires a more detailed response. I enablle the Bluetooth keyboard and - bang - the post, including my half-finished text, is gone.

**To Reproduce**
1. Start writing a post or comment.
2. Either switch your already paired BT keyboard on, or enable BT with the keyboard already switched on.
3. Frost refreshes and the post is gone.

**Details (please provide at least the app version):**
 - App Version: 3.1.1
 - Device: Samsung Galaxy Tab S2
 - Android Version: 7.0

**Logs/Screenshots:**

**Comment by AllanWang** [comment]
https://stackoverflow.com/questions/23311748/my-webview-reloads-when-bluetooth-disconnects-or-reconnects

should be a quick fix

---

https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/AndroidManifest.xml#L78

what firefox uses
