### ISSUE TITLE
Unable to see Events page for a Group

### ISSUE THREAD

**Issue by vortexmak** [AllanWang/Frost-for-Facebook#1840]
- [ ] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
When I go to a groups page, the next upcoming event is listed but there is no way to go the list of Events for a group

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Groups'
2. Click on 'Any Group you are a member of'
3. Look for events tab
4. No events tba

**Details (please provide at least the app version):**
 - App Version:3.0.0
 - Device: Samsung Galaxy S9 
 - Android Version: Oreo 8

**Logs/Screenshots:**

**Comment by AllanWang** [comment]
Frost likely doesn't hide that information, so it could be that it isn't in m.fb.com; if it's available, works on your mobile browser, but fails in Frost, then that would be a Frost bug
