### ISSUE TITLE
Mastodon account for this project

### ISSUE THREAD

**Issue by linux-lukas** [AllanWang/Frost-for-Facebook#1842]
Would a Mastodon account for this project be possible?

**Comment by AllanWang** [comment]
Not sure what this means, but I presume Mastodon isn't related to Facebook?

**Comment by linux-lukas** [comment]
> Not sure what this means, but I presume Mastodon isn't related to Facebook?

Yes and no. Mastodon is also a social network, but a free and open source one - functionally it is most comparable to Twitter.

**Comment by AllanWang** [comment]
If you are asking to make a client for Mastodon, that sounds like a different project; Frost's goal is to add some ui adjustments to Facebook, and can't add additional significant features

**Comment by linux-lukas** [comment]
It seems to me that I have expressed myself in a misleading way. That is definitely my mistake. Sorry for that.

I was talking about a Mastodon account for this project "Frost by Facebook".

**Comment by linux-lukas** [comment]
😅😅😅

**Comment by AllanWang** [comment]
If this is referring to a new account for Frost on a different platform, I unfortunately don't have time to maintain it. GitHub is my only official means of communication going forward, and previous ones (Slack, XDA, Telegram at one point I think) are deprecated
