### ISSUE TITLE
Increasing text size will crop Title text of posts

### ISSUE THREAD

**Issue by LazieWouters** [AllanWang/Frost-for-Facebook#1850]
- [ ] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
Post titles are truncated when the text size is a bit large.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Settings'
2. Click on 'Appearence'
3. Scroll down to 'Web text scale'
4. Increase the text size (eg: 140 or more)
5. See error (image below)

**Details (please provide at least the app version):**
 - App Version: 3.1.1
 - Device: Moto G6 Plus
 - Android Version: 9

![Untitled](https://user-images.githubusercontent.com/77227512/141682766-591144b0-8011-459b-af9d-5d366818fa58.png)

**Comment by AllanWang** [comment]
This can't be fixed (at least non trivially). Facebook likely hardcodes many aspects of their layouts, which can't be updated without manually addressing each element style. Font size change is a feature in webviews, and a small feature addition to Frost.
