### ISSUE TITLE
Another Dark theme

### ISSUE THREAD

**Issue by LazieWouters** [AllanWang/Frost-for-Facebook#1851]
The current dark theme displays the top in a blue tone.
Would it be possible to create a second dark theme where the top has the same shade of dark?
The AMOLED theme does this but it is very black so I would like a theme with the behavior of the AMOLED theme but with the dark theme tone.

The image below shows the current dark theme and roughly what the new theme would look like.

Edit: I tried using the custom theme option, and I adjusted the colors manually until I got this result. However, the custom theme does not correctly display the look of the comments, as they always have a white background.

![Untitled](https://user-images.githubusercontent.com/77227512/141683455-4f5ca4d3-63ff-4da8-bac2-43ab1ff5d675.png)

**Comment by AllanWang** [comment]
You can do this already with custom themes. You can match the amoled colors and replace black with a grey value:

https://github.com/AllanWang/Frost-for-Facebook/blob/bf55dbf9b46cd8826987ee6e556307e24f3d46cc/app/src/main/kotlin/com/pitchedapps/frost/enums/Theme.kt#L72-L80

this is the value order

https://github.com/AllanWang/Frost-for-Facebook/blob/bf55dbf9b46cd8826987ee6e556307e24f3d46cc/app/src/main/kotlin/com/pitchedapps/frost/enums/Theme.kt#L32-L40

**Comment by AllanWang** [comment]
Can you take a screenshot of your custom theme?
