### ISSUE TITLE
Adding download button on post 

### ISSUE THREAD

**Issue by lennardjamie5** [AllanWang/Frost-for-Facebook#1859]
Low priority:
When you click on a post and have the option to "copy link" "share" "open in browser" would it be possible to include a "download" which just downloads the media of the post?

Thank you.

**Comment by lennardjamie5** [comment]
I would just add it myself but I am unsure as to how you go from a formatted fb url to an actual download link

**Comment by AllanWang** [comment]
To download media, you can long press an image. Alternatively, go through facebooks normal flow by clicking the image, and viewing the full size.

**Comment by lennardjamie5** [comment]
I was unaware of the long press, thank you :)
