### ISSUE TITLE
Ability to disable swipe down to update

### ISSUE THREAD

**Issue by dpriskorn** [AllanWang/Frost-for-Facebook#1864]
Currently the swipe down action is on by default and I cannot find a setting to disable it.
Could we have a button or menu option also and make the gesture optional?

The reason I ask is that I sometimes write and then loose everything because of a gesture...

**Comment by AllanWang** [comment]
Could potentially add a setting. 
Tabs can still be clicked for refresh, and I'll likely add a menu option for the separate windows if swipe is disabled.

If there's a specific screen that's a problem, you could let me know and I could potentially disable it for that screen only

**Comment by dpriskorn** [comment]
I lose my stuff when adding a new post and accidentally swiping down.
