### ISSUE TITLE
Facebook intentionally slows down Frost

### ISSUE THREAD

**Issue by ishmumx** [AllanWang/Frost-for-Facebook#1870]
Facebook definitely knows what frost is and are actively trying to sabotage it.

I tried clicking stories and expanding comment sections, ALL of it loads 5 to 6 seconds longer than my chrome facebook. 

Fuck Mark Z

**Comment by ruralTom** [comment]
Without evidence this is tin foil hat territory, and a gut feeling isn't evidence. 
Can you think of other reasons why this slow down would occur?

**Comment by ishmumx** [comment]
> Without evidence this is tin foil hat territory, and a gut feeling isn't evidence. Can you think of other reasons why this slow down would occur?

Yes for sure it is tinfoil hat territory, but hear me out! I am using a recent high end Samsung phone at the moment. When I click on a group's meme comment section, it opens a new tab page and this is where the slowdown starts.  It takes a while to load comments and when you go back and cycle between notification messages and home it is also excruciatingly slope.

 I personally feel that Facebook knows frost is being used and they are employing mechanisms to slow our usage down so that we switch to the Chrome browser.

**Comment by ishmumx** [comment]
Previously in this support forum I also saw people posting about Facebook blocking their accounts because of frost.

**Comment by creativetrendsapps** [comment]
🤣

**Comment by biennvops** [comment]
That's weird, mine works very well with only a 1 - 2 seconds delay in comment section due to it being loaded in another WebView, which is basically the same with the normal Facebook app thanks to the huge amount of animations nonsense there.
But after all, it's a **WebView** wrapper, not a **native** app, so you should expect some delay (but not that long like yours)...

**Comment by ishmumx** [comment]
I'm closing this Lol
