### ISSUE TITLE
Option to hide "Suggested for you" posts

### ISSUE THREAD

**Issue by nicobustillos** [AllanWang/Frost-for-Facebook#1892]
You should only see posts from people/groups you chose to follow. Not the ones shoved to you by FB. 

The "FB purity" extension for chrome does a great job at this.

**Comment by AllanWang** [comment]
ff2f1b84128085de50193438832443f16ad3e199

Not sure if it's that simple or works across all locales. The recommended posts are literally tagged as such on mobile
