### ISSUE TITLE
Reactions to comments don't save

### ISSUE THREAD

**Issue by Bennett-69** [AllanWang/Frost-for-Facebook#1898]
- [X] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**Describe the bug**
"Likes" (and other reactions) on comments don't save.
It's still possible to "Like" a top-level post, but trying to do so on comments within a post doesn't work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any post with comments
2. Click on "Like" to react to a comment
3. Note that the reaction is not saved

**Details (please provide at least the app version):**
 - App Version: 3.1.2
 - Device: OnePlus 7T
 - Android Version: 11 (Oxygen OS 11.0.7.1.HD65AA)

**Logs/Screenshots:**
N/A

**Comment by gbakeman** [comment]
I just came here to report the same issue, using version 3.1.2 on a Samsung Galaxy S9 (?) I attempted clearing data/cache but with no success.

**Comment by ikanakova** [comment]
I have same issue on Nokia 6.1 (Android 10).

**Comment by SearchingForDottedLines** [comment]
I have the same behaviour as above on Frost 3.1.2, Samsung Galaxy A50, Android 11.

Looks to be related to the m. and touch. sites as I get the same behaviour on Firefox desktop and Firefox mobile.

Does not appear to be account related as I can like comments on my desktop on Firefox via the full FB site.

The same issue also exists:
- on my phone using FaceSlim (touch mode enabled and disabled)
- on my phone using m.facebook.com (Firefox)
- on my phone using touch.facebook.com (Firefox)
- on my desktop using m.facebook.com (Firefox)
- on my desktop using touch.facebook.com (Firefox)

The issue does not exist :
- on my desktop using www.facebook.com (Firefox)

**Comment by SearchingForDottedLines** [comment]
@Bennett-69 what mobile browser were you using when it worked via https://touch.facebook.com/ ?

**Comment by Bennett-69** [comment]
> @Bennett-69 what mobile browser were you using when it worked via https://touch.facebook.com/ ?

Yeah, I'm thinking what you're thinking: It works fine in Chrome. Maybe fixable via a change in User Agent?

Google Chrome | 102.0.5005.78 (Official Build) (64-bit)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Android 11; HD1905 Build/RKQ1.201022.002
Google Play services | SDK=221602000; Installed=221514037; Access=1p
JavaScript | V8 10.2.154.5
User Agent | Mozilla/5.0 (Linux; Android 11; HD1905) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Mobile Safari/537.36

I was just about to check a couple of other mobile browsers like Firefox to confirm, I'll get back to you here with my results.

**Comment by Bennett-69** [comment]
@SearchingForDottedLines Okay, I confirmed my suspicions about the user agent. By default, Firefox for Android fails as you described:

101.1.1 (Build #2015882827), 8092b4e74+
AC: 101.0.10, db7e8a692a
GV: 101.0-20220526203855
AS: 91.1.2

Here's its very basic default user agent:

User-Agent: Mozilla/5.0 (Android 11; Mobile; rv:101.0) Gecko/101.0 Firefox/101.0

I also confirmed that touch.facebook.com works correctly in Kiwi Browser (an open source Chromium-based alternative to Chrome). Finally, I downloaded Firefox Nightly to gain access to the about:config options, so I could customize the user agent in Firefox:

general.useragent.override
Mozilla/5.0 (Linux; Android 11; HD1905) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Mobile Safari/537.36

Upon setting it to that same user agent as used by Chrome, it works.

Hopefully this helps narrow things down, at least.

**Comment by Bennett-69** [comment]
FYI, I just submitted this bug report to the black hole of Facebook Support. The rest of you might want to do something similar, just to hopefully raise visibility on this issue.

https://m.facebook.com/bugnub/

"Using either touch.facebook.com or m.facebook.com in Firefox for Android, it's no longer possible to react to comments on posts (the reaction doesn't save). This seems to have broken about a week ago."

"The problem isn't present in Chrome, and doesn't affect top-level items like posts, photos, etc. - just the comments below them."

**Comment by Bennett-69** [comment]
Well, it looks like my bug report to Facebook themselves might have actually done some good. Is everyone else seeing the issue resolved now, too? If so, I'll go ahead and close this as fixed on the server side.

**Comment by gbakeman** [comment]
Can confirm, it's working for me! Thank you for your effort!

**Comment by SearchingForDottedLines** [comment]
Can confirm also working for me - excellent work!

**Comment by Bennett-69** [comment]
Okay, closing this as apparently fixed on Facebook's side. Thanks for your help isolating the issue!
