### ISSUE TITLE
Frost not loading fb pages anymore

### ISSUE THREAD

**Issue by montvid** [AllanWang/Frost-for-Facebook#1918]
Frost not loading fb pages anymore. None of the Frost menu links work. Frost 3.2,  3.1 do not work, reinstall does not help.
![Screenshot_2022-10-16-10-59-41-454_com pitchedapps frost](https://user-images.githubusercontent.com/23270059/196024895-58afba83-391e-4ab0-8afb-6cf7ccca8817.jpg)

**Comment by dikkedikkie** [comment]
Same problem here since v3.2.0

**Comment by dikkedikkie** [comment]
Uninstalled v 3.2.0. Reinstalled it.
No fun. At the login page it says" error connection timed out: https://m.facebook.com/login

Uninstalled 3.2.0 and installed 3.1.1. Same problem when trying to contact login page.
Error connection timed out for page: https://m.facebook.com/login.

I visit https://m.facebook.com/login with my browser on my phone. Works like it should.

So Frost gives me a timeout while my browser can contact the webpage without any issues.

**Comment by dikkedikkie** [comment]
Update,

installed latest  - test.
Everything works again.

**Comment by digitalTranshumant** [comment]
Getting the same error. I've tried with Slimsocial For Facebook, and got the same error too. 
@dikkedikkie I'm assuming that the latest is 3.2.0 , true?

**Comment by agodlydeciple** [comment]
I am having the same issue. 

I have cleared the cache and cleared the app data. I have tried everything short of uninstalling/reinstalling. 

Has uninstalling/reinstalling the app fixed it for anyone else other than @dikkedikkie?

**Comment by dikkedikkie** [comment]
Not working anymore. Problem is back

**Comment by montvid** [comment]
Working. Love the app. No ads yay!

**Comment by dikkedikkie** [comment]
Uuh closed?
Problem is not solved......

**Comment by Kastrel7** [comment]
Have the same problem

Shouldn't be closed

**Comment by ArttuH5N1** [comment]
I deleted cache and user data, logged back in and it started working.
