### ISSUE TITLE
Version 3.2.0 Notifications blocked, 3.1.2 works fine

### ISSUE THREAD

**Issue by rEd2k** [AllanWang/Frost-for-Facebook#1935]
Hello,

Brand new Samsung S23 Ultra, and the notifications don't work with Frost 3.2.0, though earlier versions work fine. 

Navigate to Settings->Notifications->Customize Notification Channels

Message reads "All notifications for this app are blocked"

Notifications switch is greyed out.

One UI verion 5.1
Android 13, build Number:  TP1A.220624.014.S918WVLU1AWBE

Maybe this issue is just because this new phone doesn't like the 3.2.0 version, but earlier versions work, so I am inclined to think it could be a bug.

**Comment by rEd2k** [comment]
Sorry, I did not see someone else reported this already.

**Comment by rmullin7286** [comment]
I can confirm on my device that notifications are blocked in 3.2.0, but work in 3.1.2. I'm on a samsung galaxy s21 running Android 13
