### ISSUE TITLE
[BUG] Events tab "broken"

### ISSUE THREAD

**Issue by HarriBuh** [AllanWang/Frost-for-Facebook#1956]
- [ ✓] I have verified that the bug does not occur in my mobile browser (at https://touch.facebook.com/)

**To Reproduce**
1. Open Frost
2. Change to events tab
3. Get error message

**Details (please provide at least the app version):**
 - App Version: 3.2.0
 - Device: Google Pixel 7
 - Android Version: 13

**Logs/Screenshots:**
![markup_1000013860](https://github.com/AllanWang/Frost-for-Facebook/assets/123186113/40e49dd1-4f2b-4ac9-874b-755116f08eae)

This just started a few days ago, and didn't fix itself so far.

**Comment by HarriBuh** [comment]
![obscura1688222524297](https://github.com/AllanWang/Frost-for-Facebook/assets/123186113/b5bd43bf-00e9-4275-af18-7596106d604e)

**Comment by HarriBuh** [comment]
Still broken, push.

**Comment by osowiecki** [comment]
Doesn't work in Poland as well.
