### ISSUE TITLE
Connectivity.java line 86

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#205]
#### in com.github.pwittchen.reactivenetwork.library.rx2.Connectivity.getNetworkInfo

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/599a0fd4be077a4dcc5dfab3?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/599a0fd4be077a4dcc5dfab3?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Null iterator through `getActiveNetworkInfo`.

[Follow up issue](https://github.com/pwittchen/ReactiveNetwork/issues/209)

**Comment by AllanWang** [comment]
Lib updated to 0.12.0
