### ISSUE TITLE
Notifications.kt line 74

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#206]
#### in com.pitchedapps.frost.settings.NotificationsKt$getNotificationPrefs$1$13$2.invoke

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/599a1a8cbe077a4dcc5e406c?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/599a1a8cbe077a4dcc5e406c?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Fixed in 684086d
