### ISSUE TITLE
ThreadedRenderer.java

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#215]
#### in android.view.ThreadedRenderer.nDeleteProxy

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/599b522cbe077a4dcc698fb5?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/599b522cbe077a4dcc698fb5?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Concurrent timeout

See

https://stackoverflow.com/questions/24021609/how-to-handle-java-util-concurrent-timeoutexception-android-os-binderproxy-fin

**Comment by AllanWang** [comment]
Notable bug (11 crashes). May be related to headless webviews, so this should be fixed once those are replaced
