### ISSUE TITLE
SwipeBackHelper.kt line 20

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#217]
#### in ca.allanwang.kau.swipe.SwipeBackHelper.get

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/599bf054be077a4dcc6eb560?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/599bf054be077a4dcc6eb560?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Old build
