### ISSUE TITLE
MediaUtils.kt line 45

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#248]
#### in ca.allanwang.kau.mediapicker.MediaUtilsKt.finish

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59a96969be077a4dccf44aa9?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59a96969be077a4dccf44aa9?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Error report

`Non-fatal Exception: java.io.IOException: open failed: ENOENT (No such file or directory)`
