### ISSUE TITLE
SimpleTarget.java line 60

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#250]
#### in com.bumptech.glide.request.target.SimpleTarget.getSize

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59aabcedbe077a4dcc0193c5?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59aabcedbe077a4dcc0193c5?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Notification image has width 0
