### ISSUE TITLE
MediaPickerActivity.kt line 23

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#252]
#### in com.pitchedapps.frost.activities.MediaPickerActivityKt$actions$1.createUri

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59ab0513be077a4dcc04a23c?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59ab0513be077a4dcc04a23c?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Fotos

**Comment by AllanWang** [comment]
Moved to https://github.com/AllanWang/KAU/issues/71
