### ISSUE TITLE
DefaultRvAdapter.java line 67

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#255]
#### in com.afollestad.materialdialogs.DefaultRvAdapter.onBindViewHolder

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59ad7ae8be077a4dcc1ac02a?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59ad7ae8be077a4dcc1ac02a?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
IAB initialized

`Property: rotation is not supported for FullPath`
