### ISSUE TITLE
MarshmallowNetworkObservingStrategy.java line 60

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#264]
#### in com.github.pwittchen.reactivenetwork.library.rx2.network.observing.strategy.MarshmallowNetworkObservingStrategy.observeNetworkConnectivity

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59b4bfaebe077a4dcc63b207?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59b4bfaebe077a4dcc63b207?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
No access to NETWORK_ACCESS_STATE
