### ISSUE TITLE
[Enhancement] Ability to share with Facebook from other apps (Intent)

### ISSUE THREAD

**Issue by chiraag-nataraj** [AllanWang/Frost-for-Facebook#266]
The official Facebook app installs an intent to allow sharing from other apps. It would be great if we could have this in Frost as well 🙂

**Comment by AllanWang** [comment]
This is a bit difficult for third party apps since we are a web wrapper. Facebook does have a Graph API, but I've avoided it based on its heavy restrictions.

The only way to create a similar sharing option is to essentially load the webview in the background and click the buttons ourselves automatically. I will consider that once I've finished with the current tasks

**Comment by chiraag-nataraj** [comment]
There's actually a URL-based way to share e.g. a link. The only thing needed there is an app ID - you then can open a URL like: `https://www.facebook.com/dialog/share?app_id=[APPID]&href=[URL]` in the app and it will allow you to share the link.

**Comment by AllanWang** [comment]
Yeah, and the app id is taken from the graph API. I may look into this, but as I've said I'm a bit hesitant on using it given that it could be revoked at any instance. Facebook has tight applications as to which apps can use what apis, and third party wrappers don't seem to be one of the favoured ones

**Comment by AllanWang** [comment]
If there's a way without an id I'll be happy to look into it

**Comment by chiraag-nataraj** [comment]
Ah I see! You _could_ theoretically use their dummy "developer" app id: `app_id=145634995501895` although I'm sure they wouldn't be too happy about that... 🙃

**Comment by chiraag-nataraj** [comment]
Hey look, this works!
`https://www.facebook.com/sharer/sharer.php?u=http://www.gmanetwork.com/news/` (just as an example).

**Comment by AllanWang** [comment]
Nice For my future reference:

https://joshuawinn.com/facebooks-sharer-php-longer-deprecated-2014/

**Comment by AllanWang** [comment]
@chiraag-nataraj 

Added link sharing.

Test build:

https://github.com/AllanWang/Frost-for-Facebook-APK-Builder/releases/tag/v646
