### ISSUE TITLE
New message bug

### ISSUE THREAD

**Issue by Crymito** [AllanWang/Frost-for-Facebook#272]
If you search for a person and in his page you want to send a message a error page is showing. Solve it please

**Comment by AllanWang** [comment]
Please try test [v625](https://github.com/AllanWang/Frost-for-Facebook-APK-Builder/releases/tag/v625).

There are still slight theming issues but you should be able to send messages. The theme will be updated upon beta release

**Comment by AllanWang** [comment]
If it still doesn't load, please send me a screenshot with how you got there, and I will reopen this
