### ISSUE TITLE
InputChannel.java

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#281]
#### in android.view.InputChannel.nativeReadFromParcel

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59b8b42bbe077a4dcc8a2912?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59b8b42bbe077a4dcc8a2912?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
May be a sound pool error?

https://stackoverflow.com/questions/25132509/java-lang-runtimeexception-could-not-read-input-channel-file-descriptors-from-p

This has only occurred once on a Samsung Galaxy J5
