### ISSUE TITLE
Can't message

### ISSUE THREAD

**Issue by thePeterG** [AllanWang/Frost-for-Facebook#285]

**Comment by AllanWang** [comment]
Can you give more detail? Frost version? Phone info? Can't message from where?

There are known issues of messenger showing the banner to get the official app if you click send message from the profile. I need to work on that.

**Comment by thePeterG** [comment]
@AllanWang Sorry. Sent from mobile and hit send before I could add details.

Yesterday, I tried to respond to messages in the latest version Frost from the Play store. It was redirecting me to the notification saying I needed to download Messenger.

Oddly enough, I restarted my phone and it's working. I'm using a Moto G Android 7.1.2 running Lineage OS 14.1.

**Comment by AllanWang** [comment]
Will be fixed under #238

**Comment by thePeterG** [comment]
@AllanWang Wanted to update this. I found the problem. It sends me to the Messenger download if I try to reply to messages sent to a Page and not my personal profile. I'm able to respond to messages sent directly to me.

**Comment by AllanWang** [comment]
There is an issue with messages if the first page launched in the overlay is not a message and you end up navigating to the message pane (eg clicking message after visiting someone's profile). This is related to Facebook disabling im on mobile and I'm working on it now
