### ISSUE TITLE
RxJavaPlugins.java line 349

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#287]
#### in io.reactivex.plugins.RxJavaPlugins.onError

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59bc42eebe077a4dccb138e3?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59bc42eebe077a4dccb138e3?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available :/
