### ISSUE TITLE
View.java line 17726

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#288]
#### in android.view.View.invalidateDrawable

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59bc42f8be077a4dccb13944?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59bc42f8be077a4dccb13944?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
OOM for a single user
