### ISSUE TITLE
AccessibilityNodeInfoCompat.java line 2082

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#301]
#### in android.support.v4.view.accessibility.AccessibilityNodeInfoCompat.wrap

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59be03b6be077a4dccc1a7d9?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59be03b6be077a4dccc1a7d9?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
single OOM
