### ISSUE TITLE
InkPageIndicator.java line 587

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#305]
#### in ca.allanwang.kau.ui.widgets.InkPageIndicator.setSelectedPage

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59be653abe077a4dccc58900?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59be653abe077a4dccc58900?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
See https://github.com/nickbutcher/plaid/issues/215

**Comment by AllanWang** [comment]
Issue moved to [AllanWang/KAU #79](https://github.com/AllanWang/KAU/issues/79) via [**ZenHub**](https://www.zenhub.com/)
