### ISSUE TITLE
ActivityUtils.kt line 40

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#330]
#### in ca.allanwang.kau.utils.ActivityUtilsKt.startActivityForResult

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59c73a8ebe077a4dcc2570a4?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59c73a8ebe077a4dcc2570a4?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Fixed in https://github.com/AllanWang/KAU/commit/6f12eb7c14c904dbb5cfc55624caac95c3439e61
