### ISSUE TITLE
MotionEvent.java

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#342]
#### in android.view.MotionEvent.nativeGetAxisValue

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59ca616dbe077a4dcc46e486?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59ca616dbe077a4dcc46e486?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Issue moved to [AllanWang/KAU #72](https://github.com/AllanWang/KAU/issues/72) via [**ZenHub**](https://www.zenhub.com/)
