### ISSUE TITLE
Progressions.kt line 99

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#345]
#### in kotlin.ranges.IntProgression.

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59cb19cebe077a4dcc4f0683?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59cb19cebe077a4dcc4f0683?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Issue moved to [AllanWang/KAU #86](https://github.com/AllanWang/KAU/issues/86) via [**ZenHub**](https://www.zenhub.com/)
