### ISSUE TITLE
Downsampler.java line 485

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#346]
#### in com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59cb986bbe077a4dcc55449f?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59cb986bbe077a4dcc55449f?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
OOM
