### ISSUE TITLE
GlideExecutor.java line 347

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#349]
#### in com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59cc2961be077a4dcc5d7b7a?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59cc2961be077a4dcc5d7b7a?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
OOM
