### ISSUE TITLE
ViewTreeObserver.java line 944

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#351]
#### in android.view.ViewTreeObserver.dispatchOnPreDraw

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59cd754ebe077a4dcc6d4286?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59cd754ebe077a4dcc6d4286?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Relevant?

https://stackoverflow.com/questions/36666091/attempt-to-invoke-virtual-method-android-view-windowcallback-android-view-wind
