### ISSUE TITLE
RequestBuilder.java line 335

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#363]
#### in com.bumptech.glide.RequestBuilder.clone

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59d60b62be077a4dccc8653d?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59d60b62be077a4dccc8653d?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
OOM
