### ISSUE TITLE
GroupedLinkedMap.java line 43

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#372]
#### in com.bumptech.glide.load.engine.bitmap_recycle.GroupedLinkedMap.get

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59d8664dbe077a4dcce25c4f?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59d8664dbe077a4dcce25c4f?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
OOM related to old im fetcher
