### ISSUE TITLE
DialogUtils.java line 172

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#377]
#### in com.afollestad.materialdialogs.util.DialogUtils.resolveDrawable

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59da60babe077a4dccf5cd40?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59da60babe077a4dccf5cd40?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Resource not found
