### ISSUE TITLE
HctNubiaEventsCheck.java line 607

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#378]
#### in com.hct.android.util.HctNubiaEventsCheck.adjustVolume

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59da9bbfbe077a4dccf804f5?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59da9bbfbe077a4dccf804f5?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Unrelated?
