### ISSUE TITLE
Swipe sensitivity 

### ISSUE THREAD

**Issue by rancidfrog** [AllanWang/Frost-for-Facebook#384]
Swipe does not work for people you may know due to sensitivity, it swipes to next view/tab messages.

Also, is there a way to hide it?

**Comment by AllanWang** [comment]
For now, if you press and hold, it will disable viewpager swipes and allow for webview swipes. You also have the option to disable viewpager swipes altogether in the settings. Eventually I will add options to only switch tabs if the swipe is from the sides
