### ISSUE TITLE
Add to Fdroid

### ISSUE THREAD

**Issue by jerryn70** [AllanWang/Frost-for-Facebook#392]
Plz add this app to fdroid

**Comment by AllanWang** [comment]
As of now, it looks like Frost is not compatible to the [guidelines](https://f-droid.org/wiki/page/Inclusion_Policy). I'd have to remove crashlytics, and I have to verify whether other components (such as linking to the play store version) is allowed.

**Comment by jerryn70** [comment]
I think you should release 2 versions. play store version and fdroid version. fdroid version don't contain crashlytics . 

or can you add option to disable crashlytics in the app.

**Comment by AllanWang** [comment]
This is no longer a priority for frost. There are too many things that make this app not FOSS, and there is a lot to work on to get to that point. I also heavily rely on crashlytics for bug fixing

**Comment by AllanWang** [comment]
Users are always free to download a version outside of the play store through github releases

**Comment by LoneFenris** [comment]
Just thought I'd note in case this ever comes up again that when crashlytics-using devs want to be on Fdroid, the usual way to go about it seems to be using build flavors to allow Fdroid to build a version without it (and other non-FOSS pieces).

**Comment by AllanWang** [comment]
Yes I understand. I'll have more time to look into it after finals. Before, I had a lot of bugs I had to address and didn't want to focus creating a new flavour and managing new builds that won't help with debugging. Another constraint I'd have before using Fdroid is the ability to automate new releases. I haven't looked into that yet but I'd be surprised if it doesn't exist.
