### ISSUE TITLE
KPref.kt line 30

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#398]
#### in ca.allanwang.kau.kpref.KPref.initialize

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59deeba161b02d480d6caa44?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59deeba161b02d480d6caa44?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Old build
