### ISSUE TITLE
MediaHTTPConnectionEx.java line 262

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#435]
#### in com.lge.media.MediaHTTPConnectionEx.seekTo

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59ea634161b02d480deb85c7?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59ea634161b02d480deb85c7?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Old lge media
