### ISSUE TITLE
Binder.java

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#442]
#### in android.os.BinderProxy.destroy

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59eef58261b02d480d1aa373?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59eef58261b02d480d1aa373?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Unavoidable issue unless wakelocks are used :/
