### ISSUE TITLE
CaptioningManager.java line 226

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#453]
#### in android.view.accessibility.CaptioningManager$1.onChange

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59f2f0fb61b02d480d47adbd?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59f2f0fb61b02d480d47adbd?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Check url before getPath
