### ISSUE TITLE
Kotterknife.kt line 138

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#457]
#### in ca.allanwang.kau.utils.KotterknifeKt.bindOptionalView

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59f4d96561b02d480d5e3bef?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59f4d96561b02d480d5e3bef?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Activity was unused and is now removed
