### ISSUE TITLE
Attributes.java line 67

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#477]
#### in org.jsoup.nodes.Attributes.getIgnoreCase

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a047a4c61b02d480d136203?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a047a4c61b02d480d136203?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Follow up here https://github.com/jhy/jsoup/issues/944
