### ISSUE TITLE
StringsJVM.kt

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#48]
#### in kotlin.text.StringsKt__StringsJVMKt.replace

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5963a3e6be077a4dcc56af0c?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5963a3e6be077a4dcc56af0c?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Fixed with null check
