### ISSUE TITLE
FrostVideoView.kt line 121

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#481]
#### in com.pitchedapps.frost.views.FrostVideoView.

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost.test/issues/5a05412b61b02d480d1ce1d2?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost.test/issues/5a05412b61b02d480d1ce1d2?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Fixed. Was a bug during testing
