### ISSUE TITLE
Matcher.java

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#488]
#### in java.util.regex.Matcher.closeImpl

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a09d32761b02d480d5a27e0?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a09d32761b02d480d5a27e0?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Relevant

https://stackoverflow.com/questions/24021609/how-to-handle-java-util-concurrent-timeoutexception-android-os-binderproxy-fin
