### ISSUE TITLE
ActivityUtils.kt line 49

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#497]
#### in ca.allanwang.kau.utils.ActivityUtilsKt.startActivityForResult

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a0ee6c661b02d480da39af4?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a0ee6c661b02d480da39af4?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Issue moved to [AllanWang/KAU #107](https://github.com/AllanWang/KAU/issues/107) via [**ZenHub**](https://www.zenhub.com/)
