### ISSUE TITLE
Facebook Nav Missing on screens with 1920 x 1200

### ISSUE THREAD

**Issue by ZenHarbinger** [AllanWang/Frost-for-Facebook#506]
Using 2 different profiles in android-studio as well as my own device (NVIDIA Shield Tablet).

The icons for notifications, menu, message, and feed do not appear.
The profile pictured below is a Nexus 7 w/ 1920x1200.  Fails in landscape and portrait.

![screenshot from 2017-11-20 15-38-54](https://user-images.githubusercontent.com/1130510/33040426-0aeff3ba-ce09-11e7-92d1-379a7b0f2549.png)

If you tell me the general area that this may be fixed in I can take a look myself.

**Comment by AllanWang** [comment]
That's interesting. I had one report on this before and didn't know if it was an in app issue or not.
The icon view I use is custom to allow for the unread badge, so I'm guessing that there is a min size for that and that the toolbar has a fixed size. One solution may be to allow the toolbar to expand, or to allow that icon to shrink.

I've never had a tablet and my laptop is too slow to run the vm, so if I get to this I'll give you some test builds.

**Comment by AllanWang** [comment]
Relevant files

* [Badge Icon](https://github.com/AllanWang/Frost-for-Facebook/blob/dev/app/src/main/kotlin/com/pitchedapps/frost/views/BadgedIcon.kt)
* [Badge Icon Layout](https://github.com/AllanWang/Frost-for-Facebook/blob/dev/app/src/main/res/layout/view_badged_icon.xml) (with fixed height)
* [Main Activity Layout](https://github.com/AllanWang/Frost-for-Facebook/blob/dev/app/src/main/res/layout/activity_main.xml) (with attr based height).

The issue is likely a varying value for `?attr/actionBarSize`. I thought it was the same for all devices, but I guess not

**Comment by ZenHarbinger** [comment]
I e-mailed from the play store a couple weeks ago about this, it may have been me (probably way).  You said the same thing before too.  But I wanted to make sure, so I grabbed and tested w/ the android studio to check.  w/ the 2 instances at 1900x1200, no go, w/ a Nexus 5 at 1900x1080 (and also I have a physical one) it worked.

I'll dig around, no promises, but at least I'm pretty sure that the resolution is the problem.

**Comment by ZenHarbinger** [comment]
OK, I don't think it's about the resolution.
I think it's actually about the size of the device:

# Fails
 - I/System.out: DisplayMetrics{density=2.0, width=1200, height=1824, scaledDensity=2.0, xdpi=320.0, ydpi=320.0}
   - **8"** 1920x1080 (Custom)
- I/System.out: DisplayMetrics{density=2.0, width=1200, height=1824, scaledDensity=2.0, xdpi=320.0, ydpi=320.0}
  - **7"** 1920x1080 (Nexus 7)
- I/System.out: DisplayMetrics{density=1.0, width=600, height=976, scaledDensity=1.0, xdpi=160.0, ydpi=160.0}
  - **7"** 1024 x 600 (7" WSVGA (Tablet))

# Works
 - I/System.out: DisplayMetrics{density=3.0, width=1080, height=1776, scaledDensity=3.0, xdpi=480.0, ydpi=480.0}
   - **5"** 1080x1920 (Nexus 5)
 - I/System.out: DisplayMetrics{density=2.0, width=768, height=1184, scaledDensity=2.0, xdpi=320.0, ydpi=320.0}
   - **4"** 768x1280 (Nexus 4)
 - I/System.out: DisplayMetrics{density=3.5, width=1440, height=2712, scaledDensity=3.5, xdpi=560.0, ydpi=560.0}
   - **5.99"** 1440x2880 (Pixel 2 XL)

## Commonality
All of the *FAIL* are listed as *Tablet* in the Android Studio - Virtual Device Configuration.

I can only imaging that something is happening w/ the loading of the ***phone*** resources listed in the application.  The menus can be pressed, but all 4 tabs are in the center and next to each other instead of spread out over the width of the screen.

I am not familiar enough w/ Android to figure this part out, but maybe this will help someone else.

**Comment by AllanWang** [comment]
I don't think being a tablet causes it to fail to load resources, but I do believe tablets may have a different set of dimensions. Maybe you can show layout bounds and take a screenshot to see if anything is there at all?

**Comment by ZenHarbinger** [comment]
OK, here's the layout bounds.

Emulated Nexus 7:
![screenshot_1511286668](https://user-images.githubusercontent.com/1130510/33088129-b9f8c812-ceba-11e7-9a38-bf4728f6cb59.png)

Physical NVIDIA Shield (8" 1920x1200):
![screenshot_20171121-124644](https://user-images.githubusercontent.com/1130510/33088195-f31d7ae8-ceba-11e7-8fda-cfceea0a3415.png)

My instinct is telling me it's something about the [intro_phone_tab.xml](https://github.com/AllanWang/Frost-for-Facebook/blob/dev/app/src/main/res/drawable/intro_phone_tab.xml) But I'm not an expert and am only able to guess.

**Comment by ZenHarbinger** [comment]
Understood.  It was the closest I could see to being like the main screen, but I also see why changing things here changed nothing in the emulators.  Naming makes sense too.

Each one of those rectangles is the button and can be pressed, just no badge and it's not spaced out like you expect.  I was thinking it was something about the display metrics, but nothing seemed consistent there.

**Comment by AllanWang** [comment]
Try this

https://github.com/AllanWang/Frost-for-Facebook-APK-Builder/releases/tag/v1581

**Comment by ZenHarbinger** [comment]
Yes, that works on my tablet, what changed?

**Comment by AllanWang** [comment]
Can you send me a screenshot actually? The first thing I did was force everything to fill the screen width. For tablets, tabs font do that. Then I set a minimum width to ensure that everything isn't collapsed. I think only the latter is needed, but I want to see how it'll look if it's spread out across such a big screen

**Comment by ZenHarbinger** [comment]
![screenshot_20171122-122319](https://user-images.githubusercontent.com/1130510/33141112-23ee2260-cf80-11e7-812d-0bf8b756e250.png)

Do you want layout lines too?  I think it looks ok,

**Comment by AllanWang** [comment]
I guess from the screenshot it looks exactly like the mobile version. I'll leave it like so for now. Thanks for the report and send any other bugs you find!
