### ISSUE TITLE
ExoMediaPlayer.java line 161

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#507]
#### in com.devbrackets.android.exomedia.core.exoplayer.ExoMediaPlayer.

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a13ffbb61b02d480de9367a?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a13ffbb61b02d480de9367a?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Issue moved to [AllanWang/KAU #108](https://github.com/AllanWang/KAU/issues/108) via [**ZenHub**](https://www.zenhub.com/)
