### ISSUE TITLE
CharacterReader.java line 54

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#511]
#### in org.jsoup.parser.CharacterReader.bufferUp

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a15070261b02d480df9b94a?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a15070261b02d480df9b94a?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
See https://github.com/jhy/jsoup/issues/980
