### ISSUE TITLE
Frost user agent shows up as 'BlackBerry OS' on Facebook

### ISSUE THREAD

**Issue by nikw92** [AllanWang/Frost-for-Facebook#514]
Not really an issue but I'm just curious about why it shows up this way.

![Imgur](https://i.imgur.com/9FCTAz1.png)

**Comment by AllanWang** [comment]
The user agent used for most pages is [here](https://github.com/AllanWang/Frost-for-Facebook/blob/dev/app/src/main/kotlin/com/pitchedapps/frost/facebook/FbConst.kt#L12) and listed as 

```kotlin
const val USER_AGENT_BASIC = "Mozilla/5.0 (BB10; Kbd) AppleWebKit/537.10+ (KHTML, like Gecko) Version/10.1.0.4633 Mobile Safari/537.10+"
```

So yes, it is listed as a blackberry. This is necessary as Facebook is gradually going away from their website and forcing mobile users to download their app. Messages for example, will not load on any new user agent. Given that I have pip videos, I also use it for the newsfeed, and essentially anything that isn't the comment section so I can still support tagging.

**Comment by nikw92** [comment]
Makes sense. Thanks for your response.
