### ISSUE TITLE
Blank page when opening external links

### ISSUE THREAD

**Issue by ruihildt** [AllanWang/Frost-for-Facebook#515]
When you click on an external link, it opens in your default browser (in my case Firefox), but instead of staying where you are, the page turns blank.

(Thank you for you app, it saved my facebook used, and delayed a bit the suppression of my facebook account ;) )

**Comment by AllanWang** [comment]
Do you have open links in default browser checked? Are themes and other js features working?

I can't seem to replicate the issue on my device

**Comment by ruihildt** [comment]
I have open links in default browser checked. Everything else is working fine.

How can I give you debug info?

**Comment by AllanWang** [comment]
If you click on a "comments" section, does that load in a new overlay or does it load in the same screen?
If you have a link that isn't sensitive, a screen recording would be nice.

The only reason I can think of if that failed is if the app wasn't notified to stop loading once it loaded its overlay.

And to confirm, what version are you using?

**Comment by ruihildt** [comment]
When I click in a "comments" section, it loads on the same screen. (no overlay that I can close with X)

Here's a link to a screencast: https://cloud.armada.digital/index.php/s/HpQcXMkVrzY2MPg
*the screencast is laggy because of the capture, I don't experience lag at all while using Frost*

Frost version: `1.6.6`

**Comment by AllanWang** [comment]
I'm not sure if this is related to Firefox queuing links rather than opening it directly. I downloaded Firefox recently but forgot to test this, but I will look into it for the future and get back to you

**Comment by AllanWang** [comment]
@ruihildt can you try again with [this](https://github.com/AllanWang/Frost-for-Facebook-APK-Builder/releases/tag/v1650) build? I tested it on my developer phone and couldn't replicate the issue, though firefox directly opened the webpage when requested.

**Comment by ruihildt** [comment]
So I tested with this build, and the bug is gone. :)

The bug is still present on 1.7

**Comment by AllanWang** [comment]
v1.7.0 Is pretty old now compared to the test build. You may either join beta to get v1.7.3 or wait until I push something to the public channel (which should happen within the next few days)
