### ISSUE TITLE
Prefs.kt line 50

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#517]
#### in com.pitchedapps.frost.utils.Prefs$loader$1.invoke

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a1932f661b02d480d39bfa3?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a1932f661b02d480d39bfa3?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Someone was manually messing with the tag?
