### ISSUE TITLE
FbUrlFormatter.kt

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#52]
#### in com.pitchedapps.frost.facebook.FbUrlFormatterKt.getFormattedFbUrl

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5964ab57be077a4dcc608f34?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5964ab57be077a4dcc608f34?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Fixed with null checks 77896b3d09ea88d005f94851e7a2014c9576f303
