### ISSUE TITLE
ViewUtils.kt line 90

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#521]
#### in ca.allanwang.kau.utils.ViewUtilsKt.snackbar

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a1b40af61b02d480d554607?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a1b40af61b02d480d554607?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Not my build
