### ISSUE TITLE
FrostWebViewCore.kt line 31

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#527]
#### in com.pitchedapps.frost.web.FrostWebViewCore.

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a207bc961b02d480d9bcfa3?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a207bc961b02d480d9bcfa3?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
webview not installed?

**Comment by AllanWang** [comment]
oom
