### ISSUE TITLE
MessageQueue.java

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#53]
#### in android.os.MessageQueue.nativePollOnce

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59652075be077a4dcc6625a5?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/59652075be077a4dcc6625a5?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
May be related to [scene animations](https://stackoverflow.com/questions/26626344/scene-transition-with-hero-elements-throws-layer-exceeds-max-dimensions-support)
