### ISSUE TITLE
SchedulerPoolFactory.java line 129

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#532]
#### in io.reactivex.internal.schedulers.SchedulerPoolFactory$ScheduledTask.run

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a22e3ee61b02d480dbcc332?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a22e3ee61b02d480dbcc332?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
OOM
