### ISSUE TITLE
FinalizerReference.java line 66

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#541]
#### in java.lang.ref.FinalizerReference.remove

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a2bdc188cb3c2fa637ed619?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a2bdc188cb3c2fa637ed619?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
21 threads of `Object.wait()`... 🤔
