### ISSUE TITLE
AndroidDatabase.java line 62

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#542]
#### in com.raizlabs.android.dbflow.structure.database.AndroidDatabase.rawQuery

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost.test/issues/5a2c50118cb3c2fa6385c593?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost.test/issues/5a2c50118cb3c2fa6385c593?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Xposed
