### ISSUE TITLE
JavaHandlerThread.java line 8

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#544]
#### in org.chromium.base.JavaHandlerThread.maybeStart

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a2cb5278cb3c2fa6389dc13?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a2cb5278cb3c2fa6389dc13?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
OOM on a pixel 2???
