### ISSUE TITLE
ColorPickerView.kt line 271

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#549]
#### in ca.allanwang.kau.colorpicker.ColorPickerView$ColorGridAdapter.onClick

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a2f19988cb3c2fa63ab44b4?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a2f19988cb3c2fa63ab44b4?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Issue moved to [AllanWang/KAU #114](https://github.com/AllanWang/KAU/issues/114) via [**ZenHub**](https://www.zenhub.com/)
