### ISSUE TITLE
Parcel.java line 1546

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#562]
#### in android.os.Parcel.readException

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a3630658cb3c2fa6310803a?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a3630658cb3c2fa6310803a?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
AOSP bug

https://issuetracker.google.com/issues/37018640
