### ISSUE TITLE
RouteSelector.java line 290

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#587]
#### in com.android.okhttp.internal.http.RouteSelector.nextTlsMode

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a485b438cb3c2fa63f40081?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a485b438cb3c2fa63f40081?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
v1.5.3 is very old
