### ISSUE TITLE
SimpleTarget.java line 64

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#588]
#### in com.bumptech.glide.request.target.SimpleTarget.getSize

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a488a948cb3c2fa63f593f7?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a488a948cb3c2fa63f593f7?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Preset to 48?

**Comment by AllanWang** [comment]
Candidiate: Load px upon service start and use Completables to keep service alive during the process
