### ISSUE TITLE
Linux.java

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#637]
#### in libcore.io.Linux.android_getaddrinfo

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a5b60f48cb3c2fa63d1e895?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a5b60f48cb3c2fa63d1e895?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
TODO. Modify "Done propagation" log
