### ISSUE TITLE
Timeout.java line 145

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#641]
#### in okio.Timeout.throwIfReached

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a5bea598cb3c2fa63d86586?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/5a5bea598cb3c2fa63d86586?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
See https://github.com/ReactiveX/RxJava/issues/4863#issuecomment-282980001
