### ISSUE TITLE
FlowSQLiteOpenHelper.java line 62

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#77]
#### in com.raizlabs.android.dbflow.structure.database.FlowSQLiteOpenHelper.getDatabase

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/597058a5be077a4dccd6a1bd?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/597058a5be077a4dccd6a1bd?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Not my issue
