### ISSUE TITLE
Pulled?

### ISSUE THREAD

**Issue by creativetrendsapps** [AllanWang/Frost-for-Facebook#844]
Has this app been pulled from the Play Store?

**Comment by AllanWang** [comment]
It has been pulled. See [here](https://forum.xda-developers.com/showpost.php?p=75948383&postcount=175). I'm still working on it and delivering it independently

**Comment by creativetrendsapps** [comment]
Sorry to see this. Are pro options still available? I purchased pro so I'm not sure how that goes as far as license checks from Google Play since the app was pulled.

**Comment by AllanWang** [comment]
As you now saw on [xda](https://forum.xda-developers.com/android/apps-games/app-frost-facebook-t3685896/post75948383#post75948383), everything is now free.

**Comment by creativetrendsapps** [comment]
Sorry, didn't read the entire XDA post. Thanks for the clarification.
