### ISSUE TITLE
Add slack url

### ISSUE THREAD

**Issue by AllanWang** [AllanWang/Frost-for-Facebook#880]
https://frost-slack.allanwang.ca/

**Comment by sevospl** [comment]
"This invite link is no longer active.
Please check with the person who shared it with you to see if there's a new link available."

Mind updating it? :)

**Comment by AllanWang** [comment]
Updated to https://join.slack.com/t/frost-for-facebook/shared_invite/enQtODEyNzAzMzYxMDc3LTYzYjQ2N2JmOTA1NTYyODYyM2EzYTFhZTIwZTU0ZTZkN2EzZWZiNzZmMGMzNGIwYjBhOWQ4ZGRlZTJiMjk2OTk <https://join.slack.com/t/frost-for-facebook/shared_invite/enQtODEyNzAzMzYxMDc3LTYzYjQ2N2JmOTA1NTYyODYyM2EzYTFhZTIwZTU0ZTZkN2EzZWZiNzZmMGMzNGIwYjBhOWQ4ZGRlZTJiMjk2OTk>

The redirect will take time to propagate
