### ISSUE TITLE
Add icons in notifications

### ISSUE THREAD

**Issue by androidghosh** [AllanWang/Frost-for-Facebook#919]
In notification tab when someone comments or when someone shares my post, the notification comes are all looks the same. So it's hard to notice when someone comments. So can you please add little icon in the left/right side of each notification to make it noticeable?

**Comment by AllanWang** [comment]
Things like this aren't easy to showcase, because I don't get much information about the actual notification beyond the text and link. I may look into checking the link detail, but other than that, there is no reliable way of telling the notification type

**Comment by AllanWang** [comment]
We can still discuss about this, but I can't think of any good ways to make visibly different icons for the status bar.

For comments, they are usually associated with a person, so the bigger avatar is already taken.

I also don't think facebook distinguishes between these notifications; it would not be great UX for people to see many different icons associated with a single app.
