### ISSUE TITLE
ImageModel.kt line 22

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#97]
#### in ca.allanwang.kau.imagepicker.ImageModel.

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/597ae83dbe077a4dcc3e4489?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/597ae83dbe077a4dcc3e4489?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Addressed in KAU
