### ISSUE TITLE
BoundedCardView.kt line 49

### ISSUE THREAD

**Issue by asdfasdfvful** [AllanWang/Frost-for-Facebook#98]
#### in ca.allanwang.kau.ui.views.BoundedCardView.onMeasure

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/597b37afbe077a4dcc41ed02?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/pitched-apps/android/apps/com.pitchedapps.frost/issues/597b37afbe077a4dcc41ed02?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by AllanWang** [comment]
Occurs with very rapid changes in cardview height

**Comment by AllanWang** [comment]
Fixed in KAU: https://github.com/AllanWang/KAU/commit/39cc76551f6622c1f6a95b9d1342381a75622376
